// Code generated by ent, DO NOT EDIT.

package imbot

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the imbot type in the database.
	Label = "im_bot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldCredentialsEncrypted holds the string denoting the credentials_encrypted field in the database.
	FieldCredentialsEncrypted = "credentials_encrypted"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldModelOverride holds the string denoting the model_override field in the database.
	FieldModelOverride = "model_override"
	// FieldSystemPrompt holds the string denoting the system_prompt field in the database.
	FieldSystemPrompt = "system_prompt"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMaxConcurrency holds the string denoting the max_concurrency field in the database.
	FieldMaxConcurrency = "max_concurrency"
	// FieldHistoryMaxMessages holds the string denoting the history_max_messages field in the database.
	FieldHistoryMaxMessages = "history_max_messages"
	// FieldPairingEnabled holds the string denoting the pairing_enabled field in the database.
	FieldPairingEnabled = "pairing_enabled"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// EdgeAPIKey holds the string denoting the api_key edge name in mutations.
	EdgeAPIKey = "api_key"
	// EdgeChats holds the string denoting the chats edge name in mutations.
	EdgeChats = "chats"
	// Table holds the table name of the imbot in the database.
	Table = "im_bots"
	// APIKeyTable is the table that holds the api_key relation/edge.
	APIKeyTable = "im_bots"
	// APIKeyInverseTable is the table name for the APIKey entity.
	// It exists in this package in order to avoid circular dependency with the "apikey" package.
	APIKeyInverseTable = "api_keys"
	// APIKeyColumn is the table column denoting the api_key relation/edge.
	APIKeyColumn = "api_key_id"
	// ChatsTable is the table that holds the chats relation/edge.
	ChatsTable = "im_bot_chats"
	// ChatsInverseTable is the table name for the IMBotChat entity.
	// It exists in this package in order to avoid circular dependency with the "imbotchat" package.
	ChatsInverseTable = "im_bot_chats"
	// ChatsColumn is the table column denoting the chats relation/edge.
	ChatsColumn = "bot_id"
)

// Columns holds all SQL columns for imbot fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldPlatform,
	FieldCredentialsEncrypted,
	FieldAPIKeyID,
	FieldModelOverride,
	FieldSystemPrompt,
	FieldStatus,
	FieldMaxConcurrency,
	FieldHistoryMaxMessages,
	FieldPairingEnabled,
	FieldLastError,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// DefaultModelOverride holds the default value on creation for the "model_override" field.
	DefaultModelOverride string
	// ModelOverrideValidator is a validator for the "model_override" field. It is called by the builders before save.
	ModelOverrideValidator func(string) error
	// DefaultSystemPrompt holds the default value on creation for the "system_prompt" field.
	DefaultSystemPrompt string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultMaxConcurrency holds the default value on creation for the "max_concurrency" field.
	DefaultMaxConcurrency int
	// DefaultHistoryMaxMessages holds the default value on creation for the "history_max_messages" field.
	DefaultHistoryMaxMessages int
	// DefaultPairingEnabled holds the default value on creation for the "pairing_enabled" field.
	DefaultPairingEnabled bool
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
)

// OrderOption defines the ordering options for the IMBot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByCredentialsEncrypted orders the results by the credentials_encrypted field.
func ByCredentialsEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCredentialsEncrypted, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByModelOverride orders the results by the model_override field.
func ByModelOverride(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelOverride, opts...).ToFunc()
}

// BySystemPrompt orders the results by the system_prompt field.
func BySystemPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSystemPrompt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByMaxConcurrency orders the results by the max_concurrency field.
func ByMaxConcurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxConcurrency, opts...).ToFunc()
}

// ByHistoryMaxMessages orders the results by the history_max_messages field.
func ByHistoryMaxMessages(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHistoryMaxMessages, opts...).ToFunc()
}

// ByPairingEnabled orders the results by the pairing_enabled field.
func ByPairingEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPairingEnabled, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByAPIKeyField orders the results by api_key field.
func ByAPIKeyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIKeyStep(), sql.OrderByField(field, opts...))
	}
}

// ByChatsCount orders the results by chats count.
func ByChatsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChatsStep(), opts...)
	}
}

// ByChats orders the results by chats terms.
func ByChats(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChatsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAPIKeyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIKeyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
	)
}
func newChatsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChatsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChatsTable, ChatsColumn),
	)
}
