package clashsub

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// LocalEndpoint is one local listener Sub2API should point at.
type LocalEndpoint struct {
	Name     string
	NodeName string
	Port     int
	Protocol string
	Host     string
}

// Binding maps a selected node to a local port and Sub2API proxy name.
type Binding struct {
	Node     Node
	Port     int
	Name     string
	Protocol string
	Host     string
}

// BuildBindings assigns ports by stable identity order and names without port suffix.
func BuildBindings(nodes []Node, prefix, host, protocol string, basePort, max int, allowContains []string) ([]Binding, error) {
	selected, err := SelectNodes(nodes, max, allowContains)
	if err != nil {
		return nil, err
	}
	// Re-sort by identity so port index is deterministic across subscription reshuffles
	// that still include the same set (SelectNodes preserves input order which is already sorted).
	sort.SliceStable(selected, func(i, j int) bool {
		return selected[i].Identity < selected[j].Identity
	})
	out := make([]Binding, 0, len(selected))
	for i, n := range selected {
		port := basePort + i
		name := StableProxyName(prefix, n.Identity, n.Name)
		out = append(out, Binding{
			Node:     n,
			Port:     port,
			Name:     name,
			Protocol: protocol,
			Host:     host,
		})
	}
	return out, nil
}

// WriteMihomoConfig writes a multi-listener mihomo config (mode 0600).
// Returns content SHA256 hex for restart-change detection.
func WriteMihomoConfig(path string, bindAddr, namePrefix string, bindings []Binding) (string, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return "", err
	}

	proxies := make([]map[string]any, 0, len(bindings))
	listeners := make([]map[string]any, 0, len(bindings))
	names := make([]string, 0, len(bindings))

	for _, b := range bindings {
		raw := cloneMap(b.Node.Raw)
		proxyName := fmt.Sprintf("n-%s", short(b.Name, namePrefix))
		raw["name"] = proxyName
		proxies = append(proxies, raw)
		names = append(names, proxyName)
		listeners = append(listeners, map[string]any{
			"name":   fmt.Sprintf("in-%d", b.Port),
			"type":   "mixed",
			"port":   b.Port,
			"listen": bindAddr,
			"proxy":  proxyName,
		})
	}

	doc := map[string]any{
		"mixed-port":          0,
		"allow-lan":           false,
		"bind-address":        bindAddr,
		"mode":                "global",
		"log-level":           "info",
		"ipv6":                false,
		"external-controller": "",
		"proxies":             proxies,
		"proxy-groups": []map[string]any{
			{
				"name":    "SIDECAR",
				"type":    "select",
				"proxies": names,
			},
		},
		"listeners": listeners,
		"rules": []string{
			"MATCH,SIDECAR",
		},
	}

	data, err := yaml.Marshal(doc)
	if err != nil {
		return "", err
	}
	header := []byte("# Generated by sub2api proxy-subscription. Do not edit.\n")
	full := append(header, data...)
	sum := sha256.Sum256(full)
	hash := hex.EncodeToString(sum[:])

	if err := os.WriteFile(path, full, 0o600); err != nil {
		return "", err
	}
	return hash, nil
}

// Runner starts/stops mihomo.
type Runner struct {
	Binary     string
	ConfigPath string
	DataDir    string
	cmd        *exec.Cmd
}

func (r *Runner) Start() error {
	if err := os.MkdirAll(r.DataDir, 0o700); err != nil {
		return err
	}
	r.cmd = exec.Command(r.Binary, "-f", r.ConfigPath, "-d", r.DataDir)
	r.cmd.Stdout = os.Stdout
	r.cmd.Stderr = os.Stderr
	return r.cmd.Start()
}

func (r *Runner) Stop() error {
	if r.cmd == nil || r.cmd.Process == nil {
		return nil
	}
	err := r.cmd.Process.Kill()
	_, _ = r.cmd.Process.Wait()
	r.cmd = nil
	return err
}

func EndpointsFromBindings(bindings []Binding) []LocalEndpoint {
	out := make([]LocalEndpoint, 0, len(bindings))
	for _, b := range bindings {
		out = append(out, LocalEndpoint{
			Name:     b.Name,
			NodeName: b.Node.Name,
			Port:     b.Port,
			Protocol: b.Protocol,
			Host:     b.Host,
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func cloneMap(in map[string]any) map[string]any {
	out := make(map[string]any, len(in))
	for k, v := range in {
		out[k] = v
	}
	return out
}

func short(s, prefix string) string {
	s = strings.TrimPrefix(s, prefix)
	if len(s) > 40 {
		return s[:40]
	}
	return s
}
