// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/imbot"
)

// IMBot is the model entity for the IMBot schema.
type IMBot struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// telegram | feishu | dingtalk | wecom | qq | slack | wechat | whatsapp
	Platform string `json:"platform,omitempty"`
	// AES-256-GCM encrypted platform credential JSON
	CredentialsEncrypted string `json:"credentials_encrypted,omitempty"`
	// Bound API key used for gateway calls.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// ModelOverride holds the value of the "model_override" field.
	ModelOverride string `json:"model_override,omitempty"`
	// SystemPrompt holds the value of the "system_prompt" field.
	SystemPrompt string `json:"system_prompt,omitempty"`
	// enabled | disabled | error
	Status string `json:"status,omitempty"`
	// MaxConcurrency holds the value of the "max_concurrency" field.
	MaxConcurrency int `json:"max_concurrency,omitempty"`
	// HistoryMaxMessages holds the value of the "history_max_messages" field.
	HistoryMaxMessages int `json:"history_max_messages,omitempty"`
	// PairingEnabled holds the value of the "pairing_enabled" field.
	PairingEnabled bool `json:"pairing_enabled,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError string `json:"last_error,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the IMBotQuery when eager-loading is set.
	Edges        IMBotEdges `json:"edges"`
	selectValues sql.SelectValues
}

// IMBotEdges holds the relations/edges for other nodes in the graph.
type IMBotEdges struct {
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// Chats holds the value of the chats edge.
	Chats []*IMBotChat `json:"chats,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IMBotEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// ChatsOrErr returns the Chats value or an error if the edge
// was not loaded in eager-loading.
func (e IMBotEdges) ChatsOrErr() ([]*IMBotChat, error) {
	if e.loadedTypes[1] {
		return e.Chats, nil
	}
	return nil, &NotLoadedError{edge: "chats"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IMBot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case imbot.FieldPairingEnabled:
			values[i] = new(sql.NullBool)
		case imbot.FieldID, imbot.FieldAPIKeyID, imbot.FieldMaxConcurrency, imbot.FieldHistoryMaxMessages:
			values[i] = new(sql.NullInt64)
		case imbot.FieldName, imbot.FieldPlatform, imbot.FieldCredentialsEncrypted, imbot.FieldModelOverride, imbot.FieldSystemPrompt, imbot.FieldStatus, imbot.FieldLastError:
			values[i] = new(sql.NullString)
		case imbot.FieldCreatedAt, imbot.FieldUpdatedAt, imbot.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IMBot fields.
func (_m *IMBot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case imbot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case imbot.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case imbot.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case imbot.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case imbot.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case imbot.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case imbot.FieldCredentialsEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credentials_encrypted", values[i])
			} else if value.Valid {
				_m.CredentialsEncrypted = value.String
			}
		case imbot.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case imbot.FieldModelOverride:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_override", values[i])
			} else if value.Valid {
				_m.ModelOverride = value.String
			}
		case imbot.FieldSystemPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field system_prompt", values[i])
			} else if value.Valid {
				_m.SystemPrompt = value.String
			}
		case imbot.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case imbot.FieldMaxConcurrency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_concurrency", values[i])
			} else if value.Valid {
				_m.MaxConcurrency = int(value.Int64)
			}
		case imbot.FieldHistoryMaxMessages:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field history_max_messages", values[i])
			} else if value.Valid {
				_m.HistoryMaxMessages = int(value.Int64)
			}
		case imbot.FieldPairingEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field pairing_enabled", values[i])
			} else if value.Valid {
				_m.PairingEnabled = value.Bool
			}
		case imbot.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IMBot.
// This includes values selected through modifiers, order, etc.
func (_m *IMBot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAPIKey queries the "api_key" edge of the IMBot entity.
func (_m *IMBot) QueryAPIKey() *APIKeyQuery {
	return NewIMBotClient(_m.config).QueryAPIKey(_m)
}

// QueryChats queries the "chats" edge of the IMBot entity.
func (_m *IMBot) QueryChats() *IMBotChatQuery {
	return NewIMBotClient(_m.config).QueryChats(_m)
}

// Update returns a builder for updating this IMBot.
// Note that you need to call IMBot.Unwrap() before calling this method if this IMBot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IMBot) Update() *IMBotUpdateOne {
	return NewIMBotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IMBot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IMBot) Unwrap() *IMBot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IMBot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IMBot) String() string {
	var builder strings.Builder
	builder.WriteString("IMBot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("credentials_encrypted=")
	builder.WriteString(_m.CredentialsEncrypted)
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("model_override=")
	builder.WriteString(_m.ModelOverride)
	builder.WriteString(", ")
	builder.WriteString("system_prompt=")
	builder.WriteString(_m.SystemPrompt)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("max_concurrency=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxConcurrency))
	builder.WriteString(", ")
	builder.WriteString("history_max_messages=")
	builder.WriteString(fmt.Sprintf("%v", _m.HistoryMaxMessages))
	builder.WriteString(", ")
	builder.WriteString("pairing_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.PairingEnabled))
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteByte(')')
	return builder.String()
}

// IMBots is a parsable slice of IMBot.
type IMBots []*IMBot
