// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imbot"
	"github.com/Wei-Shaw/sub2api/ent/imbotchat"
	"github.com/Wei-Shaw/sub2api/ent/imbotmessage"
)

// IMBotChatCreate is the builder for creating a IMBotChat entity.
type IMBotChatCreate struct {
	config
	mutation *IMBotChatMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *IMBotChatCreate) SetCreatedAt(v time.Time) *IMBotChatCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IMBotChatCreate) SetNillableCreatedAt(v *time.Time) *IMBotChatCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IMBotChatCreate) SetUpdatedAt(v time.Time) *IMBotChatCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IMBotChatCreate) SetNillableUpdatedAt(v *time.Time) *IMBotChatCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetBotID sets the "bot_id" field.
func (_c *IMBotChatCreate) SetBotID(v int64) *IMBotChatCreate {
	_c.mutation.SetBotID(v)
	return _c
}

// SetChatID sets the "chat_id" field.
func (_c *IMBotChatCreate) SetChatID(v string) *IMBotChatCreate {
	_c.mutation.SetChatID(v)
	return _c
}

// SetPlatformUserID sets the "platform_user_id" field.
func (_c *IMBotChatCreate) SetPlatformUserID(v string) *IMBotChatCreate {
	_c.mutation.SetPlatformUserID(v)
	return _c
}

// SetNillablePlatformUserID sets the "platform_user_id" field if the given value is not nil.
func (_c *IMBotChatCreate) SetNillablePlatformUserID(v *string) *IMBotChatCreate {
	if v != nil {
		_c.SetPlatformUserID(*v)
	}
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *IMBotChatCreate) SetDisplayName(v string) *IMBotChatCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *IMBotChatCreate) SetNillableDisplayName(v *string) *IMBotChatCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetSessionUUID sets the "session_uuid" field.
func (_c *IMBotChatCreate) SetSessionUUID(v string) *IMBotChatCreate {
	_c.mutation.SetSessionUUID(v)
	return _c
}

// SetModelOverride sets the "model_override" field.
func (_c *IMBotChatCreate) SetModelOverride(v string) *IMBotChatCreate {
	_c.mutation.SetModelOverride(v)
	return _c
}

// SetNillableModelOverride sets the "model_override" field if the given value is not nil.
func (_c *IMBotChatCreate) SetNillableModelOverride(v *string) *IMBotChatCreate {
	if v != nil {
		_c.SetModelOverride(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *IMBotChatCreate) SetStatus(v string) *IMBotChatCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *IMBotChatCreate) SetNillableStatus(v *string) *IMBotChatCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPairedAt sets the "paired_at" field.
func (_c *IMBotChatCreate) SetPairedAt(v time.Time) *IMBotChatCreate {
	_c.mutation.SetPairedAt(v)
	return _c
}

// SetNillablePairedAt sets the "paired_at" field if the given value is not nil.
func (_c *IMBotChatCreate) SetNillablePairedAt(v *time.Time) *IMBotChatCreate {
	if v != nil {
		_c.SetPairedAt(*v)
	}
	return _c
}

// SetLastMessageAt sets the "last_message_at" field.
func (_c *IMBotChatCreate) SetLastMessageAt(v time.Time) *IMBotChatCreate {
	_c.mutation.SetLastMessageAt(v)
	return _c
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_c *IMBotChatCreate) SetNillableLastMessageAt(v *time.Time) *IMBotChatCreate {
	if v != nil {
		_c.SetLastMessageAt(*v)
	}
	return _c
}

// SetBot sets the "bot" edge to the IMBot entity.
func (_c *IMBotChatCreate) SetBot(v *IMBot) *IMBotChatCreate {
	return _c.SetBotID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the IMBotMessage entity by IDs.
func (_c *IMBotChatCreate) AddMessageIDs(ids ...int64) *IMBotChatCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the IMBotMessage entity.
func (_c *IMBotChatCreate) AddMessages(v ...*IMBotMessage) *IMBotChatCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// Mutation returns the IMBotChatMutation object of the builder.
func (_c *IMBotChatCreate) Mutation() *IMBotChatMutation {
	return _c.mutation
}

// Save creates the IMBotChat in the database.
func (_c *IMBotChatCreate) Save(ctx context.Context) (*IMBotChat, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IMBotChatCreate) SaveX(ctx context.Context) *IMBotChat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IMBotChatCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IMBotChatCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IMBotChatCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := imbotchat.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := imbotchat.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.PlatformUserID(); !ok {
		v := imbotchat.DefaultPlatformUserID
		_c.mutation.SetPlatformUserID(v)
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		v := imbotchat.DefaultDisplayName
		_c.mutation.SetDisplayName(v)
	}
	if _, ok := _c.mutation.ModelOverride(); !ok {
		v := imbotchat.DefaultModelOverride
		_c.mutation.SetModelOverride(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := imbotchat.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.PairedAt(); !ok {
		v := imbotchat.DefaultPairedAt()
		_c.mutation.SetPairedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IMBotChatCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "IMBotChat.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "IMBotChat.updated_at"`)}
	}
	if _, ok := _c.mutation.BotID(); !ok {
		return &ValidationError{Name: "bot_id", err: errors.New(`ent: missing required field "IMBotChat.bot_id"`)}
	}
	if _, ok := _c.mutation.ChatID(); !ok {
		return &ValidationError{Name: "chat_id", err: errors.New(`ent: missing required field "IMBotChat.chat_id"`)}
	}
	if v, ok := _c.mutation.ChatID(); ok {
		if err := imbotchat.ChatIDValidator(v); err != nil {
			return &ValidationError{Name: "chat_id", err: fmt.Errorf(`ent: validator failed for field "IMBotChat.chat_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PlatformUserID(); !ok {
		return &ValidationError{Name: "platform_user_id", err: errors.New(`ent: missing required field "IMBotChat.platform_user_id"`)}
	}
	if v, ok := _c.mutation.PlatformUserID(); ok {
		if err := imbotchat.PlatformUserIDValidator(v); err != nil {
			return &ValidationError{Name: "platform_user_id", err: fmt.Errorf(`ent: validator failed for field "IMBotChat.platform_user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "IMBotChat.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := imbotchat.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "IMBotChat.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SessionUUID(); !ok {
		return &ValidationError{Name: "session_uuid", err: errors.New(`ent: missing required field "IMBotChat.session_uuid"`)}
	}
	if v, ok := _c.mutation.SessionUUID(); ok {
		if err := imbotchat.SessionUUIDValidator(v); err != nil {
			return &ValidationError{Name: "session_uuid", err: fmt.Errorf(`ent: validator failed for field "IMBotChat.session_uuid": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ModelOverride(); !ok {
		return &ValidationError{Name: "model_override", err: errors.New(`ent: missing required field "IMBotChat.model_override"`)}
	}
	if v, ok := _c.mutation.ModelOverride(); ok {
		if err := imbotchat.ModelOverrideValidator(v); err != nil {
			return &ValidationError{Name: "model_override", err: fmt.Errorf(`ent: validator failed for field "IMBotChat.model_override": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "IMBotChat.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := imbotchat.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IMBotChat.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PairedAt(); !ok {
		return &ValidationError{Name: "paired_at", err: errors.New(`ent: missing required field "IMBotChat.paired_at"`)}
	}
	if len(_c.mutation.BotIDs()) == 0 {
		return &ValidationError{Name: "bot", err: errors.New(`ent: missing required edge "IMBotChat.bot"`)}
	}
	return nil
}

func (_c *IMBotChatCreate) sqlSave(ctx context.Context) (*IMBotChat, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IMBotChatCreate) createSpec() (*IMBotChat, *sqlgraph.CreateSpec) {
	var (
		_node = &IMBotChat{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(imbotchat.Table, sqlgraph.NewFieldSpec(imbotchat.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(imbotchat.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(imbotchat.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ChatID(); ok {
		_spec.SetField(imbotchat.FieldChatID, field.TypeString, value)
		_node.ChatID = value
	}
	if value, ok := _c.mutation.PlatformUserID(); ok {
		_spec.SetField(imbotchat.FieldPlatformUserID, field.TypeString, value)
		_node.PlatformUserID = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(imbotchat.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.SessionUUID(); ok {
		_spec.SetField(imbotchat.FieldSessionUUID, field.TypeString, value)
		_node.SessionUUID = value
	}
	if value, ok := _c.mutation.ModelOverride(); ok {
		_spec.SetField(imbotchat.FieldModelOverride, field.TypeString, value)
		_node.ModelOverride = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(imbotchat.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.PairedAt(); ok {
		_spec.SetField(imbotchat.FieldPairedAt, field.TypeTime, value)
		_node.PairedAt = value
	}
	if value, ok := _c.mutation.LastMessageAt(); ok {
		_spec.SetField(imbotchat.FieldLastMessageAt, field.TypeTime, value)
		_node.LastMessageAt = &value
	}
	if nodes := _c.mutation.BotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imbotchat.BotTable,
			Columns: []string{imbotchat.BotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imbot.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BotID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imbotchat.MessagesTable,
			Columns: []string{imbotchat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imbotmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IMBotChat.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IMBotChatUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IMBotChatCreate) OnConflict(opts ...sql.ConflictOption) *IMBotChatUpsertOne {
	_c.conflict = opts
	return &IMBotChatUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IMBotChat.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IMBotChatCreate) OnConflictColumns(columns ...string) *IMBotChatUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IMBotChatUpsertOne{
		create: _c,
	}
}

type (
	// IMBotChatUpsertOne is the builder for "upsert"-ing
	//  one IMBotChat node.
	IMBotChatUpsertOne struct {
		create *IMBotChatCreate
	}

	// IMBotChatUpsert is the "OnConflict" setter.
	IMBotChatUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *IMBotChatUpsert) SetUpdatedAt(v time.Time) *IMBotChatUpsert {
	u.Set(imbotchat.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IMBotChatUpsert) UpdateUpdatedAt() *IMBotChatUpsert {
	u.SetExcluded(imbotchat.FieldUpdatedAt)
	return u
}

// SetBotID sets the "bot_id" field.
func (u *IMBotChatUpsert) SetBotID(v int64) *IMBotChatUpsert {
	u.Set(imbotchat.FieldBotID, v)
	return u
}

// UpdateBotID sets the "bot_id" field to the value that was provided on create.
func (u *IMBotChatUpsert) UpdateBotID() *IMBotChatUpsert {
	u.SetExcluded(imbotchat.FieldBotID)
	return u
}

// SetChatID sets the "chat_id" field.
func (u *IMBotChatUpsert) SetChatID(v string) *IMBotChatUpsert {
	u.Set(imbotchat.FieldChatID, v)
	return u
}

// UpdateChatID sets the "chat_id" field to the value that was provided on create.
func (u *IMBotChatUpsert) UpdateChatID() *IMBotChatUpsert {
	u.SetExcluded(imbotchat.FieldChatID)
	return u
}

// SetPlatformUserID sets the "platform_user_id" field.
func (u *IMBotChatUpsert) SetPlatformUserID(v string) *IMBotChatUpsert {
	u.Set(imbotchat.FieldPlatformUserID, v)
	return u
}

// UpdatePlatformUserID sets the "platform_user_id" field to the value that was provided on create.
func (u *IMBotChatUpsert) UpdatePlatformUserID() *IMBotChatUpsert {
	u.SetExcluded(imbotchat.FieldPlatformUserID)
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *IMBotChatUpsert) SetDisplayName(v string) *IMBotChatUpsert {
	u.Set(imbotchat.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *IMBotChatUpsert) UpdateDisplayName() *IMBotChatUpsert {
	u.SetExcluded(imbotchat.FieldDisplayName)
	return u
}

// SetSessionUUID sets the "session_uuid" field.
func (u *IMBotChatUpsert) SetSessionUUID(v string) *IMBotChatUpsert {
	u.Set(imbotchat.FieldSessionUUID, v)
	return u
}

// UpdateSessionUUID sets the "session_uuid" field to the value that was provided on create.
func (u *IMBotChatUpsert) UpdateSessionUUID() *IMBotChatUpsert {
	u.SetExcluded(imbotchat.FieldSessionUUID)
	return u
}

// SetModelOverride sets the "model_override" field.
func (u *IMBotChatUpsert) SetModelOverride(v string) *IMBotChatUpsert {
	u.Set(imbotchat.FieldModelOverride, v)
	return u
}

// UpdateModelOverride sets the "model_override" field to the value that was provided on create.
func (u *IMBotChatUpsert) UpdateModelOverride() *IMBotChatUpsert {
	u.SetExcluded(imbotchat.FieldModelOverride)
	return u
}

// SetStatus sets the "status" field.
func (u *IMBotChatUpsert) SetStatus(v string) *IMBotChatUpsert {
	u.Set(imbotchat.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IMBotChatUpsert) UpdateStatus() *IMBotChatUpsert {
	u.SetExcluded(imbotchat.FieldStatus)
	return u
}

// SetPairedAt sets the "paired_at" field.
func (u *IMBotChatUpsert) SetPairedAt(v time.Time) *IMBotChatUpsert {
	u.Set(imbotchat.FieldPairedAt, v)
	return u
}

// UpdatePairedAt sets the "paired_at" field to the value that was provided on create.
func (u *IMBotChatUpsert) UpdatePairedAt() *IMBotChatUpsert {
	u.SetExcluded(imbotchat.FieldPairedAt)
	return u
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *IMBotChatUpsert) SetLastMessageAt(v time.Time) *IMBotChatUpsert {
	u.Set(imbotchat.FieldLastMessageAt, v)
	return u
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *IMBotChatUpsert) UpdateLastMessageAt() *IMBotChatUpsert {
	u.SetExcluded(imbotchat.FieldLastMessageAt)
	return u
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (u *IMBotChatUpsert) ClearLastMessageAt() *IMBotChatUpsert {
	u.SetNull(imbotchat.FieldLastMessageAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.IMBotChat.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IMBotChatUpsertOne) UpdateNewValues() *IMBotChatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(imbotchat.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IMBotChat.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IMBotChatUpsertOne) Ignore() *IMBotChatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IMBotChatUpsertOne) DoNothing() *IMBotChatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IMBotChatCreate.OnConflict
// documentation for more info.
func (u *IMBotChatUpsertOne) Update(set func(*IMBotChatUpsert)) *IMBotChatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IMBotChatUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IMBotChatUpsertOne) SetUpdatedAt(v time.Time) *IMBotChatUpsertOne {
	return u.Update(func(s *IMBotChatUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IMBotChatUpsertOne) UpdateUpdatedAt() *IMBotChatUpsertOne {
	return u.Update(func(s *IMBotChatUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetBotID sets the "bot_id" field.
func (u *IMBotChatUpsertOne) SetBotID(v int64) *IMBotChatUpsertOne {
	return u.Update(func(s *IMBotChatUpsert) {
		s.SetBotID(v)
	})
}

// UpdateBotID sets the "bot_id" field to the value that was provided on create.
func (u *IMBotChatUpsertOne) UpdateBotID() *IMBotChatUpsertOne {
	return u.Update(func(s *IMBotChatUpsert) {
		s.UpdateBotID()
	})
}

// SetChatID sets the "chat_id" field.
func (u *IMBotChatUpsertOne) SetChatID(v string) *IMBotChatUpsertOne {
	return u.Update(func(s *IMBotChatUpsert) {
		s.SetChatID(v)
	})
}

// UpdateChatID sets the "chat_id" field to the value that was provided on create.
func (u *IMBotChatUpsertOne) UpdateChatID() *IMBotChatUpsertOne {
	return u.Update(func(s *IMBotChatUpsert) {
		s.UpdateChatID()
	})
}

// SetPlatformUserID sets the "platform_user_id" field.
func (u *IMBotChatUpsertOne) SetPlatformUserID(v string) *IMBotChatUpsertOne {
	return u.Update(func(s *IMBotChatUpsert) {
		s.SetPlatformUserID(v)
	})
}

// UpdatePlatformUserID sets the "platform_user_id" field to the value that was provided on create.
func (u *IMBotChatUpsertOne) UpdatePlatformUserID() *IMBotChatUpsertOne {
	return u.Update(func(s *IMBotChatUpsert) {
		s.UpdatePlatformUserID()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *IMBotChatUpsertOne) SetDisplayName(v string) *IMBotChatUpsertOne {
	return u.Update(func(s *IMBotChatUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *IMBotChatUpsertOne) UpdateDisplayName() *IMBotChatUpsertOne {
	return u.Update(func(s *IMBotChatUpsert) {
		s.UpdateDisplayName()
	})
}

// SetSessionUUID sets the "session_uuid" field.
func (u *IMBotChatUpsertOne) SetSessionUUID(v string) *IMBotChatUpsertOne {
	return u.Update(func(s *IMBotChatUpsert) {
		s.SetSessionUUID(v)
	})
}

// UpdateSessionUUID sets the "session_uuid" field to the value that was provided on create.
func (u *IMBotChatUpsertOne) UpdateSessionUUID() *IMBotChatUpsertOne {
	return u.Update(func(s *IMBotChatUpsert) {
		s.UpdateSessionUUID()
	})
}

// SetModelOverride sets the "model_override" field.
func (u *IMBotChatUpsertOne) SetModelOverride(v string) *IMBotChatUpsertOne {
	return u.Update(func(s *IMBotChatUpsert) {
		s.SetModelOverride(v)
	})
}

// UpdateModelOverride sets the "model_override" field to the value that was provided on create.
func (u *IMBotChatUpsertOne) UpdateModelOverride() *IMBotChatUpsertOne {
	return u.Update(func(s *IMBotChatUpsert) {
		s.UpdateModelOverride()
	})
}

// SetStatus sets the "status" field.
func (u *IMBotChatUpsertOne) SetStatus(v string) *IMBotChatUpsertOne {
	return u.Update(func(s *IMBotChatUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IMBotChatUpsertOne) UpdateStatus() *IMBotChatUpsertOne {
	return u.Update(func(s *IMBotChatUpsert) {
		s.UpdateStatus()
	})
}

// SetPairedAt sets the "paired_at" field.
func (u *IMBotChatUpsertOne) SetPairedAt(v time.Time) *IMBotChatUpsertOne {
	return u.Update(func(s *IMBotChatUpsert) {
		s.SetPairedAt(v)
	})
}

// UpdatePairedAt sets the "paired_at" field to the value that was provided on create.
func (u *IMBotChatUpsertOne) UpdatePairedAt() *IMBotChatUpsertOne {
	return u.Update(func(s *IMBotChatUpsert) {
		s.UpdatePairedAt()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *IMBotChatUpsertOne) SetLastMessageAt(v time.Time) *IMBotChatUpsertOne {
	return u.Update(func(s *IMBotChatUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *IMBotChatUpsertOne) UpdateLastMessageAt() *IMBotChatUpsertOne {
	return u.Update(func(s *IMBotChatUpsert) {
		s.UpdateLastMessageAt()
	})
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (u *IMBotChatUpsertOne) ClearLastMessageAt() *IMBotChatUpsertOne {
	return u.Update(func(s *IMBotChatUpsert) {
		s.ClearLastMessageAt()
	})
}

// Exec executes the query.
func (u *IMBotChatUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IMBotChatCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IMBotChatUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IMBotChatUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IMBotChatUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IMBotChatCreateBulk is the builder for creating many IMBotChat entities in bulk.
type IMBotChatCreateBulk struct {
	config
	err      error
	builders []*IMBotChatCreate
	conflict []sql.ConflictOption
}

// Save creates the IMBotChat entities in the database.
func (_c *IMBotChatCreateBulk) Save(ctx context.Context) ([]*IMBotChat, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IMBotChat, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IMBotChatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IMBotChatCreateBulk) SaveX(ctx context.Context) []*IMBotChat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IMBotChatCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IMBotChatCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IMBotChat.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IMBotChatUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IMBotChatCreateBulk) OnConflict(opts ...sql.ConflictOption) *IMBotChatUpsertBulk {
	_c.conflict = opts
	return &IMBotChatUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IMBotChat.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IMBotChatCreateBulk) OnConflictColumns(columns ...string) *IMBotChatUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IMBotChatUpsertBulk{
		create: _c,
	}
}

// IMBotChatUpsertBulk is the builder for "upsert"-ing
// a bulk of IMBotChat nodes.
type IMBotChatUpsertBulk struct {
	create *IMBotChatCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IMBotChat.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IMBotChatUpsertBulk) UpdateNewValues() *IMBotChatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(imbotchat.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IMBotChat.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IMBotChatUpsertBulk) Ignore() *IMBotChatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IMBotChatUpsertBulk) DoNothing() *IMBotChatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IMBotChatCreateBulk.OnConflict
// documentation for more info.
func (u *IMBotChatUpsertBulk) Update(set func(*IMBotChatUpsert)) *IMBotChatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IMBotChatUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IMBotChatUpsertBulk) SetUpdatedAt(v time.Time) *IMBotChatUpsertBulk {
	return u.Update(func(s *IMBotChatUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IMBotChatUpsertBulk) UpdateUpdatedAt() *IMBotChatUpsertBulk {
	return u.Update(func(s *IMBotChatUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetBotID sets the "bot_id" field.
func (u *IMBotChatUpsertBulk) SetBotID(v int64) *IMBotChatUpsertBulk {
	return u.Update(func(s *IMBotChatUpsert) {
		s.SetBotID(v)
	})
}

// UpdateBotID sets the "bot_id" field to the value that was provided on create.
func (u *IMBotChatUpsertBulk) UpdateBotID() *IMBotChatUpsertBulk {
	return u.Update(func(s *IMBotChatUpsert) {
		s.UpdateBotID()
	})
}

// SetChatID sets the "chat_id" field.
func (u *IMBotChatUpsertBulk) SetChatID(v string) *IMBotChatUpsertBulk {
	return u.Update(func(s *IMBotChatUpsert) {
		s.SetChatID(v)
	})
}

// UpdateChatID sets the "chat_id" field to the value that was provided on create.
func (u *IMBotChatUpsertBulk) UpdateChatID() *IMBotChatUpsertBulk {
	return u.Update(func(s *IMBotChatUpsert) {
		s.UpdateChatID()
	})
}

// SetPlatformUserID sets the "platform_user_id" field.
func (u *IMBotChatUpsertBulk) SetPlatformUserID(v string) *IMBotChatUpsertBulk {
	return u.Update(func(s *IMBotChatUpsert) {
		s.SetPlatformUserID(v)
	})
}

// UpdatePlatformUserID sets the "platform_user_id" field to the value that was provided on create.
func (u *IMBotChatUpsertBulk) UpdatePlatformUserID() *IMBotChatUpsertBulk {
	return u.Update(func(s *IMBotChatUpsert) {
		s.UpdatePlatformUserID()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *IMBotChatUpsertBulk) SetDisplayName(v string) *IMBotChatUpsertBulk {
	return u.Update(func(s *IMBotChatUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *IMBotChatUpsertBulk) UpdateDisplayName() *IMBotChatUpsertBulk {
	return u.Update(func(s *IMBotChatUpsert) {
		s.UpdateDisplayName()
	})
}

// SetSessionUUID sets the "session_uuid" field.
func (u *IMBotChatUpsertBulk) SetSessionUUID(v string) *IMBotChatUpsertBulk {
	return u.Update(func(s *IMBotChatUpsert) {
		s.SetSessionUUID(v)
	})
}

// UpdateSessionUUID sets the "session_uuid" field to the value that was provided on create.
func (u *IMBotChatUpsertBulk) UpdateSessionUUID() *IMBotChatUpsertBulk {
	return u.Update(func(s *IMBotChatUpsert) {
		s.UpdateSessionUUID()
	})
}

// SetModelOverride sets the "model_override" field.
func (u *IMBotChatUpsertBulk) SetModelOverride(v string) *IMBotChatUpsertBulk {
	return u.Update(func(s *IMBotChatUpsert) {
		s.SetModelOverride(v)
	})
}

// UpdateModelOverride sets the "model_override" field to the value that was provided on create.
func (u *IMBotChatUpsertBulk) UpdateModelOverride() *IMBotChatUpsertBulk {
	return u.Update(func(s *IMBotChatUpsert) {
		s.UpdateModelOverride()
	})
}

// SetStatus sets the "status" field.
func (u *IMBotChatUpsertBulk) SetStatus(v string) *IMBotChatUpsertBulk {
	return u.Update(func(s *IMBotChatUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IMBotChatUpsertBulk) UpdateStatus() *IMBotChatUpsertBulk {
	return u.Update(func(s *IMBotChatUpsert) {
		s.UpdateStatus()
	})
}

// SetPairedAt sets the "paired_at" field.
func (u *IMBotChatUpsertBulk) SetPairedAt(v time.Time) *IMBotChatUpsertBulk {
	return u.Update(func(s *IMBotChatUpsert) {
		s.SetPairedAt(v)
	})
}

// UpdatePairedAt sets the "paired_at" field to the value that was provided on create.
func (u *IMBotChatUpsertBulk) UpdatePairedAt() *IMBotChatUpsertBulk {
	return u.Update(func(s *IMBotChatUpsert) {
		s.UpdatePairedAt()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *IMBotChatUpsertBulk) SetLastMessageAt(v time.Time) *IMBotChatUpsertBulk {
	return u.Update(func(s *IMBotChatUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *IMBotChatUpsertBulk) UpdateLastMessageAt() *IMBotChatUpsertBulk {
	return u.Update(func(s *IMBotChatUpsert) {
		s.UpdateLastMessageAt()
	})
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (u *IMBotChatUpsertBulk) ClearLastMessageAt() *IMBotChatUpsertBulk {
	return u.Update(func(s *IMBotChatUpsert) {
		s.ClearLastMessageAt()
	})
}

// Exec executes the query.
func (u *IMBotChatUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IMBotChatCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IMBotChatCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IMBotChatUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
