// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imbot"
	"github.com/Wei-Shaw/sub2api/ent/imbotchat"
	"github.com/Wei-Shaw/sub2api/ent/imbotmessage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// IMBotChatUpdate is the builder for updating IMBotChat entities.
type IMBotChatUpdate struct {
	config
	hooks    []Hook
	mutation *IMBotChatMutation
}

// Where appends a list predicates to the IMBotChatUpdate builder.
func (_u *IMBotChatUpdate) Where(ps ...predicate.IMBotChat) *IMBotChatUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IMBotChatUpdate) SetUpdatedAt(v time.Time) *IMBotChatUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBotID sets the "bot_id" field.
func (_u *IMBotChatUpdate) SetBotID(v int64) *IMBotChatUpdate {
	_u.mutation.SetBotID(v)
	return _u
}

// SetNillableBotID sets the "bot_id" field if the given value is not nil.
func (_u *IMBotChatUpdate) SetNillableBotID(v *int64) *IMBotChatUpdate {
	if v != nil {
		_u.SetBotID(*v)
	}
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *IMBotChatUpdate) SetChatID(v string) *IMBotChatUpdate {
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *IMBotChatUpdate) SetNillableChatID(v *string) *IMBotChatUpdate {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// SetPlatformUserID sets the "platform_user_id" field.
func (_u *IMBotChatUpdate) SetPlatformUserID(v string) *IMBotChatUpdate {
	_u.mutation.SetPlatformUserID(v)
	return _u
}

// SetNillablePlatformUserID sets the "platform_user_id" field if the given value is not nil.
func (_u *IMBotChatUpdate) SetNillablePlatformUserID(v *string) *IMBotChatUpdate {
	if v != nil {
		_u.SetPlatformUserID(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *IMBotChatUpdate) SetDisplayName(v string) *IMBotChatUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *IMBotChatUpdate) SetNillableDisplayName(v *string) *IMBotChatUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetSessionUUID sets the "session_uuid" field.
func (_u *IMBotChatUpdate) SetSessionUUID(v string) *IMBotChatUpdate {
	_u.mutation.SetSessionUUID(v)
	return _u
}

// SetNillableSessionUUID sets the "session_uuid" field if the given value is not nil.
func (_u *IMBotChatUpdate) SetNillableSessionUUID(v *string) *IMBotChatUpdate {
	if v != nil {
		_u.SetSessionUUID(*v)
	}
	return _u
}

// SetModelOverride sets the "model_override" field.
func (_u *IMBotChatUpdate) SetModelOverride(v string) *IMBotChatUpdate {
	_u.mutation.SetModelOverride(v)
	return _u
}

// SetNillableModelOverride sets the "model_override" field if the given value is not nil.
func (_u *IMBotChatUpdate) SetNillableModelOverride(v *string) *IMBotChatUpdate {
	if v != nil {
		_u.SetModelOverride(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *IMBotChatUpdate) SetStatus(v string) *IMBotChatUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IMBotChatUpdate) SetNillableStatus(v *string) *IMBotChatUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPairedAt sets the "paired_at" field.
func (_u *IMBotChatUpdate) SetPairedAt(v time.Time) *IMBotChatUpdate {
	_u.mutation.SetPairedAt(v)
	return _u
}

// SetNillablePairedAt sets the "paired_at" field if the given value is not nil.
func (_u *IMBotChatUpdate) SetNillablePairedAt(v *time.Time) *IMBotChatUpdate {
	if v != nil {
		_u.SetPairedAt(*v)
	}
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *IMBotChatUpdate) SetLastMessageAt(v time.Time) *IMBotChatUpdate {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *IMBotChatUpdate) SetNillableLastMessageAt(v *time.Time) *IMBotChatUpdate {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (_u *IMBotChatUpdate) ClearLastMessageAt() *IMBotChatUpdate {
	_u.mutation.ClearLastMessageAt()
	return _u
}

// SetBot sets the "bot" edge to the IMBot entity.
func (_u *IMBotChatUpdate) SetBot(v *IMBot) *IMBotChatUpdate {
	return _u.SetBotID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the IMBotMessage entity by IDs.
func (_u *IMBotChatUpdate) AddMessageIDs(ids ...int64) *IMBotChatUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the IMBotMessage entity.
func (_u *IMBotChatUpdate) AddMessages(v ...*IMBotMessage) *IMBotChatUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the IMBotChatMutation object of the builder.
func (_u *IMBotChatUpdate) Mutation() *IMBotChatMutation {
	return _u.mutation
}

// ClearBot clears the "bot" edge to the IMBot entity.
func (_u *IMBotChatUpdate) ClearBot() *IMBotChatUpdate {
	_u.mutation.ClearBot()
	return _u
}

// ClearMessages clears all "messages" edges to the IMBotMessage entity.
func (_u *IMBotChatUpdate) ClearMessages() *IMBotChatUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to IMBotMessage entities by IDs.
func (_u *IMBotChatUpdate) RemoveMessageIDs(ids ...int64) *IMBotChatUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to IMBotMessage entities.
func (_u *IMBotChatUpdate) RemoveMessages(v ...*IMBotMessage) *IMBotChatUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IMBotChatUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IMBotChatUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IMBotChatUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IMBotChatUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IMBotChatUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := imbotchat.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IMBotChatUpdate) check() error {
	if v, ok := _u.mutation.ChatID(); ok {
		if err := imbotchat.ChatIDValidator(v); err != nil {
			return &ValidationError{Name: "chat_id", err: fmt.Errorf(`ent: validator failed for field "IMBotChat.chat_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlatformUserID(); ok {
		if err := imbotchat.PlatformUserIDValidator(v); err != nil {
			return &ValidationError{Name: "platform_user_id", err: fmt.Errorf(`ent: validator failed for field "IMBotChat.platform_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := imbotchat.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "IMBotChat.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionUUID(); ok {
		if err := imbotchat.SessionUUIDValidator(v); err != nil {
			return &ValidationError{Name: "session_uuid", err: fmt.Errorf(`ent: validator failed for field "IMBotChat.session_uuid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelOverride(); ok {
		if err := imbotchat.ModelOverrideValidator(v); err != nil {
			return &ValidationError{Name: "model_override", err: fmt.Errorf(`ent: validator failed for field "IMBotChat.model_override": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := imbotchat.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IMBotChat.status": %w`, err)}
		}
	}
	if _u.mutation.BotCleared() && len(_u.mutation.BotIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "IMBotChat.bot"`)
	}
	return nil
}

func (_u *IMBotChatUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imbotchat.Table, imbotchat.Columns, sqlgraph.NewFieldSpec(imbotchat.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imbotchat.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(imbotchat.FieldChatID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformUserID(); ok {
		_spec.SetField(imbotchat.FieldPlatformUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(imbotchat.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionUUID(); ok {
		_spec.SetField(imbotchat.FieldSessionUUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelOverride(); ok {
		_spec.SetField(imbotchat.FieldModelOverride, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(imbotchat.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PairedAt(); ok {
		_spec.SetField(imbotchat.FieldPairedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(imbotchat.FieldLastMessageAt, field.TypeTime, value)
	}
	if _u.mutation.LastMessageAtCleared() {
		_spec.ClearField(imbotchat.FieldLastMessageAt, field.TypeTime)
	}
	if _u.mutation.BotCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imbotchat.BotTable,
			Columns: []string{imbotchat.BotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imbot.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imbotchat.BotTable,
			Columns: []string{imbotchat.BotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imbot.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imbotchat.MessagesTable,
			Columns: []string{imbotchat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imbotmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imbotchat.MessagesTable,
			Columns: []string{imbotchat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imbotmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imbotchat.MessagesTable,
			Columns: []string{imbotchat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imbotmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imbotchat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IMBotChatUpdateOne is the builder for updating a single IMBotChat entity.
type IMBotChatUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IMBotChatMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IMBotChatUpdateOne) SetUpdatedAt(v time.Time) *IMBotChatUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBotID sets the "bot_id" field.
func (_u *IMBotChatUpdateOne) SetBotID(v int64) *IMBotChatUpdateOne {
	_u.mutation.SetBotID(v)
	return _u
}

// SetNillableBotID sets the "bot_id" field if the given value is not nil.
func (_u *IMBotChatUpdateOne) SetNillableBotID(v *int64) *IMBotChatUpdateOne {
	if v != nil {
		_u.SetBotID(*v)
	}
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *IMBotChatUpdateOne) SetChatID(v string) *IMBotChatUpdateOne {
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *IMBotChatUpdateOne) SetNillableChatID(v *string) *IMBotChatUpdateOne {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// SetPlatformUserID sets the "platform_user_id" field.
func (_u *IMBotChatUpdateOne) SetPlatformUserID(v string) *IMBotChatUpdateOne {
	_u.mutation.SetPlatformUserID(v)
	return _u
}

// SetNillablePlatformUserID sets the "platform_user_id" field if the given value is not nil.
func (_u *IMBotChatUpdateOne) SetNillablePlatformUserID(v *string) *IMBotChatUpdateOne {
	if v != nil {
		_u.SetPlatformUserID(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *IMBotChatUpdateOne) SetDisplayName(v string) *IMBotChatUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *IMBotChatUpdateOne) SetNillableDisplayName(v *string) *IMBotChatUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetSessionUUID sets the "session_uuid" field.
func (_u *IMBotChatUpdateOne) SetSessionUUID(v string) *IMBotChatUpdateOne {
	_u.mutation.SetSessionUUID(v)
	return _u
}

// SetNillableSessionUUID sets the "session_uuid" field if the given value is not nil.
func (_u *IMBotChatUpdateOne) SetNillableSessionUUID(v *string) *IMBotChatUpdateOne {
	if v != nil {
		_u.SetSessionUUID(*v)
	}
	return _u
}

// SetModelOverride sets the "model_override" field.
func (_u *IMBotChatUpdateOne) SetModelOverride(v string) *IMBotChatUpdateOne {
	_u.mutation.SetModelOverride(v)
	return _u
}

// SetNillableModelOverride sets the "model_override" field if the given value is not nil.
func (_u *IMBotChatUpdateOne) SetNillableModelOverride(v *string) *IMBotChatUpdateOne {
	if v != nil {
		_u.SetModelOverride(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *IMBotChatUpdateOne) SetStatus(v string) *IMBotChatUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IMBotChatUpdateOne) SetNillableStatus(v *string) *IMBotChatUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPairedAt sets the "paired_at" field.
func (_u *IMBotChatUpdateOne) SetPairedAt(v time.Time) *IMBotChatUpdateOne {
	_u.mutation.SetPairedAt(v)
	return _u
}

// SetNillablePairedAt sets the "paired_at" field if the given value is not nil.
func (_u *IMBotChatUpdateOne) SetNillablePairedAt(v *time.Time) *IMBotChatUpdateOne {
	if v != nil {
		_u.SetPairedAt(*v)
	}
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *IMBotChatUpdateOne) SetLastMessageAt(v time.Time) *IMBotChatUpdateOne {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *IMBotChatUpdateOne) SetNillableLastMessageAt(v *time.Time) *IMBotChatUpdateOne {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (_u *IMBotChatUpdateOne) ClearLastMessageAt() *IMBotChatUpdateOne {
	_u.mutation.ClearLastMessageAt()
	return _u
}

// SetBot sets the "bot" edge to the IMBot entity.
func (_u *IMBotChatUpdateOne) SetBot(v *IMBot) *IMBotChatUpdateOne {
	return _u.SetBotID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the IMBotMessage entity by IDs.
func (_u *IMBotChatUpdateOne) AddMessageIDs(ids ...int64) *IMBotChatUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the IMBotMessage entity.
func (_u *IMBotChatUpdateOne) AddMessages(v ...*IMBotMessage) *IMBotChatUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the IMBotChatMutation object of the builder.
func (_u *IMBotChatUpdateOne) Mutation() *IMBotChatMutation {
	return _u.mutation
}

// ClearBot clears the "bot" edge to the IMBot entity.
func (_u *IMBotChatUpdateOne) ClearBot() *IMBotChatUpdateOne {
	_u.mutation.ClearBot()
	return _u
}

// ClearMessages clears all "messages" edges to the IMBotMessage entity.
func (_u *IMBotChatUpdateOne) ClearMessages() *IMBotChatUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to IMBotMessage entities by IDs.
func (_u *IMBotChatUpdateOne) RemoveMessageIDs(ids ...int64) *IMBotChatUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to IMBotMessage entities.
func (_u *IMBotChatUpdateOne) RemoveMessages(v ...*IMBotMessage) *IMBotChatUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the IMBotChatUpdate builder.
func (_u *IMBotChatUpdateOne) Where(ps ...predicate.IMBotChat) *IMBotChatUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IMBotChatUpdateOne) Select(field string, fields ...string) *IMBotChatUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IMBotChat entity.
func (_u *IMBotChatUpdateOne) Save(ctx context.Context) (*IMBotChat, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IMBotChatUpdateOne) SaveX(ctx context.Context) *IMBotChat {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IMBotChatUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IMBotChatUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IMBotChatUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := imbotchat.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IMBotChatUpdateOne) check() error {
	if v, ok := _u.mutation.ChatID(); ok {
		if err := imbotchat.ChatIDValidator(v); err != nil {
			return &ValidationError{Name: "chat_id", err: fmt.Errorf(`ent: validator failed for field "IMBotChat.chat_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlatformUserID(); ok {
		if err := imbotchat.PlatformUserIDValidator(v); err != nil {
			return &ValidationError{Name: "platform_user_id", err: fmt.Errorf(`ent: validator failed for field "IMBotChat.platform_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := imbotchat.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "IMBotChat.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionUUID(); ok {
		if err := imbotchat.SessionUUIDValidator(v); err != nil {
			return &ValidationError{Name: "session_uuid", err: fmt.Errorf(`ent: validator failed for field "IMBotChat.session_uuid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelOverride(); ok {
		if err := imbotchat.ModelOverrideValidator(v); err != nil {
			return &ValidationError{Name: "model_override", err: fmt.Errorf(`ent: validator failed for field "IMBotChat.model_override": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := imbotchat.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IMBotChat.status": %w`, err)}
		}
	}
	if _u.mutation.BotCleared() && len(_u.mutation.BotIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "IMBotChat.bot"`)
	}
	return nil
}

func (_u *IMBotChatUpdateOne) sqlSave(ctx context.Context) (_node *IMBotChat, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imbotchat.Table, imbotchat.Columns, sqlgraph.NewFieldSpec(imbotchat.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IMBotChat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, imbotchat.FieldID)
		for _, f := range fields {
			if !imbotchat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != imbotchat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imbotchat.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(imbotchat.FieldChatID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformUserID(); ok {
		_spec.SetField(imbotchat.FieldPlatformUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(imbotchat.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionUUID(); ok {
		_spec.SetField(imbotchat.FieldSessionUUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelOverride(); ok {
		_spec.SetField(imbotchat.FieldModelOverride, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(imbotchat.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PairedAt(); ok {
		_spec.SetField(imbotchat.FieldPairedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(imbotchat.FieldLastMessageAt, field.TypeTime, value)
	}
	if _u.mutation.LastMessageAtCleared() {
		_spec.ClearField(imbotchat.FieldLastMessageAt, field.TypeTime)
	}
	if _u.mutation.BotCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imbotchat.BotTable,
			Columns: []string{imbotchat.BotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imbot.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imbotchat.BotTable,
			Columns: []string{imbotchat.BotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imbot.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imbotchat.MessagesTable,
			Columns: []string{imbotchat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imbotmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imbotchat.MessagesTable,
			Columns: []string{imbotchat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imbotmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imbotchat.MessagesTable,
			Columns: []string{imbotchat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imbotmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &IMBotChat{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imbotchat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
