// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imbotchat"
	"github.com/Wei-Shaw/sub2api/ent/imbotmessage"
)

// IMBotMessageCreate is the builder for creating a IMBotMessage entity.
type IMBotMessageCreate struct {
	config
	mutation *IMBotMessageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *IMBotMessageCreate) SetCreatedAt(v time.Time) *IMBotMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IMBotMessageCreate) SetNillableCreatedAt(v *time.Time) *IMBotMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IMBotMessageCreate) SetUpdatedAt(v time.Time) *IMBotMessageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IMBotMessageCreate) SetNillableUpdatedAt(v *time.Time) *IMBotMessageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetChatID sets the "chat_id" field.
func (_c *IMBotMessageCreate) SetChatID(v int64) *IMBotMessageCreate {
	_c.mutation.SetChatID(v)
	return _c
}

// SetBotID sets the "bot_id" field.
func (_c *IMBotMessageCreate) SetBotID(v int64) *IMBotMessageCreate {
	_c.mutation.SetBotID(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *IMBotMessageCreate) SetRole(v string) *IMBotMessageCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *IMBotMessageCreate) SetContent(v string) *IMBotMessageCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *IMBotMessageCreate) SetRequestID(v string) *IMBotMessageCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *IMBotMessageCreate) SetNillableRequestID(v *string) *IMBotMessageCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetChat sets the "chat" edge to the IMBotChat entity.
func (_c *IMBotMessageCreate) SetChat(v *IMBotChat) *IMBotMessageCreate {
	return _c.SetChatID(v.ID)
}

// Mutation returns the IMBotMessageMutation object of the builder.
func (_c *IMBotMessageCreate) Mutation() *IMBotMessageMutation {
	return _c.mutation
}

// Save creates the IMBotMessage in the database.
func (_c *IMBotMessageCreate) Save(ctx context.Context) (*IMBotMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IMBotMessageCreate) SaveX(ctx context.Context) *IMBotMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IMBotMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IMBotMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IMBotMessageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := imbotmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := imbotmessage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		v := imbotmessage.DefaultRequestID
		_c.mutation.SetRequestID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IMBotMessageCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "IMBotMessage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "IMBotMessage.updated_at"`)}
	}
	if _, ok := _c.mutation.ChatID(); !ok {
		return &ValidationError{Name: "chat_id", err: errors.New(`ent: missing required field "IMBotMessage.chat_id"`)}
	}
	if _, ok := _c.mutation.BotID(); !ok {
		return &ValidationError{Name: "bot_id", err: errors.New(`ent: missing required field "IMBotMessage.bot_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "IMBotMessage.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := imbotmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "IMBotMessage.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "IMBotMessage.content"`)}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "IMBotMessage.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := imbotmessage.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "IMBotMessage.request_id": %w`, err)}
		}
	}
	if len(_c.mutation.ChatIDs()) == 0 {
		return &ValidationError{Name: "chat", err: errors.New(`ent: missing required edge "IMBotMessage.chat"`)}
	}
	return nil
}

func (_c *IMBotMessageCreate) sqlSave(ctx context.Context) (*IMBotMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IMBotMessageCreate) createSpec() (*IMBotMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &IMBotMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(imbotmessage.Table, sqlgraph.NewFieldSpec(imbotmessage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(imbotmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(imbotmessage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.BotID(); ok {
		_spec.SetField(imbotmessage.FieldBotID, field.TypeInt64, value)
		_node.BotID = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(imbotmessage.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(imbotmessage.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(imbotmessage.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if nodes := _c.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imbotmessage.ChatTable,
			Columns: []string{imbotmessage.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imbotchat.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChatID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IMBotMessage.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IMBotMessageUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IMBotMessageCreate) OnConflict(opts ...sql.ConflictOption) *IMBotMessageUpsertOne {
	_c.conflict = opts
	return &IMBotMessageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IMBotMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IMBotMessageCreate) OnConflictColumns(columns ...string) *IMBotMessageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IMBotMessageUpsertOne{
		create: _c,
	}
}

type (
	// IMBotMessageUpsertOne is the builder for "upsert"-ing
	//  one IMBotMessage node.
	IMBotMessageUpsertOne struct {
		create *IMBotMessageCreate
	}

	// IMBotMessageUpsert is the "OnConflict" setter.
	IMBotMessageUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *IMBotMessageUpsert) SetUpdatedAt(v time.Time) *IMBotMessageUpsert {
	u.Set(imbotmessage.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IMBotMessageUpsert) UpdateUpdatedAt() *IMBotMessageUpsert {
	u.SetExcluded(imbotmessage.FieldUpdatedAt)
	return u
}

// SetChatID sets the "chat_id" field.
func (u *IMBotMessageUpsert) SetChatID(v int64) *IMBotMessageUpsert {
	u.Set(imbotmessage.FieldChatID, v)
	return u
}

// UpdateChatID sets the "chat_id" field to the value that was provided on create.
func (u *IMBotMessageUpsert) UpdateChatID() *IMBotMessageUpsert {
	u.SetExcluded(imbotmessage.FieldChatID)
	return u
}

// SetBotID sets the "bot_id" field.
func (u *IMBotMessageUpsert) SetBotID(v int64) *IMBotMessageUpsert {
	u.Set(imbotmessage.FieldBotID, v)
	return u
}

// UpdateBotID sets the "bot_id" field to the value that was provided on create.
func (u *IMBotMessageUpsert) UpdateBotID() *IMBotMessageUpsert {
	u.SetExcluded(imbotmessage.FieldBotID)
	return u
}

// AddBotID adds v to the "bot_id" field.
func (u *IMBotMessageUpsert) AddBotID(v int64) *IMBotMessageUpsert {
	u.Add(imbotmessage.FieldBotID, v)
	return u
}

// SetRole sets the "role" field.
func (u *IMBotMessageUpsert) SetRole(v string) *IMBotMessageUpsert {
	u.Set(imbotmessage.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *IMBotMessageUpsert) UpdateRole() *IMBotMessageUpsert {
	u.SetExcluded(imbotmessage.FieldRole)
	return u
}

// SetContent sets the "content" field.
func (u *IMBotMessageUpsert) SetContent(v string) *IMBotMessageUpsert {
	u.Set(imbotmessage.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *IMBotMessageUpsert) UpdateContent() *IMBotMessageUpsert {
	u.SetExcluded(imbotmessage.FieldContent)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *IMBotMessageUpsert) SetRequestID(v string) *IMBotMessageUpsert {
	u.Set(imbotmessage.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *IMBotMessageUpsert) UpdateRequestID() *IMBotMessageUpsert {
	u.SetExcluded(imbotmessage.FieldRequestID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.IMBotMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IMBotMessageUpsertOne) UpdateNewValues() *IMBotMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(imbotmessage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IMBotMessage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IMBotMessageUpsertOne) Ignore() *IMBotMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IMBotMessageUpsertOne) DoNothing() *IMBotMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IMBotMessageCreate.OnConflict
// documentation for more info.
func (u *IMBotMessageUpsertOne) Update(set func(*IMBotMessageUpsert)) *IMBotMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IMBotMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IMBotMessageUpsertOne) SetUpdatedAt(v time.Time) *IMBotMessageUpsertOne {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IMBotMessageUpsertOne) UpdateUpdatedAt() *IMBotMessageUpsertOne {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetChatID sets the "chat_id" field.
func (u *IMBotMessageUpsertOne) SetChatID(v int64) *IMBotMessageUpsertOne {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.SetChatID(v)
	})
}

// UpdateChatID sets the "chat_id" field to the value that was provided on create.
func (u *IMBotMessageUpsertOne) UpdateChatID() *IMBotMessageUpsertOne {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.UpdateChatID()
	})
}

// SetBotID sets the "bot_id" field.
func (u *IMBotMessageUpsertOne) SetBotID(v int64) *IMBotMessageUpsertOne {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.SetBotID(v)
	})
}

// AddBotID adds v to the "bot_id" field.
func (u *IMBotMessageUpsertOne) AddBotID(v int64) *IMBotMessageUpsertOne {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.AddBotID(v)
	})
}

// UpdateBotID sets the "bot_id" field to the value that was provided on create.
func (u *IMBotMessageUpsertOne) UpdateBotID() *IMBotMessageUpsertOne {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.UpdateBotID()
	})
}

// SetRole sets the "role" field.
func (u *IMBotMessageUpsertOne) SetRole(v string) *IMBotMessageUpsertOne {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *IMBotMessageUpsertOne) UpdateRole() *IMBotMessageUpsertOne {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.UpdateRole()
	})
}

// SetContent sets the "content" field.
func (u *IMBotMessageUpsertOne) SetContent(v string) *IMBotMessageUpsertOne {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *IMBotMessageUpsertOne) UpdateContent() *IMBotMessageUpsertOne {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.UpdateContent()
	})
}

// SetRequestID sets the "request_id" field.
func (u *IMBotMessageUpsertOne) SetRequestID(v string) *IMBotMessageUpsertOne {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *IMBotMessageUpsertOne) UpdateRequestID() *IMBotMessageUpsertOne {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.UpdateRequestID()
	})
}

// Exec executes the query.
func (u *IMBotMessageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IMBotMessageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IMBotMessageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IMBotMessageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IMBotMessageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IMBotMessageCreateBulk is the builder for creating many IMBotMessage entities in bulk.
type IMBotMessageCreateBulk struct {
	config
	err      error
	builders []*IMBotMessageCreate
	conflict []sql.ConflictOption
}

// Save creates the IMBotMessage entities in the database.
func (_c *IMBotMessageCreateBulk) Save(ctx context.Context) ([]*IMBotMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IMBotMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IMBotMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IMBotMessageCreateBulk) SaveX(ctx context.Context) []*IMBotMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IMBotMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IMBotMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IMBotMessage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IMBotMessageUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IMBotMessageCreateBulk) OnConflict(opts ...sql.ConflictOption) *IMBotMessageUpsertBulk {
	_c.conflict = opts
	return &IMBotMessageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IMBotMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IMBotMessageCreateBulk) OnConflictColumns(columns ...string) *IMBotMessageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IMBotMessageUpsertBulk{
		create: _c,
	}
}

// IMBotMessageUpsertBulk is the builder for "upsert"-ing
// a bulk of IMBotMessage nodes.
type IMBotMessageUpsertBulk struct {
	create *IMBotMessageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IMBotMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IMBotMessageUpsertBulk) UpdateNewValues() *IMBotMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(imbotmessage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IMBotMessage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IMBotMessageUpsertBulk) Ignore() *IMBotMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IMBotMessageUpsertBulk) DoNothing() *IMBotMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IMBotMessageCreateBulk.OnConflict
// documentation for more info.
func (u *IMBotMessageUpsertBulk) Update(set func(*IMBotMessageUpsert)) *IMBotMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IMBotMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IMBotMessageUpsertBulk) SetUpdatedAt(v time.Time) *IMBotMessageUpsertBulk {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IMBotMessageUpsertBulk) UpdateUpdatedAt() *IMBotMessageUpsertBulk {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetChatID sets the "chat_id" field.
func (u *IMBotMessageUpsertBulk) SetChatID(v int64) *IMBotMessageUpsertBulk {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.SetChatID(v)
	})
}

// UpdateChatID sets the "chat_id" field to the value that was provided on create.
func (u *IMBotMessageUpsertBulk) UpdateChatID() *IMBotMessageUpsertBulk {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.UpdateChatID()
	})
}

// SetBotID sets the "bot_id" field.
func (u *IMBotMessageUpsertBulk) SetBotID(v int64) *IMBotMessageUpsertBulk {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.SetBotID(v)
	})
}

// AddBotID adds v to the "bot_id" field.
func (u *IMBotMessageUpsertBulk) AddBotID(v int64) *IMBotMessageUpsertBulk {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.AddBotID(v)
	})
}

// UpdateBotID sets the "bot_id" field to the value that was provided on create.
func (u *IMBotMessageUpsertBulk) UpdateBotID() *IMBotMessageUpsertBulk {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.UpdateBotID()
	})
}

// SetRole sets the "role" field.
func (u *IMBotMessageUpsertBulk) SetRole(v string) *IMBotMessageUpsertBulk {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *IMBotMessageUpsertBulk) UpdateRole() *IMBotMessageUpsertBulk {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.UpdateRole()
	})
}

// SetContent sets the "content" field.
func (u *IMBotMessageUpsertBulk) SetContent(v string) *IMBotMessageUpsertBulk {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *IMBotMessageUpsertBulk) UpdateContent() *IMBotMessageUpsertBulk {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.UpdateContent()
	})
}

// SetRequestID sets the "request_id" field.
func (u *IMBotMessageUpsertBulk) SetRequestID(v string) *IMBotMessageUpsertBulk {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *IMBotMessageUpsertBulk) UpdateRequestID() *IMBotMessageUpsertBulk {
	return u.Update(func(s *IMBotMessageUpsert) {
		s.UpdateRequestID()
	})
}

// Exec executes the query.
func (u *IMBotMessageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IMBotMessageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IMBotMessageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IMBotMessageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
