// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/imbotchat"
	"github.com/Wei-Shaw/sub2api/ent/imbotmessage"
)

// IMBotMessage is the model entity for the IMBotMessage schema.
type IMBotMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ChatID holds the value of the "chat_id" field.
	ChatID int64 `json:"chat_id,omitempty"`
	// BotID holds the value of the "bot_id" field.
	BotID int64 `json:"bot_id,omitempty"`
	// user | assistant
	Role string `json:"role,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the IMBotMessageQuery when eager-loading is set.
	Edges        IMBotMessageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// IMBotMessageEdges holds the relations/edges for other nodes in the graph.
type IMBotMessageEdges struct {
	// Chat holds the value of the chat edge.
	Chat *IMBotChat `json:"chat,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ChatOrErr returns the Chat value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IMBotMessageEdges) ChatOrErr() (*IMBotChat, error) {
	if e.Chat != nil {
		return e.Chat, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: imbotchat.Label}
	}
	return nil, &NotLoadedError{edge: "chat"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IMBotMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case imbotmessage.FieldID, imbotmessage.FieldChatID, imbotmessage.FieldBotID:
			values[i] = new(sql.NullInt64)
		case imbotmessage.FieldRole, imbotmessage.FieldContent, imbotmessage.FieldRequestID:
			values[i] = new(sql.NullString)
		case imbotmessage.FieldCreatedAt, imbotmessage.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IMBotMessage fields.
func (_m *IMBotMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case imbotmessage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case imbotmessage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case imbotmessage.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case imbotmessage.FieldChatID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chat_id", values[i])
			} else if value.Valid {
				_m.ChatID = value.Int64
			}
		case imbotmessage.FieldBotID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bot_id", values[i])
			} else if value.Valid {
				_m.BotID = value.Int64
			}
		case imbotmessage.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case imbotmessage.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case imbotmessage.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IMBotMessage.
// This includes values selected through modifiers, order, etc.
func (_m *IMBotMessage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChat queries the "chat" edge of the IMBotMessage entity.
func (_m *IMBotMessage) QueryChat() *IMBotChatQuery {
	return NewIMBotMessageClient(_m.config).QueryChat(_m)
}

// Update returns a builder for updating this IMBotMessage.
// Note that you need to call IMBotMessage.Unwrap() before calling this method if this IMBotMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IMBotMessage) Update() *IMBotMessageUpdateOne {
	return NewIMBotMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IMBotMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IMBotMessage) Unwrap() *IMBotMessage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IMBotMessage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IMBotMessage) String() string {
	var builder strings.Builder
	builder.WriteString("IMBotMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("chat_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChatID))
	builder.WriteString(", ")
	builder.WriteString("bot_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BotID))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteByte(')')
	return builder.String()
}

// IMBotMessages is a parsable slice of IMBotMessage.
type IMBotMessages []*IMBotMessage
