// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/imbot"
	"github.com/Wei-Shaw/sub2api/ent/imbotchat"
)

// IMBotCreate is the builder for creating a IMBot entity.
type IMBotCreate struct {
	config
	mutation *IMBotMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *IMBotCreate) SetCreatedAt(v time.Time) *IMBotCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IMBotCreate) SetNillableCreatedAt(v *time.Time) *IMBotCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IMBotCreate) SetUpdatedAt(v time.Time) *IMBotCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IMBotCreate) SetNillableUpdatedAt(v *time.Time) *IMBotCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *IMBotCreate) SetDeletedAt(v time.Time) *IMBotCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *IMBotCreate) SetNillableDeletedAt(v *time.Time) *IMBotCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *IMBotCreate) SetName(v string) *IMBotCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *IMBotCreate) SetPlatform(v string) *IMBotCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetCredentialsEncrypted sets the "credentials_encrypted" field.
func (_c *IMBotCreate) SetCredentialsEncrypted(v string) *IMBotCreate {
	_c.mutation.SetCredentialsEncrypted(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *IMBotCreate) SetAPIKeyID(v int64) *IMBotCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetModelOverride sets the "model_override" field.
func (_c *IMBotCreate) SetModelOverride(v string) *IMBotCreate {
	_c.mutation.SetModelOverride(v)
	return _c
}

// SetNillableModelOverride sets the "model_override" field if the given value is not nil.
func (_c *IMBotCreate) SetNillableModelOverride(v *string) *IMBotCreate {
	if v != nil {
		_c.SetModelOverride(*v)
	}
	return _c
}

// SetSystemPrompt sets the "system_prompt" field.
func (_c *IMBotCreate) SetSystemPrompt(v string) *IMBotCreate {
	_c.mutation.SetSystemPrompt(v)
	return _c
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_c *IMBotCreate) SetNillableSystemPrompt(v *string) *IMBotCreate {
	if v != nil {
		_c.SetSystemPrompt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *IMBotCreate) SetStatus(v string) *IMBotCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *IMBotCreate) SetNillableStatus(v *string) *IMBotCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (_c *IMBotCreate) SetMaxConcurrency(v int) *IMBotCreate {
	_c.mutation.SetMaxConcurrency(v)
	return _c
}

// SetNillableMaxConcurrency sets the "max_concurrency" field if the given value is not nil.
func (_c *IMBotCreate) SetNillableMaxConcurrency(v *int) *IMBotCreate {
	if v != nil {
		_c.SetMaxConcurrency(*v)
	}
	return _c
}

// SetHistoryMaxMessages sets the "history_max_messages" field.
func (_c *IMBotCreate) SetHistoryMaxMessages(v int) *IMBotCreate {
	_c.mutation.SetHistoryMaxMessages(v)
	return _c
}

// SetNillableHistoryMaxMessages sets the "history_max_messages" field if the given value is not nil.
func (_c *IMBotCreate) SetNillableHistoryMaxMessages(v *int) *IMBotCreate {
	if v != nil {
		_c.SetHistoryMaxMessages(*v)
	}
	return _c
}

// SetPairingEnabled sets the "pairing_enabled" field.
func (_c *IMBotCreate) SetPairingEnabled(v bool) *IMBotCreate {
	_c.mutation.SetPairingEnabled(v)
	return _c
}

// SetNillablePairingEnabled sets the "pairing_enabled" field if the given value is not nil.
func (_c *IMBotCreate) SetNillablePairingEnabled(v *bool) *IMBotCreate {
	if v != nil {
		_c.SetPairingEnabled(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *IMBotCreate) SetLastError(v string) *IMBotCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *IMBotCreate) SetNillableLastError(v *string) *IMBotCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *IMBotCreate) SetAPIKey(v *APIKey) *IMBotCreate {
	return _c.SetAPIKeyID(v.ID)
}

// AddChatIDs adds the "chats" edge to the IMBotChat entity by IDs.
func (_c *IMBotCreate) AddChatIDs(ids ...int64) *IMBotCreate {
	_c.mutation.AddChatIDs(ids...)
	return _c
}

// AddChats adds the "chats" edges to the IMBotChat entity.
func (_c *IMBotCreate) AddChats(v ...*IMBotChat) *IMBotCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChatIDs(ids...)
}

// Mutation returns the IMBotMutation object of the builder.
func (_c *IMBotCreate) Mutation() *IMBotMutation {
	return _c.mutation
}

// Save creates the IMBot in the database.
func (_c *IMBotCreate) Save(ctx context.Context) (*IMBot, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IMBotCreate) SaveX(ctx context.Context) *IMBot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IMBotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IMBotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IMBotCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if imbot.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized imbot.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := imbot.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if imbot.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized imbot.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := imbot.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ModelOverride(); !ok {
		v := imbot.DefaultModelOverride
		_c.mutation.SetModelOverride(v)
	}
	if _, ok := _c.mutation.SystemPrompt(); !ok {
		v := imbot.DefaultSystemPrompt
		_c.mutation.SetSystemPrompt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := imbot.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.MaxConcurrency(); !ok {
		v := imbot.DefaultMaxConcurrency
		_c.mutation.SetMaxConcurrency(v)
	}
	if _, ok := _c.mutation.HistoryMaxMessages(); !ok {
		v := imbot.DefaultHistoryMaxMessages
		_c.mutation.SetHistoryMaxMessages(v)
	}
	if _, ok := _c.mutation.PairingEnabled(); !ok {
		v := imbot.DefaultPairingEnabled
		_c.mutation.SetPairingEnabled(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := imbot.DefaultLastError
		_c.mutation.SetLastError(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *IMBotCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "IMBot.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "IMBot.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "IMBot.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := imbot.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "IMBot.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "IMBot.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := imbot.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "IMBot.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CredentialsEncrypted(); !ok {
		return &ValidationError{Name: "credentials_encrypted", err: errors.New(`ent: missing required field "IMBot.credentials_encrypted"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "IMBot.api_key_id"`)}
	}
	if _, ok := _c.mutation.ModelOverride(); !ok {
		return &ValidationError{Name: "model_override", err: errors.New(`ent: missing required field "IMBot.model_override"`)}
	}
	if v, ok := _c.mutation.ModelOverride(); ok {
		if err := imbot.ModelOverrideValidator(v); err != nil {
			return &ValidationError{Name: "model_override", err: fmt.Errorf(`ent: validator failed for field "IMBot.model_override": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SystemPrompt(); !ok {
		return &ValidationError{Name: "system_prompt", err: errors.New(`ent: missing required field "IMBot.system_prompt"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "IMBot.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := imbot.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IMBot.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MaxConcurrency(); !ok {
		return &ValidationError{Name: "max_concurrency", err: errors.New(`ent: missing required field "IMBot.max_concurrency"`)}
	}
	if _, ok := _c.mutation.HistoryMaxMessages(); !ok {
		return &ValidationError{Name: "history_max_messages", err: errors.New(`ent: missing required field "IMBot.history_max_messages"`)}
	}
	if _, ok := _c.mutation.PairingEnabled(); !ok {
		return &ValidationError{Name: "pairing_enabled", err: errors.New(`ent: missing required field "IMBot.pairing_enabled"`)}
	}
	if _, ok := _c.mutation.LastError(); !ok {
		return &ValidationError{Name: "last_error", err: errors.New(`ent: missing required field "IMBot.last_error"`)}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "IMBot.api_key"`)}
	}
	return nil
}

func (_c *IMBotCreate) sqlSave(ctx context.Context) (*IMBot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IMBotCreate) createSpec() (*IMBot, *sqlgraph.CreateSpec) {
	var (
		_node = &IMBot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(imbot.Table, sqlgraph.NewFieldSpec(imbot.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(imbot.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(imbot.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(imbot.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(imbot.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(imbot.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.CredentialsEncrypted(); ok {
		_spec.SetField(imbot.FieldCredentialsEncrypted, field.TypeString, value)
		_node.CredentialsEncrypted = value
	}
	if value, ok := _c.mutation.ModelOverride(); ok {
		_spec.SetField(imbot.FieldModelOverride, field.TypeString, value)
		_node.ModelOverride = value
	}
	if value, ok := _c.mutation.SystemPrompt(); ok {
		_spec.SetField(imbot.FieldSystemPrompt, field.TypeString, value)
		_node.SystemPrompt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(imbot.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.MaxConcurrency(); ok {
		_spec.SetField(imbot.FieldMaxConcurrency, field.TypeInt, value)
		_node.MaxConcurrency = value
	}
	if value, ok := _c.mutation.HistoryMaxMessages(); ok {
		_spec.SetField(imbot.FieldHistoryMaxMessages, field.TypeInt, value)
		_node.HistoryMaxMessages = value
	}
	if value, ok := _c.mutation.PairingEnabled(); ok {
		_spec.SetField(imbot.FieldPairingEnabled, field.TypeBool, value)
		_node.PairingEnabled = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(imbot.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imbot.APIKeyTable,
			Columns: []string{imbot.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imbot.ChatsTable,
			Columns: []string{imbot.ChatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imbotchat.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IMBot.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IMBotUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IMBotCreate) OnConflict(opts ...sql.ConflictOption) *IMBotUpsertOne {
	_c.conflict = opts
	return &IMBotUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IMBot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IMBotCreate) OnConflictColumns(columns ...string) *IMBotUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IMBotUpsertOne{
		create: _c,
	}
}

type (
	// IMBotUpsertOne is the builder for "upsert"-ing
	//  one IMBot node.
	IMBotUpsertOne struct {
		create *IMBotCreate
	}

	// IMBotUpsert is the "OnConflict" setter.
	IMBotUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *IMBotUpsert) SetUpdatedAt(v time.Time) *IMBotUpsert {
	u.Set(imbot.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IMBotUpsert) UpdateUpdatedAt() *IMBotUpsert {
	u.SetExcluded(imbot.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *IMBotUpsert) SetDeletedAt(v time.Time) *IMBotUpsert {
	u.Set(imbot.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *IMBotUpsert) UpdateDeletedAt() *IMBotUpsert {
	u.SetExcluded(imbot.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *IMBotUpsert) ClearDeletedAt() *IMBotUpsert {
	u.SetNull(imbot.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *IMBotUpsert) SetName(v string) *IMBotUpsert {
	u.Set(imbot.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *IMBotUpsert) UpdateName() *IMBotUpsert {
	u.SetExcluded(imbot.FieldName)
	return u
}

// SetPlatform sets the "platform" field.
func (u *IMBotUpsert) SetPlatform(v string) *IMBotUpsert {
	u.Set(imbot.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *IMBotUpsert) UpdatePlatform() *IMBotUpsert {
	u.SetExcluded(imbot.FieldPlatform)
	return u
}

// SetCredentialsEncrypted sets the "credentials_encrypted" field.
func (u *IMBotUpsert) SetCredentialsEncrypted(v string) *IMBotUpsert {
	u.Set(imbot.FieldCredentialsEncrypted, v)
	return u
}

// UpdateCredentialsEncrypted sets the "credentials_encrypted" field to the value that was provided on create.
func (u *IMBotUpsert) UpdateCredentialsEncrypted() *IMBotUpsert {
	u.SetExcluded(imbot.FieldCredentialsEncrypted)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *IMBotUpsert) SetAPIKeyID(v int64) *IMBotUpsert {
	u.Set(imbot.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *IMBotUpsert) UpdateAPIKeyID() *IMBotUpsert {
	u.SetExcluded(imbot.FieldAPIKeyID)
	return u
}

// SetModelOverride sets the "model_override" field.
func (u *IMBotUpsert) SetModelOverride(v string) *IMBotUpsert {
	u.Set(imbot.FieldModelOverride, v)
	return u
}

// UpdateModelOverride sets the "model_override" field to the value that was provided on create.
func (u *IMBotUpsert) UpdateModelOverride() *IMBotUpsert {
	u.SetExcluded(imbot.FieldModelOverride)
	return u
}

// SetSystemPrompt sets the "system_prompt" field.
func (u *IMBotUpsert) SetSystemPrompt(v string) *IMBotUpsert {
	u.Set(imbot.FieldSystemPrompt, v)
	return u
}

// UpdateSystemPrompt sets the "system_prompt" field to the value that was provided on create.
func (u *IMBotUpsert) UpdateSystemPrompt() *IMBotUpsert {
	u.SetExcluded(imbot.FieldSystemPrompt)
	return u
}

// SetStatus sets the "status" field.
func (u *IMBotUpsert) SetStatus(v string) *IMBotUpsert {
	u.Set(imbot.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IMBotUpsert) UpdateStatus() *IMBotUpsert {
	u.SetExcluded(imbot.FieldStatus)
	return u
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (u *IMBotUpsert) SetMaxConcurrency(v int) *IMBotUpsert {
	u.Set(imbot.FieldMaxConcurrency, v)
	return u
}

// UpdateMaxConcurrency sets the "max_concurrency" field to the value that was provided on create.
func (u *IMBotUpsert) UpdateMaxConcurrency() *IMBotUpsert {
	u.SetExcluded(imbot.FieldMaxConcurrency)
	return u
}

// AddMaxConcurrency adds v to the "max_concurrency" field.
func (u *IMBotUpsert) AddMaxConcurrency(v int) *IMBotUpsert {
	u.Add(imbot.FieldMaxConcurrency, v)
	return u
}

// SetHistoryMaxMessages sets the "history_max_messages" field.
func (u *IMBotUpsert) SetHistoryMaxMessages(v int) *IMBotUpsert {
	u.Set(imbot.FieldHistoryMaxMessages, v)
	return u
}

// UpdateHistoryMaxMessages sets the "history_max_messages" field to the value that was provided on create.
func (u *IMBotUpsert) UpdateHistoryMaxMessages() *IMBotUpsert {
	u.SetExcluded(imbot.FieldHistoryMaxMessages)
	return u
}

// AddHistoryMaxMessages adds v to the "history_max_messages" field.
func (u *IMBotUpsert) AddHistoryMaxMessages(v int) *IMBotUpsert {
	u.Add(imbot.FieldHistoryMaxMessages, v)
	return u
}

// SetPairingEnabled sets the "pairing_enabled" field.
func (u *IMBotUpsert) SetPairingEnabled(v bool) *IMBotUpsert {
	u.Set(imbot.FieldPairingEnabled, v)
	return u
}

// UpdatePairingEnabled sets the "pairing_enabled" field to the value that was provided on create.
func (u *IMBotUpsert) UpdatePairingEnabled() *IMBotUpsert {
	u.SetExcluded(imbot.FieldPairingEnabled)
	return u
}

// SetLastError sets the "last_error" field.
func (u *IMBotUpsert) SetLastError(v string) *IMBotUpsert {
	u.Set(imbot.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *IMBotUpsert) UpdateLastError() *IMBotUpsert {
	u.SetExcluded(imbot.FieldLastError)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.IMBot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IMBotUpsertOne) UpdateNewValues() *IMBotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(imbot.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IMBot.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IMBotUpsertOne) Ignore() *IMBotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IMBotUpsertOne) DoNothing() *IMBotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IMBotCreate.OnConflict
// documentation for more info.
func (u *IMBotUpsertOne) Update(set func(*IMBotUpsert)) *IMBotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IMBotUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IMBotUpsertOne) SetUpdatedAt(v time.Time) *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IMBotUpsertOne) UpdateUpdatedAt() *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *IMBotUpsertOne) SetDeletedAt(v time.Time) *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *IMBotUpsertOne) UpdateDeletedAt() *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *IMBotUpsertOne) ClearDeletedAt() *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *IMBotUpsertOne) SetName(v string) *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *IMBotUpsertOne) UpdateName() *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateName()
	})
}

// SetPlatform sets the "platform" field.
func (u *IMBotUpsertOne) SetPlatform(v string) *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *IMBotUpsertOne) UpdatePlatform() *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdatePlatform()
	})
}

// SetCredentialsEncrypted sets the "credentials_encrypted" field.
func (u *IMBotUpsertOne) SetCredentialsEncrypted(v string) *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.SetCredentialsEncrypted(v)
	})
}

// UpdateCredentialsEncrypted sets the "credentials_encrypted" field to the value that was provided on create.
func (u *IMBotUpsertOne) UpdateCredentialsEncrypted() *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateCredentialsEncrypted()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *IMBotUpsertOne) SetAPIKeyID(v int64) *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *IMBotUpsertOne) UpdateAPIKeyID() *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetModelOverride sets the "model_override" field.
func (u *IMBotUpsertOne) SetModelOverride(v string) *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.SetModelOverride(v)
	})
}

// UpdateModelOverride sets the "model_override" field to the value that was provided on create.
func (u *IMBotUpsertOne) UpdateModelOverride() *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateModelOverride()
	})
}

// SetSystemPrompt sets the "system_prompt" field.
func (u *IMBotUpsertOne) SetSystemPrompt(v string) *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.SetSystemPrompt(v)
	})
}

// UpdateSystemPrompt sets the "system_prompt" field to the value that was provided on create.
func (u *IMBotUpsertOne) UpdateSystemPrompt() *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateSystemPrompt()
	})
}

// SetStatus sets the "status" field.
func (u *IMBotUpsertOne) SetStatus(v string) *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IMBotUpsertOne) UpdateStatus() *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateStatus()
	})
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (u *IMBotUpsertOne) SetMaxConcurrency(v int) *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.SetMaxConcurrency(v)
	})
}

// AddMaxConcurrency adds v to the "max_concurrency" field.
func (u *IMBotUpsertOne) AddMaxConcurrency(v int) *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.AddMaxConcurrency(v)
	})
}

// UpdateMaxConcurrency sets the "max_concurrency" field to the value that was provided on create.
func (u *IMBotUpsertOne) UpdateMaxConcurrency() *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateMaxConcurrency()
	})
}

// SetHistoryMaxMessages sets the "history_max_messages" field.
func (u *IMBotUpsertOne) SetHistoryMaxMessages(v int) *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.SetHistoryMaxMessages(v)
	})
}

// AddHistoryMaxMessages adds v to the "history_max_messages" field.
func (u *IMBotUpsertOne) AddHistoryMaxMessages(v int) *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.AddHistoryMaxMessages(v)
	})
}

// UpdateHistoryMaxMessages sets the "history_max_messages" field to the value that was provided on create.
func (u *IMBotUpsertOne) UpdateHistoryMaxMessages() *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateHistoryMaxMessages()
	})
}

// SetPairingEnabled sets the "pairing_enabled" field.
func (u *IMBotUpsertOne) SetPairingEnabled(v bool) *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.SetPairingEnabled(v)
	})
}

// UpdatePairingEnabled sets the "pairing_enabled" field to the value that was provided on create.
func (u *IMBotUpsertOne) UpdatePairingEnabled() *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdatePairingEnabled()
	})
}

// SetLastError sets the "last_error" field.
func (u *IMBotUpsertOne) SetLastError(v string) *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *IMBotUpsertOne) UpdateLastError() *IMBotUpsertOne {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateLastError()
	})
}

// Exec executes the query.
func (u *IMBotUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IMBotCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IMBotUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IMBotUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IMBotUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IMBotCreateBulk is the builder for creating many IMBot entities in bulk.
type IMBotCreateBulk struct {
	config
	err      error
	builders []*IMBotCreate
	conflict []sql.ConflictOption
}

// Save creates the IMBot entities in the database.
func (_c *IMBotCreateBulk) Save(ctx context.Context) ([]*IMBot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IMBot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IMBotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IMBotCreateBulk) SaveX(ctx context.Context) []*IMBot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IMBotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IMBotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IMBot.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IMBotUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IMBotCreateBulk) OnConflict(opts ...sql.ConflictOption) *IMBotUpsertBulk {
	_c.conflict = opts
	return &IMBotUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IMBot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IMBotCreateBulk) OnConflictColumns(columns ...string) *IMBotUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IMBotUpsertBulk{
		create: _c,
	}
}

// IMBotUpsertBulk is the builder for "upsert"-ing
// a bulk of IMBot nodes.
type IMBotUpsertBulk struct {
	create *IMBotCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IMBot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IMBotUpsertBulk) UpdateNewValues() *IMBotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(imbot.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IMBot.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IMBotUpsertBulk) Ignore() *IMBotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IMBotUpsertBulk) DoNothing() *IMBotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IMBotCreateBulk.OnConflict
// documentation for more info.
func (u *IMBotUpsertBulk) Update(set func(*IMBotUpsert)) *IMBotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IMBotUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IMBotUpsertBulk) SetUpdatedAt(v time.Time) *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IMBotUpsertBulk) UpdateUpdatedAt() *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *IMBotUpsertBulk) SetDeletedAt(v time.Time) *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *IMBotUpsertBulk) UpdateDeletedAt() *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *IMBotUpsertBulk) ClearDeletedAt() *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *IMBotUpsertBulk) SetName(v string) *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *IMBotUpsertBulk) UpdateName() *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateName()
	})
}

// SetPlatform sets the "platform" field.
func (u *IMBotUpsertBulk) SetPlatform(v string) *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *IMBotUpsertBulk) UpdatePlatform() *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdatePlatform()
	})
}

// SetCredentialsEncrypted sets the "credentials_encrypted" field.
func (u *IMBotUpsertBulk) SetCredentialsEncrypted(v string) *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.SetCredentialsEncrypted(v)
	})
}

// UpdateCredentialsEncrypted sets the "credentials_encrypted" field to the value that was provided on create.
func (u *IMBotUpsertBulk) UpdateCredentialsEncrypted() *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateCredentialsEncrypted()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *IMBotUpsertBulk) SetAPIKeyID(v int64) *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *IMBotUpsertBulk) UpdateAPIKeyID() *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetModelOverride sets the "model_override" field.
func (u *IMBotUpsertBulk) SetModelOverride(v string) *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.SetModelOverride(v)
	})
}

// UpdateModelOverride sets the "model_override" field to the value that was provided on create.
func (u *IMBotUpsertBulk) UpdateModelOverride() *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateModelOverride()
	})
}

// SetSystemPrompt sets the "system_prompt" field.
func (u *IMBotUpsertBulk) SetSystemPrompt(v string) *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.SetSystemPrompt(v)
	})
}

// UpdateSystemPrompt sets the "system_prompt" field to the value that was provided on create.
func (u *IMBotUpsertBulk) UpdateSystemPrompt() *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateSystemPrompt()
	})
}

// SetStatus sets the "status" field.
func (u *IMBotUpsertBulk) SetStatus(v string) *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IMBotUpsertBulk) UpdateStatus() *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateStatus()
	})
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (u *IMBotUpsertBulk) SetMaxConcurrency(v int) *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.SetMaxConcurrency(v)
	})
}

// AddMaxConcurrency adds v to the "max_concurrency" field.
func (u *IMBotUpsertBulk) AddMaxConcurrency(v int) *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.AddMaxConcurrency(v)
	})
}

// UpdateMaxConcurrency sets the "max_concurrency" field to the value that was provided on create.
func (u *IMBotUpsertBulk) UpdateMaxConcurrency() *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateMaxConcurrency()
	})
}

// SetHistoryMaxMessages sets the "history_max_messages" field.
func (u *IMBotUpsertBulk) SetHistoryMaxMessages(v int) *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.SetHistoryMaxMessages(v)
	})
}

// AddHistoryMaxMessages adds v to the "history_max_messages" field.
func (u *IMBotUpsertBulk) AddHistoryMaxMessages(v int) *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.AddHistoryMaxMessages(v)
	})
}

// UpdateHistoryMaxMessages sets the "history_max_messages" field to the value that was provided on create.
func (u *IMBotUpsertBulk) UpdateHistoryMaxMessages() *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateHistoryMaxMessages()
	})
}

// SetPairingEnabled sets the "pairing_enabled" field.
func (u *IMBotUpsertBulk) SetPairingEnabled(v bool) *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.SetPairingEnabled(v)
	})
}

// UpdatePairingEnabled sets the "pairing_enabled" field to the value that was provided on create.
func (u *IMBotUpsertBulk) UpdatePairingEnabled() *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdatePairingEnabled()
	})
}

// SetLastError sets the "last_error" field.
func (u *IMBotUpsertBulk) SetLastError(v string) *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *IMBotUpsertBulk) UpdateLastError() *IMBotUpsertBulk {
	return u.Update(func(s *IMBotUpsert) {
		s.UpdateLastError()
	})
}

// Exec executes the query.
func (u *IMBotUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IMBotCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IMBotCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IMBotUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
