// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/imbot"
	"github.com/Wei-Shaw/sub2api/ent/imbotchat"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// IMBotQuery is the builder for querying IMBot entities.
type IMBotQuery struct {
	config
	ctx        *QueryContext
	order      []imbot.OrderOption
	inters     []Interceptor
	predicates []predicate.IMBot
	withAPIKey *APIKeyQuery
	withChats  *IMBotChatQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IMBotQuery builder.
func (_q *IMBotQuery) Where(ps ...predicate.IMBot) *IMBotQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *IMBotQuery) Limit(limit int) *IMBotQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *IMBotQuery) Offset(offset int) *IMBotQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *IMBotQuery) Unique(unique bool) *IMBotQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *IMBotQuery) Order(o ...imbot.OrderOption) *IMBotQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAPIKey chains the current query on the "api_key" edge.
func (_q *IMBotQuery) QueryAPIKey() *APIKeyQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(imbot.Table, imbot.FieldID, selector),
			sqlgraph.To(apikey.Table, apikey.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, imbot.APIKeyTable, imbot.APIKeyColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChats chains the current query on the "chats" edge.
func (_q *IMBotQuery) QueryChats() *IMBotChatQuery {
	query := (&IMBotChatClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(imbot.Table, imbot.FieldID, selector),
			sqlgraph.To(imbotchat.Table, imbotchat.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, imbot.ChatsTable, imbot.ChatsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first IMBot entity from the query.
// Returns a *NotFoundError when no IMBot was found.
func (_q *IMBotQuery) First(ctx context.Context) (*IMBot, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{imbot.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *IMBotQuery) FirstX(ctx context.Context) *IMBot {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IMBot ID from the query.
// Returns a *NotFoundError when no IMBot ID was found.
func (_q *IMBotQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{imbot.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *IMBotQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IMBot entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IMBot entity is found.
// Returns a *NotFoundError when no IMBot entities are found.
func (_q *IMBotQuery) Only(ctx context.Context) (*IMBot, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{imbot.Label}
	default:
		return nil, &NotSingularError{imbot.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *IMBotQuery) OnlyX(ctx context.Context) *IMBot {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IMBot ID in the query.
// Returns a *NotSingularError when more than one IMBot ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *IMBotQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{imbot.Label}
	default:
		err = &NotSingularError{imbot.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *IMBotQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IMBots.
func (_q *IMBotQuery) All(ctx context.Context) ([]*IMBot, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*IMBot, *IMBotQuery]()
	return withInterceptors[[]*IMBot](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *IMBotQuery) AllX(ctx context.Context) []*IMBot {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IMBot IDs.
func (_q *IMBotQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(imbot.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *IMBotQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *IMBotQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*IMBotQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *IMBotQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *IMBotQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *IMBotQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IMBotQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *IMBotQuery) Clone() *IMBotQuery {
	if _q == nil {
		return nil
	}
	return &IMBotQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]imbot.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.IMBot{}, _q.predicates...),
		withAPIKey: _q.withAPIKey.Clone(),
		withChats:  _q.withChats.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithAPIKey tells the query-builder to eager-load the nodes that are connected to
// the "api_key" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *IMBotQuery) WithAPIKey(opts ...func(*APIKeyQuery)) *IMBotQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAPIKey = query
	return _q
}

// WithChats tells the query-builder to eager-load the nodes that are connected to
// the "chats" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *IMBotQuery) WithChats(opts ...func(*IMBotChatQuery)) *IMBotQuery {
	query := (&IMBotChatClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChats = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IMBot.Query().
//		GroupBy(imbot.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *IMBotQuery) GroupBy(field string, fields ...string) *IMBotGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IMBotGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = imbot.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.IMBot.Query().
//		Select(imbot.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *IMBotQuery) Select(fields ...string) *IMBotSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &IMBotSelect{IMBotQuery: _q}
	sbuild.label = imbot.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IMBotSelect configured with the given aggregations.
func (_q *IMBotQuery) Aggregate(fns ...AggregateFunc) *IMBotSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *IMBotQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !imbot.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *IMBotQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*IMBot, error) {
	var (
		nodes       = []*IMBot{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withAPIKey != nil,
			_q.withChats != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*IMBot).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &IMBot{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAPIKey; query != nil {
		if err := _q.loadAPIKey(ctx, query, nodes, nil,
			func(n *IMBot, e *APIKey) { n.Edges.APIKey = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChats; query != nil {
		if err := _q.loadChats(ctx, query, nodes,
			func(n *IMBot) { n.Edges.Chats = []*IMBotChat{} },
			func(n *IMBot, e *IMBotChat) { n.Edges.Chats = append(n.Edges.Chats, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *IMBotQuery) loadAPIKey(ctx context.Context, query *APIKeyQuery, nodes []*IMBot, init func(*IMBot), assign func(*IMBot, *APIKey)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*IMBot)
	for i := range nodes {
		fk := nodes[i].APIKeyID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(apikey.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "api_key_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *IMBotQuery) loadChats(ctx context.Context, query *IMBotChatQuery, nodes []*IMBot, init func(*IMBot), assign func(*IMBot, *IMBotChat)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*IMBot)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(imbotchat.FieldBotID)
	}
	query.Where(predicate.IMBotChat(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(imbot.ChatsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.BotID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "bot_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *IMBotQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *IMBotQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(imbot.Table, imbot.Columns, sqlgraph.NewFieldSpec(imbot.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, imbot.FieldID)
		for i := range fields {
			if fields[i] != imbot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withAPIKey != nil {
			_spec.Node.AddColumnOnce(imbot.FieldAPIKeyID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *IMBotQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(imbot.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = imbot.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *IMBotQuery) ForUpdate(opts ...sql.LockOption) *IMBotQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *IMBotQuery) ForShare(opts ...sql.LockOption) *IMBotQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// IMBotGroupBy is the group-by builder for IMBot entities.
type IMBotGroupBy struct {
	selector
	build *IMBotQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *IMBotGroupBy) Aggregate(fns ...AggregateFunc) *IMBotGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *IMBotGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IMBotQuery, *IMBotGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *IMBotGroupBy) sqlScan(ctx context.Context, root *IMBotQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IMBotSelect is the builder for selecting fields of IMBot entities.
type IMBotSelect struct {
	*IMBotQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *IMBotSelect) Aggregate(fns ...AggregateFunc) *IMBotSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *IMBotSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IMBotQuery, *IMBotSelect](ctx, _s.IMBotQuery, _s, _s.inters, v)
}

func (_s *IMBotSelect) sqlScan(ctx context.Context, root *IMBotQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
