// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/imbot"
	"github.com/Wei-Shaw/sub2api/ent/imbotchat"
)

// IMBotChat is the model entity for the IMBotChat schema.
type IMBotChat struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// BotID holds the value of the "bot_id" field.
	BotID int64 `json:"bot_id,omitempty"`
	// Platform-native chat identifier (TG chat id, Feishu open_id, ...).
	ChatID string `json:"chat_id,omitempty"`
	// PlatformUserID holds the value of the "platform_user_id" field.
	PlatformUserID string `json:"platform_user_id,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// Stable sticky-session + usage-log identifier, rotated on /new.
	SessionUUID string `json:"session_uuid,omitempty"`
	// ModelOverride holds the value of the "model_override" field.
	ModelOverride string `json:"model_override,omitempty"`
	// active | blocked
	Status string `json:"status,omitempty"`
	// PairedAt holds the value of the "paired_at" field.
	PairedAt time.Time `json:"paired_at,omitempty"`
	// LastMessageAt holds the value of the "last_message_at" field.
	LastMessageAt *time.Time `json:"last_message_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the IMBotChatQuery when eager-loading is set.
	Edges        IMBotChatEdges `json:"edges"`
	selectValues sql.SelectValues
}

// IMBotChatEdges holds the relations/edges for other nodes in the graph.
type IMBotChatEdges struct {
	// Bot holds the value of the bot edge.
	Bot *IMBot `json:"bot,omitempty"`
	// Messages holds the value of the messages edge.
	Messages []*IMBotMessage `json:"messages,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// BotOrErr returns the Bot value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IMBotChatEdges) BotOrErr() (*IMBot, error) {
	if e.Bot != nil {
		return e.Bot, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: imbot.Label}
	}
	return nil, &NotLoadedError{edge: "bot"}
}

// MessagesOrErr returns the Messages value or an error if the edge
// was not loaded in eager-loading.
func (e IMBotChatEdges) MessagesOrErr() ([]*IMBotMessage, error) {
	if e.loadedTypes[1] {
		return e.Messages, nil
	}
	return nil, &NotLoadedError{edge: "messages"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IMBotChat) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case imbotchat.FieldID, imbotchat.FieldBotID:
			values[i] = new(sql.NullInt64)
		case imbotchat.FieldChatID, imbotchat.FieldPlatformUserID, imbotchat.FieldDisplayName, imbotchat.FieldSessionUUID, imbotchat.FieldModelOverride, imbotchat.FieldStatus:
			values[i] = new(sql.NullString)
		case imbotchat.FieldCreatedAt, imbotchat.FieldUpdatedAt, imbotchat.FieldPairedAt, imbotchat.FieldLastMessageAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IMBotChat fields.
func (_m *IMBotChat) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case imbotchat.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case imbotchat.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case imbotchat.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case imbotchat.FieldBotID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bot_id", values[i])
			} else if value.Valid {
				_m.BotID = value.Int64
			}
		case imbotchat.FieldChatID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field chat_id", values[i])
			} else if value.Valid {
				_m.ChatID = value.String
			}
		case imbotchat.FieldPlatformUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform_user_id", values[i])
			} else if value.Valid {
				_m.PlatformUserID = value.String
			}
		case imbotchat.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case imbotchat.FieldSessionUUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_uuid", values[i])
			} else if value.Valid {
				_m.SessionUUID = value.String
			}
		case imbotchat.FieldModelOverride:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_override", values[i])
			} else if value.Valid {
				_m.ModelOverride = value.String
			}
		case imbotchat.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case imbotchat.FieldPairedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paired_at", values[i])
			} else if value.Valid {
				_m.PairedAt = value.Time
			}
		case imbotchat.FieldLastMessageAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_message_at", values[i])
			} else if value.Valid {
				_m.LastMessageAt = new(time.Time)
				*_m.LastMessageAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IMBotChat.
// This includes values selected through modifiers, order, etc.
func (_m *IMBotChat) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBot queries the "bot" edge of the IMBotChat entity.
func (_m *IMBotChat) QueryBot() *IMBotQuery {
	return NewIMBotChatClient(_m.config).QueryBot(_m)
}

// QueryMessages queries the "messages" edge of the IMBotChat entity.
func (_m *IMBotChat) QueryMessages() *IMBotMessageQuery {
	return NewIMBotChatClient(_m.config).QueryMessages(_m)
}

// Update returns a builder for updating this IMBotChat.
// Note that you need to call IMBotChat.Unwrap() before calling this method if this IMBotChat
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IMBotChat) Update() *IMBotChatUpdateOne {
	return NewIMBotChatClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IMBotChat entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IMBotChat) Unwrap() *IMBotChat {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IMBotChat is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IMBotChat) String() string {
	var builder strings.Builder
	builder.WriteString("IMBotChat(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("bot_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BotID))
	builder.WriteString(", ")
	builder.WriteString("chat_id=")
	builder.WriteString(_m.ChatID)
	builder.WriteString(", ")
	builder.WriteString("platform_user_id=")
	builder.WriteString(_m.PlatformUserID)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("session_uuid=")
	builder.WriteString(_m.SessionUUID)
	builder.WriteString(", ")
	builder.WriteString("model_override=")
	builder.WriteString(_m.ModelOverride)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("paired_at=")
	builder.WriteString(_m.PairedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastMessageAt; v != nil {
		builder.WriteString("last_message_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// IMBotChats is a parsable slice of IMBotChat.
type IMBotChats []*IMBotChat
