// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/proxysubscription"
)

// ProxySubscriptionUpdate is the builder for updating ProxySubscription entities.
type ProxySubscriptionUpdate struct {
	config
	hooks    []Hook
	mutation *ProxySubscriptionMutation
}

// Where appends a list predicates to the ProxySubscriptionUpdate builder.
func (_u *ProxySubscriptionUpdate) Where(ps ...predicate.ProxySubscription) *ProxySubscriptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxySubscriptionUpdate) SetUpdatedAt(v time.Time) *ProxySubscriptionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ProxySubscriptionUpdate) SetName(v string) *ProxySubscriptionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxySubscriptionUpdate) SetNillableName(v *string) *ProxySubscriptionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ProxySubscriptionUpdate) SetEnabled(v bool) *ProxySubscriptionUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ProxySubscriptionUpdate) SetNillableEnabled(v *bool) *ProxySubscriptionUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *ProxySubscriptionUpdate) SetSourceType(v string) *ProxySubscriptionUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *ProxySubscriptionUpdate) SetNillableSourceType(v *string) *ProxySubscriptionUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSubscriptionURL sets the "subscription_url" field.
func (_u *ProxySubscriptionUpdate) SetSubscriptionURL(v string) *ProxySubscriptionUpdate {
	_u.mutation.SetSubscriptionURL(v)
	return _u
}

// SetNillableSubscriptionURL sets the "subscription_url" field if the given value is not nil.
func (_u *ProxySubscriptionUpdate) SetNillableSubscriptionURL(v *string) *ProxySubscriptionUpdate {
	if v != nil {
		_u.SetSubscriptionURL(*v)
	}
	return _u
}

// ClearSubscriptionURL clears the value of the "subscription_url" field.
func (_u *ProxySubscriptionUpdate) ClearSubscriptionURL() *ProxySubscriptionUpdate {
	_u.mutation.ClearSubscriptionURL()
	return _u
}

// SetInlineBody sets the "inline_body" field.
func (_u *ProxySubscriptionUpdate) SetInlineBody(v string) *ProxySubscriptionUpdate {
	_u.mutation.SetInlineBody(v)
	return _u
}

// SetNillableInlineBody sets the "inline_body" field if the given value is not nil.
func (_u *ProxySubscriptionUpdate) SetNillableInlineBody(v *string) *ProxySubscriptionUpdate {
	if v != nil {
		_u.SetInlineBody(*v)
	}
	return _u
}

// ClearInlineBody clears the value of the "inline_body" field.
func (_u *ProxySubscriptionUpdate) ClearInlineBody() *ProxySubscriptionUpdate {
	_u.mutation.ClearInlineBody()
	return _u
}

// SetNamePrefix sets the "name_prefix" field.
func (_u *ProxySubscriptionUpdate) SetNamePrefix(v string) *ProxySubscriptionUpdate {
	_u.mutation.SetNamePrefix(v)
	return _u
}

// SetNillableNamePrefix sets the "name_prefix" field if the given value is not nil.
func (_u *ProxySubscriptionUpdate) SetNillableNamePrefix(v *string) *ProxySubscriptionUpdate {
	if v != nil {
		_u.SetNamePrefix(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *ProxySubscriptionUpdate) SetProtocol(v string) *ProxySubscriptionUpdate {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *ProxySubscriptionUpdate) SetNillableProtocol(v *string) *ProxySubscriptionUpdate {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetBindAddress sets the "bind_address" field.
func (_u *ProxySubscriptionUpdate) SetBindAddress(v string) *ProxySubscriptionUpdate {
	_u.mutation.SetBindAddress(v)
	return _u
}

// SetNillableBindAddress sets the "bind_address" field if the given value is not nil.
func (_u *ProxySubscriptionUpdate) SetNillableBindAddress(v *string) *ProxySubscriptionUpdate {
	if v != nil {
		_u.SetBindAddress(*v)
	}
	return _u
}

// SetBasePort sets the "base_port" field.
func (_u *ProxySubscriptionUpdate) SetBasePort(v int) *ProxySubscriptionUpdate {
	_u.mutation.ResetBasePort()
	_u.mutation.SetBasePort(v)
	return _u
}

// SetNillableBasePort sets the "base_port" field if the given value is not nil.
func (_u *ProxySubscriptionUpdate) SetNillableBasePort(v *int) *ProxySubscriptionUpdate {
	if v != nil {
		_u.SetBasePort(*v)
	}
	return _u
}

// AddBasePort adds value to the "base_port" field.
func (_u *ProxySubscriptionUpdate) AddBasePort(v int) *ProxySubscriptionUpdate {
	_u.mutation.AddBasePort(v)
	return _u
}

// SetMaxPorts sets the "max_ports" field.
func (_u *ProxySubscriptionUpdate) SetMaxPorts(v int) *ProxySubscriptionUpdate {
	_u.mutation.ResetMaxPorts()
	_u.mutation.SetMaxPorts(v)
	return _u
}

// SetNillableMaxPorts sets the "max_ports" field if the given value is not nil.
func (_u *ProxySubscriptionUpdate) SetNillableMaxPorts(v *int) *ProxySubscriptionUpdate {
	if v != nil {
		_u.SetMaxPorts(*v)
	}
	return _u
}

// AddMaxPorts adds value to the "max_ports" field.
func (_u *ProxySubscriptionUpdate) AddMaxPorts(v int) *ProxySubscriptionUpdate {
	_u.mutation.AddMaxPorts(v)
	return _u
}

// SetSyncIntervalSec sets the "sync_interval_sec" field.
func (_u *ProxySubscriptionUpdate) SetSyncIntervalSec(v int) *ProxySubscriptionUpdate {
	_u.mutation.ResetSyncIntervalSec()
	_u.mutation.SetSyncIntervalSec(v)
	return _u
}

// SetNillableSyncIntervalSec sets the "sync_interval_sec" field if the given value is not nil.
func (_u *ProxySubscriptionUpdate) SetNillableSyncIntervalSec(v *int) *ProxySubscriptionUpdate {
	if v != nil {
		_u.SetSyncIntervalSec(*v)
	}
	return _u
}

// AddSyncIntervalSec adds value to the "sync_interval_sec" field.
func (_u *ProxySubscriptionUpdate) AddSyncIntervalSec(v int) *ProxySubscriptionUpdate {
	_u.mutation.AddSyncIntervalSec(v)
	return _u
}

// SetNodeAllowContains sets the "node_allow_contains" field.
func (_u *ProxySubscriptionUpdate) SetNodeAllowContains(v []string) *ProxySubscriptionUpdate {
	_u.mutation.SetNodeAllowContains(v)
	return _u
}

// AppendNodeAllowContains appends value to the "node_allow_contains" field.
func (_u *ProxySubscriptionUpdate) AppendNodeAllowContains(v []string) *ProxySubscriptionUpdate {
	_u.mutation.AppendNodeAllowContains(v)
	return _u
}

// SetNodeIdentityAllowlist sets the "node_identity_allowlist" field.
func (_u *ProxySubscriptionUpdate) SetNodeIdentityAllowlist(v []string) *ProxySubscriptionUpdate {
	_u.mutation.SetNodeIdentityAllowlist(v)
	return _u
}

// AppendNodeIdentityAllowlist appends value to the "node_identity_allowlist" field.
func (_u *ProxySubscriptionUpdate) AppendNodeIdentityAllowlist(v []string) *ProxySubscriptionUpdate {
	_u.mutation.AppendNodeIdentityAllowlist(v)
	return _u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_u *ProxySubscriptionUpdate) SetLastSyncAt(v time.Time) *ProxySubscriptionUpdate {
	_u.mutation.SetLastSyncAt(v)
	return _u
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_u *ProxySubscriptionUpdate) SetNillableLastSyncAt(v *time.Time) *ProxySubscriptionUpdate {
	if v != nil {
		_u.SetLastSyncAt(*v)
	}
	return _u
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (_u *ProxySubscriptionUpdate) ClearLastSyncAt() *ProxySubscriptionUpdate {
	_u.mutation.ClearLastSyncAt()
	return _u
}

// SetLastSyncStatus sets the "last_sync_status" field.
func (_u *ProxySubscriptionUpdate) SetLastSyncStatus(v string) *ProxySubscriptionUpdate {
	_u.mutation.SetLastSyncStatus(v)
	return _u
}

// SetNillableLastSyncStatus sets the "last_sync_status" field if the given value is not nil.
func (_u *ProxySubscriptionUpdate) SetNillableLastSyncStatus(v *string) *ProxySubscriptionUpdate {
	if v != nil {
		_u.SetLastSyncStatus(*v)
	}
	return _u
}

// ClearLastSyncStatus clears the value of the "last_sync_status" field.
func (_u *ProxySubscriptionUpdate) ClearLastSyncStatus() *ProxySubscriptionUpdate {
	_u.mutation.ClearLastSyncStatus()
	return _u
}

// SetLastSyncError sets the "last_sync_error" field.
func (_u *ProxySubscriptionUpdate) SetLastSyncError(v string) *ProxySubscriptionUpdate {
	_u.mutation.SetLastSyncError(v)
	return _u
}

// SetNillableLastSyncError sets the "last_sync_error" field if the given value is not nil.
func (_u *ProxySubscriptionUpdate) SetNillableLastSyncError(v *string) *ProxySubscriptionUpdate {
	if v != nil {
		_u.SetLastSyncError(*v)
	}
	return _u
}

// ClearLastSyncError clears the value of the "last_sync_error" field.
func (_u *ProxySubscriptionUpdate) ClearLastSyncError() *ProxySubscriptionUpdate {
	_u.mutation.ClearLastSyncError()
	return _u
}

// SetLastConfigHash sets the "last_config_hash" field.
func (_u *ProxySubscriptionUpdate) SetLastConfigHash(v string) *ProxySubscriptionUpdate {
	_u.mutation.SetLastConfigHash(v)
	return _u
}

// SetNillableLastConfigHash sets the "last_config_hash" field if the given value is not nil.
func (_u *ProxySubscriptionUpdate) SetNillableLastConfigHash(v *string) *ProxySubscriptionUpdate {
	if v != nil {
		_u.SetLastConfigHash(*v)
	}
	return _u
}

// ClearLastConfigHash clears the value of the "last_config_hash" field.
func (_u *ProxySubscriptionUpdate) ClearLastConfigHash() *ProxySubscriptionUpdate {
	_u.mutation.ClearLastConfigHash()
	return _u
}

// SetDesiredCount sets the "desired_count" field.
func (_u *ProxySubscriptionUpdate) SetDesiredCount(v int) *ProxySubscriptionUpdate {
	_u.mutation.ResetDesiredCount()
	_u.mutation.SetDesiredCount(v)
	return _u
}

// SetNillableDesiredCount sets the "desired_count" field if the given value is not nil.
func (_u *ProxySubscriptionUpdate) SetNillableDesiredCount(v *int) *ProxySubscriptionUpdate {
	if v != nil {
		_u.SetDesiredCount(*v)
	}
	return _u
}

// AddDesiredCount adds value to the "desired_count" field.
func (_u *ProxySubscriptionUpdate) AddDesiredCount(v int) *ProxySubscriptionUpdate {
	_u.mutation.AddDesiredCount(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ProxySubscriptionUpdate) SetCreatedBy(v int64) *ProxySubscriptionUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ProxySubscriptionUpdate) SetNillableCreatedBy(v *int64) *ProxySubscriptionUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ProxySubscriptionUpdate) AddCreatedBy(v int64) *ProxySubscriptionUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ProxySubscriptionUpdate) ClearCreatedBy() *ProxySubscriptionUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetNextDueAt sets the "next_due_at" field.
func (_u *ProxySubscriptionUpdate) SetNextDueAt(v time.Time) *ProxySubscriptionUpdate {
	_u.mutation.SetNextDueAt(v)
	return _u
}

// SetNillableNextDueAt sets the "next_due_at" field if the given value is not nil.
func (_u *ProxySubscriptionUpdate) SetNillableNextDueAt(v *time.Time) *ProxySubscriptionUpdate {
	if v != nil {
		_u.SetNextDueAt(*v)
	}
	return _u
}

// ClearNextDueAt clears the value of the "next_due_at" field.
func (_u *ProxySubscriptionUpdate) ClearNextDueAt() *ProxySubscriptionUpdate {
	_u.mutation.ClearNextDueAt()
	return _u
}

// Mutation returns the ProxySubscriptionMutation object of the builder.
func (_u *ProxySubscriptionUpdate) Mutation() *ProxySubscriptionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxySubscriptionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxySubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxySubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxySubscriptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxySubscriptionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxysubscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxySubscriptionUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxysubscription.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := proxysubscription.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubscriptionURL(); ok {
		if err := proxysubscription.SubscriptionURLValidator(v); err != nil {
			return &ValidationError{Name: "subscription_url", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.subscription_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NamePrefix(); ok {
		if err := proxysubscription.NamePrefixValidator(v); err != nil {
			return &ValidationError{Name: "name_prefix", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.name_prefix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Protocol(); ok {
		if err := proxysubscription.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BindAddress(); ok {
		if err := proxysubscription.BindAddressValidator(v); err != nil {
			return &ValidationError{Name: "bind_address", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.bind_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastSyncStatus(); ok {
		if err := proxysubscription.LastSyncStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_sync_status", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.last_sync_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastConfigHash(); ok {
		if err := proxysubscription.LastConfigHashValidator(v); err != nil {
			return &ValidationError{Name: "last_config_hash", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.last_config_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxySubscriptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxysubscription.Table, proxysubscription.Columns, sqlgraph.NewFieldSpec(proxysubscription.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxysubscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxysubscription.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(proxysubscription.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(proxysubscription.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubscriptionURL(); ok {
		_spec.SetField(proxysubscription.FieldSubscriptionURL, field.TypeString, value)
	}
	if _u.mutation.SubscriptionURLCleared() {
		_spec.ClearField(proxysubscription.FieldSubscriptionURL, field.TypeString)
	}
	if value, ok := _u.mutation.InlineBody(); ok {
		_spec.SetField(proxysubscription.FieldInlineBody, field.TypeString, value)
	}
	if _u.mutation.InlineBodyCleared() {
		_spec.ClearField(proxysubscription.FieldInlineBody, field.TypeString)
	}
	if value, ok := _u.mutation.NamePrefix(); ok {
		_spec.SetField(proxysubscription.FieldNamePrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(proxysubscription.FieldProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.BindAddress(); ok {
		_spec.SetField(proxysubscription.FieldBindAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.BasePort(); ok {
		_spec.SetField(proxysubscription.FieldBasePort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBasePort(); ok {
		_spec.AddField(proxysubscription.FieldBasePort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxPorts(); ok {
		_spec.SetField(proxysubscription.FieldMaxPorts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxPorts(); ok {
		_spec.AddField(proxysubscription.FieldMaxPorts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SyncIntervalSec(); ok {
		_spec.SetField(proxysubscription.FieldSyncIntervalSec, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSyncIntervalSec(); ok {
		_spec.AddField(proxysubscription.FieldSyncIntervalSec, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NodeAllowContains(); ok {
		_spec.SetField(proxysubscription.FieldNodeAllowContains, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedNodeAllowContains(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, proxysubscription.FieldNodeAllowContains, value)
		})
	}
	if value, ok := _u.mutation.NodeIdentityAllowlist(); ok {
		_spec.SetField(proxysubscription.FieldNodeIdentityAllowlist, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedNodeIdentityAllowlist(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, proxysubscription.FieldNodeIdentityAllowlist, value)
		})
	}
	if value, ok := _u.mutation.LastSyncAt(); ok {
		_spec.SetField(proxysubscription.FieldLastSyncAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncAtCleared() {
		_spec.ClearField(proxysubscription.FieldLastSyncAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSyncStatus(); ok {
		_spec.SetField(proxysubscription.FieldLastSyncStatus, field.TypeString, value)
	}
	if _u.mutation.LastSyncStatusCleared() {
		_spec.ClearField(proxysubscription.FieldLastSyncStatus, field.TypeString)
	}
	if value, ok := _u.mutation.LastSyncError(); ok {
		_spec.SetField(proxysubscription.FieldLastSyncError, field.TypeString, value)
	}
	if _u.mutation.LastSyncErrorCleared() {
		_spec.ClearField(proxysubscription.FieldLastSyncError, field.TypeString)
	}
	if value, ok := _u.mutation.LastConfigHash(); ok {
		_spec.SetField(proxysubscription.FieldLastConfigHash, field.TypeString, value)
	}
	if _u.mutation.LastConfigHashCleared() {
		_spec.ClearField(proxysubscription.FieldLastConfigHash, field.TypeString)
	}
	if value, ok := _u.mutation.DesiredCount(); ok {
		_spec.SetField(proxysubscription.FieldDesiredCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDesiredCount(); ok {
		_spec.AddField(proxysubscription.FieldDesiredCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(proxysubscription.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(proxysubscription.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(proxysubscription.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.NextDueAt(); ok {
		_spec.SetField(proxysubscription.FieldNextDueAt, field.TypeTime, value)
	}
	if _u.mutation.NextDueAtCleared() {
		_spec.ClearField(proxysubscription.FieldNextDueAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxysubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxySubscriptionUpdateOne is the builder for updating a single ProxySubscription entity.
type ProxySubscriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxySubscriptionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxySubscriptionUpdateOne) SetUpdatedAt(v time.Time) *ProxySubscriptionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ProxySubscriptionUpdateOne) SetName(v string) *ProxySubscriptionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxySubscriptionUpdateOne) SetNillableName(v *string) *ProxySubscriptionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ProxySubscriptionUpdateOne) SetEnabled(v bool) *ProxySubscriptionUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ProxySubscriptionUpdateOne) SetNillableEnabled(v *bool) *ProxySubscriptionUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *ProxySubscriptionUpdateOne) SetSourceType(v string) *ProxySubscriptionUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *ProxySubscriptionUpdateOne) SetNillableSourceType(v *string) *ProxySubscriptionUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSubscriptionURL sets the "subscription_url" field.
func (_u *ProxySubscriptionUpdateOne) SetSubscriptionURL(v string) *ProxySubscriptionUpdateOne {
	_u.mutation.SetSubscriptionURL(v)
	return _u
}

// SetNillableSubscriptionURL sets the "subscription_url" field if the given value is not nil.
func (_u *ProxySubscriptionUpdateOne) SetNillableSubscriptionURL(v *string) *ProxySubscriptionUpdateOne {
	if v != nil {
		_u.SetSubscriptionURL(*v)
	}
	return _u
}

// ClearSubscriptionURL clears the value of the "subscription_url" field.
func (_u *ProxySubscriptionUpdateOne) ClearSubscriptionURL() *ProxySubscriptionUpdateOne {
	_u.mutation.ClearSubscriptionURL()
	return _u
}

// SetInlineBody sets the "inline_body" field.
func (_u *ProxySubscriptionUpdateOne) SetInlineBody(v string) *ProxySubscriptionUpdateOne {
	_u.mutation.SetInlineBody(v)
	return _u
}

// SetNillableInlineBody sets the "inline_body" field if the given value is not nil.
func (_u *ProxySubscriptionUpdateOne) SetNillableInlineBody(v *string) *ProxySubscriptionUpdateOne {
	if v != nil {
		_u.SetInlineBody(*v)
	}
	return _u
}

// ClearInlineBody clears the value of the "inline_body" field.
func (_u *ProxySubscriptionUpdateOne) ClearInlineBody() *ProxySubscriptionUpdateOne {
	_u.mutation.ClearInlineBody()
	return _u
}

// SetNamePrefix sets the "name_prefix" field.
func (_u *ProxySubscriptionUpdateOne) SetNamePrefix(v string) *ProxySubscriptionUpdateOne {
	_u.mutation.SetNamePrefix(v)
	return _u
}

// SetNillableNamePrefix sets the "name_prefix" field if the given value is not nil.
func (_u *ProxySubscriptionUpdateOne) SetNillableNamePrefix(v *string) *ProxySubscriptionUpdateOne {
	if v != nil {
		_u.SetNamePrefix(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *ProxySubscriptionUpdateOne) SetProtocol(v string) *ProxySubscriptionUpdateOne {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *ProxySubscriptionUpdateOne) SetNillableProtocol(v *string) *ProxySubscriptionUpdateOne {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetBindAddress sets the "bind_address" field.
func (_u *ProxySubscriptionUpdateOne) SetBindAddress(v string) *ProxySubscriptionUpdateOne {
	_u.mutation.SetBindAddress(v)
	return _u
}

// SetNillableBindAddress sets the "bind_address" field if the given value is not nil.
func (_u *ProxySubscriptionUpdateOne) SetNillableBindAddress(v *string) *ProxySubscriptionUpdateOne {
	if v != nil {
		_u.SetBindAddress(*v)
	}
	return _u
}

// SetBasePort sets the "base_port" field.
func (_u *ProxySubscriptionUpdateOne) SetBasePort(v int) *ProxySubscriptionUpdateOne {
	_u.mutation.ResetBasePort()
	_u.mutation.SetBasePort(v)
	return _u
}

// SetNillableBasePort sets the "base_port" field if the given value is not nil.
func (_u *ProxySubscriptionUpdateOne) SetNillableBasePort(v *int) *ProxySubscriptionUpdateOne {
	if v != nil {
		_u.SetBasePort(*v)
	}
	return _u
}

// AddBasePort adds value to the "base_port" field.
func (_u *ProxySubscriptionUpdateOne) AddBasePort(v int) *ProxySubscriptionUpdateOne {
	_u.mutation.AddBasePort(v)
	return _u
}

// SetMaxPorts sets the "max_ports" field.
func (_u *ProxySubscriptionUpdateOne) SetMaxPorts(v int) *ProxySubscriptionUpdateOne {
	_u.mutation.ResetMaxPorts()
	_u.mutation.SetMaxPorts(v)
	return _u
}

// SetNillableMaxPorts sets the "max_ports" field if the given value is not nil.
func (_u *ProxySubscriptionUpdateOne) SetNillableMaxPorts(v *int) *ProxySubscriptionUpdateOne {
	if v != nil {
		_u.SetMaxPorts(*v)
	}
	return _u
}

// AddMaxPorts adds value to the "max_ports" field.
func (_u *ProxySubscriptionUpdateOne) AddMaxPorts(v int) *ProxySubscriptionUpdateOne {
	_u.mutation.AddMaxPorts(v)
	return _u
}

// SetSyncIntervalSec sets the "sync_interval_sec" field.
func (_u *ProxySubscriptionUpdateOne) SetSyncIntervalSec(v int) *ProxySubscriptionUpdateOne {
	_u.mutation.ResetSyncIntervalSec()
	_u.mutation.SetSyncIntervalSec(v)
	return _u
}

// SetNillableSyncIntervalSec sets the "sync_interval_sec" field if the given value is not nil.
func (_u *ProxySubscriptionUpdateOne) SetNillableSyncIntervalSec(v *int) *ProxySubscriptionUpdateOne {
	if v != nil {
		_u.SetSyncIntervalSec(*v)
	}
	return _u
}

// AddSyncIntervalSec adds value to the "sync_interval_sec" field.
func (_u *ProxySubscriptionUpdateOne) AddSyncIntervalSec(v int) *ProxySubscriptionUpdateOne {
	_u.mutation.AddSyncIntervalSec(v)
	return _u
}

// SetNodeAllowContains sets the "node_allow_contains" field.
func (_u *ProxySubscriptionUpdateOne) SetNodeAllowContains(v []string) *ProxySubscriptionUpdateOne {
	_u.mutation.SetNodeAllowContains(v)
	return _u
}

// AppendNodeAllowContains appends value to the "node_allow_contains" field.
func (_u *ProxySubscriptionUpdateOne) AppendNodeAllowContains(v []string) *ProxySubscriptionUpdateOne {
	_u.mutation.AppendNodeAllowContains(v)
	return _u
}

// SetNodeIdentityAllowlist sets the "node_identity_allowlist" field.
func (_u *ProxySubscriptionUpdateOne) SetNodeIdentityAllowlist(v []string) *ProxySubscriptionUpdateOne {
	_u.mutation.SetNodeIdentityAllowlist(v)
	return _u
}

// AppendNodeIdentityAllowlist appends value to the "node_identity_allowlist" field.
func (_u *ProxySubscriptionUpdateOne) AppendNodeIdentityAllowlist(v []string) *ProxySubscriptionUpdateOne {
	_u.mutation.AppendNodeIdentityAllowlist(v)
	return _u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_u *ProxySubscriptionUpdateOne) SetLastSyncAt(v time.Time) *ProxySubscriptionUpdateOne {
	_u.mutation.SetLastSyncAt(v)
	return _u
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_u *ProxySubscriptionUpdateOne) SetNillableLastSyncAt(v *time.Time) *ProxySubscriptionUpdateOne {
	if v != nil {
		_u.SetLastSyncAt(*v)
	}
	return _u
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (_u *ProxySubscriptionUpdateOne) ClearLastSyncAt() *ProxySubscriptionUpdateOne {
	_u.mutation.ClearLastSyncAt()
	return _u
}

// SetLastSyncStatus sets the "last_sync_status" field.
func (_u *ProxySubscriptionUpdateOne) SetLastSyncStatus(v string) *ProxySubscriptionUpdateOne {
	_u.mutation.SetLastSyncStatus(v)
	return _u
}

// SetNillableLastSyncStatus sets the "last_sync_status" field if the given value is not nil.
func (_u *ProxySubscriptionUpdateOne) SetNillableLastSyncStatus(v *string) *ProxySubscriptionUpdateOne {
	if v != nil {
		_u.SetLastSyncStatus(*v)
	}
	return _u
}

// ClearLastSyncStatus clears the value of the "last_sync_status" field.
func (_u *ProxySubscriptionUpdateOne) ClearLastSyncStatus() *ProxySubscriptionUpdateOne {
	_u.mutation.ClearLastSyncStatus()
	return _u
}

// SetLastSyncError sets the "last_sync_error" field.
func (_u *ProxySubscriptionUpdateOne) SetLastSyncError(v string) *ProxySubscriptionUpdateOne {
	_u.mutation.SetLastSyncError(v)
	return _u
}

// SetNillableLastSyncError sets the "last_sync_error" field if the given value is not nil.
func (_u *ProxySubscriptionUpdateOne) SetNillableLastSyncError(v *string) *ProxySubscriptionUpdateOne {
	if v != nil {
		_u.SetLastSyncError(*v)
	}
	return _u
}

// ClearLastSyncError clears the value of the "last_sync_error" field.
func (_u *ProxySubscriptionUpdateOne) ClearLastSyncError() *ProxySubscriptionUpdateOne {
	_u.mutation.ClearLastSyncError()
	return _u
}

// SetLastConfigHash sets the "last_config_hash" field.
func (_u *ProxySubscriptionUpdateOne) SetLastConfigHash(v string) *ProxySubscriptionUpdateOne {
	_u.mutation.SetLastConfigHash(v)
	return _u
}

// SetNillableLastConfigHash sets the "last_config_hash" field if the given value is not nil.
func (_u *ProxySubscriptionUpdateOne) SetNillableLastConfigHash(v *string) *ProxySubscriptionUpdateOne {
	if v != nil {
		_u.SetLastConfigHash(*v)
	}
	return _u
}

// ClearLastConfigHash clears the value of the "last_config_hash" field.
func (_u *ProxySubscriptionUpdateOne) ClearLastConfigHash() *ProxySubscriptionUpdateOne {
	_u.mutation.ClearLastConfigHash()
	return _u
}

// SetDesiredCount sets the "desired_count" field.
func (_u *ProxySubscriptionUpdateOne) SetDesiredCount(v int) *ProxySubscriptionUpdateOne {
	_u.mutation.ResetDesiredCount()
	_u.mutation.SetDesiredCount(v)
	return _u
}

// SetNillableDesiredCount sets the "desired_count" field if the given value is not nil.
func (_u *ProxySubscriptionUpdateOne) SetNillableDesiredCount(v *int) *ProxySubscriptionUpdateOne {
	if v != nil {
		_u.SetDesiredCount(*v)
	}
	return _u
}

// AddDesiredCount adds value to the "desired_count" field.
func (_u *ProxySubscriptionUpdateOne) AddDesiredCount(v int) *ProxySubscriptionUpdateOne {
	_u.mutation.AddDesiredCount(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ProxySubscriptionUpdateOne) SetCreatedBy(v int64) *ProxySubscriptionUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ProxySubscriptionUpdateOne) SetNillableCreatedBy(v *int64) *ProxySubscriptionUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ProxySubscriptionUpdateOne) AddCreatedBy(v int64) *ProxySubscriptionUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ProxySubscriptionUpdateOne) ClearCreatedBy() *ProxySubscriptionUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetNextDueAt sets the "next_due_at" field.
func (_u *ProxySubscriptionUpdateOne) SetNextDueAt(v time.Time) *ProxySubscriptionUpdateOne {
	_u.mutation.SetNextDueAt(v)
	return _u
}

// SetNillableNextDueAt sets the "next_due_at" field if the given value is not nil.
func (_u *ProxySubscriptionUpdateOne) SetNillableNextDueAt(v *time.Time) *ProxySubscriptionUpdateOne {
	if v != nil {
		_u.SetNextDueAt(*v)
	}
	return _u
}

// ClearNextDueAt clears the value of the "next_due_at" field.
func (_u *ProxySubscriptionUpdateOne) ClearNextDueAt() *ProxySubscriptionUpdateOne {
	_u.mutation.ClearNextDueAt()
	return _u
}

// Mutation returns the ProxySubscriptionMutation object of the builder.
func (_u *ProxySubscriptionUpdateOne) Mutation() *ProxySubscriptionMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProxySubscriptionUpdate builder.
func (_u *ProxySubscriptionUpdateOne) Where(ps ...predicate.ProxySubscription) *ProxySubscriptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxySubscriptionUpdateOne) Select(field string, fields ...string) *ProxySubscriptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProxySubscription entity.
func (_u *ProxySubscriptionUpdateOne) Save(ctx context.Context) (*ProxySubscription, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxySubscriptionUpdateOne) SaveX(ctx context.Context) *ProxySubscription {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxySubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxySubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxySubscriptionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxysubscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxySubscriptionUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxysubscription.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := proxysubscription.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubscriptionURL(); ok {
		if err := proxysubscription.SubscriptionURLValidator(v); err != nil {
			return &ValidationError{Name: "subscription_url", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.subscription_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NamePrefix(); ok {
		if err := proxysubscription.NamePrefixValidator(v); err != nil {
			return &ValidationError{Name: "name_prefix", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.name_prefix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Protocol(); ok {
		if err := proxysubscription.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BindAddress(); ok {
		if err := proxysubscription.BindAddressValidator(v); err != nil {
			return &ValidationError{Name: "bind_address", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.bind_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastSyncStatus(); ok {
		if err := proxysubscription.LastSyncStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_sync_status", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.last_sync_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastConfigHash(); ok {
		if err := proxysubscription.LastConfigHashValidator(v); err != nil {
			return &ValidationError{Name: "last_config_hash", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.last_config_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxySubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *ProxySubscription, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxysubscription.Table, proxysubscription.Columns, sqlgraph.NewFieldSpec(proxysubscription.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProxySubscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxysubscription.FieldID)
		for _, f := range fields {
			if !proxysubscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxysubscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxysubscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxysubscription.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(proxysubscription.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(proxysubscription.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubscriptionURL(); ok {
		_spec.SetField(proxysubscription.FieldSubscriptionURL, field.TypeString, value)
	}
	if _u.mutation.SubscriptionURLCleared() {
		_spec.ClearField(proxysubscription.FieldSubscriptionURL, field.TypeString)
	}
	if value, ok := _u.mutation.InlineBody(); ok {
		_spec.SetField(proxysubscription.FieldInlineBody, field.TypeString, value)
	}
	if _u.mutation.InlineBodyCleared() {
		_spec.ClearField(proxysubscription.FieldInlineBody, field.TypeString)
	}
	if value, ok := _u.mutation.NamePrefix(); ok {
		_spec.SetField(proxysubscription.FieldNamePrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(proxysubscription.FieldProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.BindAddress(); ok {
		_spec.SetField(proxysubscription.FieldBindAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.BasePort(); ok {
		_spec.SetField(proxysubscription.FieldBasePort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBasePort(); ok {
		_spec.AddField(proxysubscription.FieldBasePort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxPorts(); ok {
		_spec.SetField(proxysubscription.FieldMaxPorts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxPorts(); ok {
		_spec.AddField(proxysubscription.FieldMaxPorts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SyncIntervalSec(); ok {
		_spec.SetField(proxysubscription.FieldSyncIntervalSec, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSyncIntervalSec(); ok {
		_spec.AddField(proxysubscription.FieldSyncIntervalSec, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NodeAllowContains(); ok {
		_spec.SetField(proxysubscription.FieldNodeAllowContains, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedNodeAllowContains(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, proxysubscription.FieldNodeAllowContains, value)
		})
	}
	if value, ok := _u.mutation.NodeIdentityAllowlist(); ok {
		_spec.SetField(proxysubscription.FieldNodeIdentityAllowlist, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedNodeIdentityAllowlist(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, proxysubscription.FieldNodeIdentityAllowlist, value)
		})
	}
	if value, ok := _u.mutation.LastSyncAt(); ok {
		_spec.SetField(proxysubscription.FieldLastSyncAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncAtCleared() {
		_spec.ClearField(proxysubscription.FieldLastSyncAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSyncStatus(); ok {
		_spec.SetField(proxysubscription.FieldLastSyncStatus, field.TypeString, value)
	}
	if _u.mutation.LastSyncStatusCleared() {
		_spec.ClearField(proxysubscription.FieldLastSyncStatus, field.TypeString)
	}
	if value, ok := _u.mutation.LastSyncError(); ok {
		_spec.SetField(proxysubscription.FieldLastSyncError, field.TypeString, value)
	}
	if _u.mutation.LastSyncErrorCleared() {
		_spec.ClearField(proxysubscription.FieldLastSyncError, field.TypeString)
	}
	if value, ok := _u.mutation.LastConfigHash(); ok {
		_spec.SetField(proxysubscription.FieldLastConfigHash, field.TypeString, value)
	}
	if _u.mutation.LastConfigHashCleared() {
		_spec.ClearField(proxysubscription.FieldLastConfigHash, field.TypeString)
	}
	if value, ok := _u.mutation.DesiredCount(); ok {
		_spec.SetField(proxysubscription.FieldDesiredCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDesiredCount(); ok {
		_spec.AddField(proxysubscription.FieldDesiredCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(proxysubscription.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(proxysubscription.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(proxysubscription.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.NextDueAt(); ok {
		_spec.SetField(proxysubscription.FieldNextDueAt, field.TypeTime, value)
	}
	if _u.mutation.NextDueAtCleared() {
		_spec.ClearField(proxysubscription.FieldNextDueAt, field.TypeTime)
	}
	_node = &ProxySubscription{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxysubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
