// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/proxysubscription"
)

// ProxySubscription is the model entity for the ProxySubscription schema.
type ProxySubscription struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// url | inline
	SourceType string `json:"source_type,omitempty"`
	// Remote subscription URL (https preferred)
	SubscriptionURL string `json:"-"`
	// Inline subscription body (Clash YAML or share-link list / base64)
	InlineBody string `json:"-"`
	// Owned proxy name prefix; must start with sidecar-
	NamePrefix string `json:"name_prefix,omitempty"`
	// Protocol written to Sub2API proxies: socks5|http|https|socks5h
	Protocol string `json:"protocol,omitempty"`
	// BindAddress holds the value of the "bind_address" field.
	BindAddress string `json:"bind_address,omitempty"`
	// BasePort holds the value of the "base_port" field.
	BasePort int `json:"base_port,omitempty"`
	// MaxPorts holds the value of the "max_ports" field.
	MaxPorts int `json:"max_ports,omitempty"`
	// Per-source sync interval in seconds
	SyncIntervalSec int `json:"sync_interval_sec,omitempty"`
	// Optional node-name substring allowlist; fail-closed when non-empty
	NodeAllowContains []string `json:"node_allow_contains,omitempty"`
	// Optional exact node identity allowlist (type|server|port|name); fail-closed when non-empty
	NodeIdentityAllowlist []string `json:"node_identity_allowlist,omitempty"`
	// LastSyncAt holds the value of the "last_sync_at" field.
	LastSyncAt *time.Time `json:"last_sync_at,omitempty"`
	// LastSyncStatus holds the value of the "last_sync_status" field.
	LastSyncStatus string `json:"last_sync_status,omitempty"`
	// LastSyncError holds the value of the "last_sync_error" field.
	LastSyncError string `json:"last_sync_error,omitempty"`
	// LastConfigHash holds the value of the "last_config_hash" field.
	LastConfigHash string `json:"last_config_hash,omitempty"`
	// DesiredCount holds the value of the "desired_count" field.
	DesiredCount int `json:"desired_count,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int64 `json:"created_by,omitempty"`
	// Next scheduled sync time; nil means ASAP when enabled
	NextDueAt    *time.Time `json:"next_due_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProxySubscription) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case proxysubscription.FieldNodeAllowContains, proxysubscription.FieldNodeIdentityAllowlist:
			values[i] = new([]byte)
		case proxysubscription.FieldEnabled:
			values[i] = new(sql.NullBool)
		case proxysubscription.FieldID, proxysubscription.FieldBasePort, proxysubscription.FieldMaxPorts, proxysubscription.FieldSyncIntervalSec, proxysubscription.FieldDesiredCount, proxysubscription.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case proxysubscription.FieldName, proxysubscription.FieldSourceType, proxysubscription.FieldSubscriptionURL, proxysubscription.FieldInlineBody, proxysubscription.FieldNamePrefix, proxysubscription.FieldProtocol, proxysubscription.FieldBindAddress, proxysubscription.FieldLastSyncStatus, proxysubscription.FieldLastSyncError, proxysubscription.FieldLastConfigHash:
			values[i] = new(sql.NullString)
		case proxysubscription.FieldCreatedAt, proxysubscription.FieldUpdatedAt, proxysubscription.FieldLastSyncAt, proxysubscription.FieldNextDueAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProxySubscription fields.
func (_m *ProxySubscription) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case proxysubscription.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case proxysubscription.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case proxysubscription.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case proxysubscription.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case proxysubscription.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case proxysubscription.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				_m.SourceType = value.String
			}
		case proxysubscription.FieldSubscriptionURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_url", values[i])
			} else if value.Valid {
				_m.SubscriptionURL = value.String
			}
		case proxysubscription.FieldInlineBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field inline_body", values[i])
			} else if value.Valid {
				_m.InlineBody = value.String
			}
		case proxysubscription.FieldNamePrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name_prefix", values[i])
			} else if value.Valid {
				_m.NamePrefix = value.String
			}
		case proxysubscription.FieldProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field protocol", values[i])
			} else if value.Valid {
				_m.Protocol = value.String
			}
		case proxysubscription.FieldBindAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bind_address", values[i])
			} else if value.Valid {
				_m.BindAddress = value.String
			}
		case proxysubscription.FieldBasePort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field base_port", values[i])
			} else if value.Valid {
				_m.BasePort = int(value.Int64)
			}
		case proxysubscription.FieldMaxPorts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_ports", values[i])
			} else if value.Valid {
				_m.MaxPorts = int(value.Int64)
			}
		case proxysubscription.FieldSyncIntervalSec:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sync_interval_sec", values[i])
			} else if value.Valid {
				_m.SyncIntervalSec = int(value.Int64)
			}
		case proxysubscription.FieldNodeAllowContains:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field node_allow_contains", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.NodeAllowContains); err != nil {
					return fmt.Errorf("unmarshal field node_allow_contains: %w", err)
				}
			}
		case proxysubscription.FieldNodeIdentityAllowlist:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field node_identity_allowlist", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.NodeIdentityAllowlist); err != nil {
					return fmt.Errorf("unmarshal field node_identity_allowlist: %w", err)
				}
			}
		case proxysubscription.FieldLastSyncAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_sync_at", values[i])
			} else if value.Valid {
				_m.LastSyncAt = new(time.Time)
				*_m.LastSyncAt = value.Time
			}
		case proxysubscription.FieldLastSyncStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_sync_status", values[i])
			} else if value.Valid {
				_m.LastSyncStatus = value.String
			}
		case proxysubscription.FieldLastSyncError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_sync_error", values[i])
			} else if value.Valid {
				_m.LastSyncError = value.String
			}
		case proxysubscription.FieldLastConfigHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_config_hash", values[i])
			} else if value.Valid {
				_m.LastConfigHash = value.String
			}
		case proxysubscription.FieldDesiredCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field desired_count", values[i])
			} else if value.Valid {
				_m.DesiredCount = int(value.Int64)
			}
		case proxysubscription.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		case proxysubscription.FieldNextDueAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_due_at", values[i])
			} else if value.Valid {
				_m.NextDueAt = new(time.Time)
				*_m.NextDueAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProxySubscription.
// This includes values selected through modifiers, order, etc.
func (_m *ProxySubscription) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProxySubscription.
// Note that you need to call ProxySubscription.Unwrap() before calling this method if this ProxySubscription
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProxySubscription) Update() *ProxySubscriptionUpdateOne {
	return NewProxySubscriptionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProxySubscription entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProxySubscription) Unwrap() *ProxySubscription {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProxySubscription is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProxySubscription) String() string {
	var builder strings.Builder
	builder.WriteString("ProxySubscription(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("source_type=")
	builder.WriteString(_m.SourceType)
	builder.WriteString(", ")
	builder.WriteString("subscription_url=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("inline_body=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("name_prefix=")
	builder.WriteString(_m.NamePrefix)
	builder.WriteString(", ")
	builder.WriteString("protocol=")
	builder.WriteString(_m.Protocol)
	builder.WriteString(", ")
	builder.WriteString("bind_address=")
	builder.WriteString(_m.BindAddress)
	builder.WriteString(", ")
	builder.WriteString("base_port=")
	builder.WriteString(fmt.Sprintf("%v", _m.BasePort))
	builder.WriteString(", ")
	builder.WriteString("max_ports=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxPorts))
	builder.WriteString(", ")
	builder.WriteString("sync_interval_sec=")
	builder.WriteString(fmt.Sprintf("%v", _m.SyncIntervalSec))
	builder.WriteString(", ")
	builder.WriteString("node_allow_contains=")
	builder.WriteString(fmt.Sprintf("%v", _m.NodeAllowContains))
	builder.WriteString(", ")
	builder.WriteString("node_identity_allowlist=")
	builder.WriteString(fmt.Sprintf("%v", _m.NodeIdentityAllowlist))
	builder.WriteString(", ")
	if v := _m.LastSyncAt; v != nil {
		builder.WriteString("last_sync_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_sync_status=")
	builder.WriteString(_m.LastSyncStatus)
	builder.WriteString(", ")
	builder.WriteString("last_sync_error=")
	builder.WriteString(_m.LastSyncError)
	builder.WriteString(", ")
	builder.WriteString("last_config_hash=")
	builder.WriteString(_m.LastConfigHash)
	builder.WriteString(", ")
	builder.WriteString("desired_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.DesiredCount))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	if v := _m.NextDueAt; v != nil {
		builder.WriteString("next_due_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ProxySubscriptions is a parsable slice of ProxySubscription.
type ProxySubscriptions []*ProxySubscription
