// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/proxysubscription"
)

// ProxySubscriptionCreate is the builder for creating a ProxySubscription entity.
type ProxySubscriptionCreate struct {
	config
	mutation *ProxySubscriptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProxySubscriptionCreate) SetCreatedAt(v time.Time) *ProxySubscriptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProxySubscriptionCreate) SetNillableCreatedAt(v *time.Time) *ProxySubscriptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProxySubscriptionCreate) SetUpdatedAt(v time.Time) *ProxySubscriptionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProxySubscriptionCreate) SetNillableUpdatedAt(v *time.Time) *ProxySubscriptionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ProxySubscriptionCreate) SetName(v string) *ProxySubscriptionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ProxySubscriptionCreate) SetEnabled(v bool) *ProxySubscriptionCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ProxySubscriptionCreate) SetNillableEnabled(v *bool) *ProxySubscriptionCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetSourceType sets the "source_type" field.
func (_c *ProxySubscriptionCreate) SetSourceType(v string) *ProxySubscriptionCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_c *ProxySubscriptionCreate) SetNillableSourceType(v *string) *ProxySubscriptionCreate {
	if v != nil {
		_c.SetSourceType(*v)
	}
	return _c
}

// SetSubscriptionURL sets the "subscription_url" field.
func (_c *ProxySubscriptionCreate) SetSubscriptionURL(v string) *ProxySubscriptionCreate {
	_c.mutation.SetSubscriptionURL(v)
	return _c
}

// SetNillableSubscriptionURL sets the "subscription_url" field if the given value is not nil.
func (_c *ProxySubscriptionCreate) SetNillableSubscriptionURL(v *string) *ProxySubscriptionCreate {
	if v != nil {
		_c.SetSubscriptionURL(*v)
	}
	return _c
}

// SetInlineBody sets the "inline_body" field.
func (_c *ProxySubscriptionCreate) SetInlineBody(v string) *ProxySubscriptionCreate {
	_c.mutation.SetInlineBody(v)
	return _c
}

// SetNillableInlineBody sets the "inline_body" field if the given value is not nil.
func (_c *ProxySubscriptionCreate) SetNillableInlineBody(v *string) *ProxySubscriptionCreate {
	if v != nil {
		_c.SetInlineBody(*v)
	}
	return _c
}

// SetNamePrefix sets the "name_prefix" field.
func (_c *ProxySubscriptionCreate) SetNamePrefix(v string) *ProxySubscriptionCreate {
	_c.mutation.SetNamePrefix(v)
	return _c
}

// SetNillableNamePrefix sets the "name_prefix" field if the given value is not nil.
func (_c *ProxySubscriptionCreate) SetNillableNamePrefix(v *string) *ProxySubscriptionCreate {
	if v != nil {
		_c.SetNamePrefix(*v)
	}
	return _c
}

// SetProtocol sets the "protocol" field.
func (_c *ProxySubscriptionCreate) SetProtocol(v string) *ProxySubscriptionCreate {
	_c.mutation.SetProtocol(v)
	return _c
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_c *ProxySubscriptionCreate) SetNillableProtocol(v *string) *ProxySubscriptionCreate {
	if v != nil {
		_c.SetProtocol(*v)
	}
	return _c
}

// SetBindAddress sets the "bind_address" field.
func (_c *ProxySubscriptionCreate) SetBindAddress(v string) *ProxySubscriptionCreate {
	_c.mutation.SetBindAddress(v)
	return _c
}

// SetNillableBindAddress sets the "bind_address" field if the given value is not nil.
func (_c *ProxySubscriptionCreate) SetNillableBindAddress(v *string) *ProxySubscriptionCreate {
	if v != nil {
		_c.SetBindAddress(*v)
	}
	return _c
}

// SetBasePort sets the "base_port" field.
func (_c *ProxySubscriptionCreate) SetBasePort(v int) *ProxySubscriptionCreate {
	_c.mutation.SetBasePort(v)
	return _c
}

// SetNillableBasePort sets the "base_port" field if the given value is not nil.
func (_c *ProxySubscriptionCreate) SetNillableBasePort(v *int) *ProxySubscriptionCreate {
	if v != nil {
		_c.SetBasePort(*v)
	}
	return _c
}

// SetMaxPorts sets the "max_ports" field.
func (_c *ProxySubscriptionCreate) SetMaxPorts(v int) *ProxySubscriptionCreate {
	_c.mutation.SetMaxPorts(v)
	return _c
}

// SetNillableMaxPorts sets the "max_ports" field if the given value is not nil.
func (_c *ProxySubscriptionCreate) SetNillableMaxPorts(v *int) *ProxySubscriptionCreate {
	if v != nil {
		_c.SetMaxPorts(*v)
	}
	return _c
}

// SetSyncIntervalSec sets the "sync_interval_sec" field.
func (_c *ProxySubscriptionCreate) SetSyncIntervalSec(v int) *ProxySubscriptionCreate {
	_c.mutation.SetSyncIntervalSec(v)
	return _c
}

// SetNillableSyncIntervalSec sets the "sync_interval_sec" field if the given value is not nil.
func (_c *ProxySubscriptionCreate) SetNillableSyncIntervalSec(v *int) *ProxySubscriptionCreate {
	if v != nil {
		_c.SetSyncIntervalSec(*v)
	}
	return _c
}

// SetNodeAllowContains sets the "node_allow_contains" field.
func (_c *ProxySubscriptionCreate) SetNodeAllowContains(v []string) *ProxySubscriptionCreate {
	_c.mutation.SetNodeAllowContains(v)
	return _c
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_c *ProxySubscriptionCreate) SetLastSyncAt(v time.Time) *ProxySubscriptionCreate {
	_c.mutation.SetLastSyncAt(v)
	return _c
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_c *ProxySubscriptionCreate) SetNillableLastSyncAt(v *time.Time) *ProxySubscriptionCreate {
	if v != nil {
		_c.SetLastSyncAt(*v)
	}
	return _c
}

// SetLastSyncStatus sets the "last_sync_status" field.
func (_c *ProxySubscriptionCreate) SetLastSyncStatus(v string) *ProxySubscriptionCreate {
	_c.mutation.SetLastSyncStatus(v)
	return _c
}

// SetNillableLastSyncStatus sets the "last_sync_status" field if the given value is not nil.
func (_c *ProxySubscriptionCreate) SetNillableLastSyncStatus(v *string) *ProxySubscriptionCreate {
	if v != nil {
		_c.SetLastSyncStatus(*v)
	}
	return _c
}

// SetLastSyncError sets the "last_sync_error" field.
func (_c *ProxySubscriptionCreate) SetLastSyncError(v string) *ProxySubscriptionCreate {
	_c.mutation.SetLastSyncError(v)
	return _c
}

// SetNillableLastSyncError sets the "last_sync_error" field if the given value is not nil.
func (_c *ProxySubscriptionCreate) SetNillableLastSyncError(v *string) *ProxySubscriptionCreate {
	if v != nil {
		_c.SetLastSyncError(*v)
	}
	return _c
}

// SetLastConfigHash sets the "last_config_hash" field.
func (_c *ProxySubscriptionCreate) SetLastConfigHash(v string) *ProxySubscriptionCreate {
	_c.mutation.SetLastConfigHash(v)
	return _c
}

// SetNillableLastConfigHash sets the "last_config_hash" field if the given value is not nil.
func (_c *ProxySubscriptionCreate) SetNillableLastConfigHash(v *string) *ProxySubscriptionCreate {
	if v != nil {
		_c.SetLastConfigHash(*v)
	}
	return _c
}

// SetDesiredCount sets the "desired_count" field.
func (_c *ProxySubscriptionCreate) SetDesiredCount(v int) *ProxySubscriptionCreate {
	_c.mutation.SetDesiredCount(v)
	return _c
}

// SetNillableDesiredCount sets the "desired_count" field if the given value is not nil.
func (_c *ProxySubscriptionCreate) SetNillableDesiredCount(v *int) *ProxySubscriptionCreate {
	if v != nil {
		_c.SetDesiredCount(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ProxySubscriptionCreate) SetCreatedBy(v int64) *ProxySubscriptionCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *ProxySubscriptionCreate) SetNillableCreatedBy(v *int64) *ProxySubscriptionCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetNextDueAt sets the "next_due_at" field.
func (_c *ProxySubscriptionCreate) SetNextDueAt(v time.Time) *ProxySubscriptionCreate {
	_c.mutation.SetNextDueAt(v)
	return _c
}

// SetNillableNextDueAt sets the "next_due_at" field if the given value is not nil.
func (_c *ProxySubscriptionCreate) SetNillableNextDueAt(v *time.Time) *ProxySubscriptionCreate {
	if v != nil {
		_c.SetNextDueAt(*v)
	}
	return _c
}

// Mutation returns the ProxySubscriptionMutation object of the builder.
func (_c *ProxySubscriptionCreate) Mutation() *ProxySubscriptionMutation {
	return _c.mutation
}

// Save creates the ProxySubscription in the database.
func (_c *ProxySubscriptionCreate) Save(ctx context.Context) (*ProxySubscription, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProxySubscriptionCreate) SaveX(ctx context.Context) *ProxySubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxySubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxySubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProxySubscriptionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := proxysubscription.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := proxysubscription.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := proxysubscription.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		v := proxysubscription.DefaultSourceType
		_c.mutation.SetSourceType(v)
	}
	if _, ok := _c.mutation.SubscriptionURL(); !ok {
		v := proxysubscription.DefaultSubscriptionURL
		_c.mutation.SetSubscriptionURL(v)
	}
	if _, ok := _c.mutation.InlineBody(); !ok {
		v := proxysubscription.DefaultInlineBody
		_c.mutation.SetInlineBody(v)
	}
	if _, ok := _c.mutation.NamePrefix(); !ok {
		v := proxysubscription.DefaultNamePrefix
		_c.mutation.SetNamePrefix(v)
	}
	if _, ok := _c.mutation.Protocol(); !ok {
		v := proxysubscription.DefaultProtocol
		_c.mutation.SetProtocol(v)
	}
	if _, ok := _c.mutation.BindAddress(); !ok {
		v := proxysubscription.DefaultBindAddress
		_c.mutation.SetBindAddress(v)
	}
	if _, ok := _c.mutation.BasePort(); !ok {
		v := proxysubscription.DefaultBasePort
		_c.mutation.SetBasePort(v)
	}
	if _, ok := _c.mutation.MaxPorts(); !ok {
		v := proxysubscription.DefaultMaxPorts
		_c.mutation.SetMaxPorts(v)
	}
	if _, ok := _c.mutation.SyncIntervalSec(); !ok {
		v := proxysubscription.DefaultSyncIntervalSec
		_c.mutation.SetSyncIntervalSec(v)
	}
	if _, ok := _c.mutation.NodeAllowContains(); !ok {
		v := proxysubscription.DefaultNodeAllowContains
		_c.mutation.SetNodeAllowContains(v)
	}
	if _, ok := _c.mutation.LastSyncStatus(); !ok {
		v := proxysubscription.DefaultLastSyncStatus
		_c.mutation.SetLastSyncStatus(v)
	}
	if _, ok := _c.mutation.LastSyncError(); !ok {
		v := proxysubscription.DefaultLastSyncError
		_c.mutation.SetLastSyncError(v)
	}
	if _, ok := _c.mutation.LastConfigHash(); !ok {
		v := proxysubscription.DefaultLastConfigHash
		_c.mutation.SetLastConfigHash(v)
	}
	if _, ok := _c.mutation.DesiredCount(); !ok {
		v := proxysubscription.DefaultDesiredCount
		_c.mutation.SetDesiredCount(v)
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		v := proxysubscription.DefaultCreatedBy
		_c.mutation.SetCreatedBy(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProxySubscriptionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProxySubscription.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProxySubscription.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ProxySubscription.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := proxysubscription.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ProxySubscription.enabled"`)}
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New(`ent: missing required field "ProxySubscription.source_type"`)}
	}
	if v, ok := _c.mutation.SourceType(); ok {
		if err := proxysubscription.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.source_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SubscriptionURL(); ok {
		if err := proxysubscription.SubscriptionURLValidator(v); err != nil {
			return &ValidationError{Name: "subscription_url", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.subscription_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NamePrefix(); !ok {
		return &ValidationError{Name: "name_prefix", err: errors.New(`ent: missing required field "ProxySubscription.name_prefix"`)}
	}
	if v, ok := _c.mutation.NamePrefix(); ok {
		if err := proxysubscription.NamePrefixValidator(v); err != nil {
			return &ValidationError{Name: "name_prefix", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.name_prefix": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Protocol(); !ok {
		return &ValidationError{Name: "protocol", err: errors.New(`ent: missing required field "ProxySubscription.protocol"`)}
	}
	if v, ok := _c.mutation.Protocol(); ok {
		if err := proxysubscription.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.protocol": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BindAddress(); !ok {
		return &ValidationError{Name: "bind_address", err: errors.New(`ent: missing required field "ProxySubscription.bind_address"`)}
	}
	if v, ok := _c.mutation.BindAddress(); ok {
		if err := proxysubscription.BindAddressValidator(v); err != nil {
			return &ValidationError{Name: "bind_address", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.bind_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BasePort(); !ok {
		return &ValidationError{Name: "base_port", err: errors.New(`ent: missing required field "ProxySubscription.base_port"`)}
	}
	if _, ok := _c.mutation.MaxPorts(); !ok {
		return &ValidationError{Name: "max_ports", err: errors.New(`ent: missing required field "ProxySubscription.max_ports"`)}
	}
	if _, ok := _c.mutation.SyncIntervalSec(); !ok {
		return &ValidationError{Name: "sync_interval_sec", err: errors.New(`ent: missing required field "ProxySubscription.sync_interval_sec"`)}
	}
	if _, ok := _c.mutation.NodeAllowContains(); !ok {
		return &ValidationError{Name: "node_allow_contains", err: errors.New(`ent: missing required field "ProxySubscription.node_allow_contains"`)}
	}
	if v, ok := _c.mutation.LastSyncStatus(); ok {
		if err := proxysubscription.LastSyncStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_sync_status", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.last_sync_status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LastConfigHash(); ok {
		if err := proxysubscription.LastConfigHashValidator(v); err != nil {
			return &ValidationError{Name: "last_config_hash", err: fmt.Errorf(`ent: validator failed for field "ProxySubscription.last_config_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DesiredCount(); !ok {
		return &ValidationError{Name: "desired_count", err: errors.New(`ent: missing required field "ProxySubscription.desired_count"`)}
	}
	return nil
}

func (_c *ProxySubscriptionCreate) sqlSave(ctx context.Context) (*ProxySubscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProxySubscriptionCreate) createSpec() (*ProxySubscription, *sqlgraph.CreateSpec) {
	var (
		_node = &ProxySubscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(proxysubscription.Table, sqlgraph.NewFieldSpec(proxysubscription.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(proxysubscription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(proxysubscription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(proxysubscription.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(proxysubscription.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(proxysubscription.FieldSourceType, field.TypeString, value)
		_node.SourceType = value
	}
	if value, ok := _c.mutation.SubscriptionURL(); ok {
		_spec.SetField(proxysubscription.FieldSubscriptionURL, field.TypeString, value)
		_node.SubscriptionURL = value
	}
	if value, ok := _c.mutation.InlineBody(); ok {
		_spec.SetField(proxysubscription.FieldInlineBody, field.TypeString, value)
		_node.InlineBody = value
	}
	if value, ok := _c.mutation.NamePrefix(); ok {
		_spec.SetField(proxysubscription.FieldNamePrefix, field.TypeString, value)
		_node.NamePrefix = value
	}
	if value, ok := _c.mutation.Protocol(); ok {
		_spec.SetField(proxysubscription.FieldProtocol, field.TypeString, value)
		_node.Protocol = value
	}
	if value, ok := _c.mutation.BindAddress(); ok {
		_spec.SetField(proxysubscription.FieldBindAddress, field.TypeString, value)
		_node.BindAddress = value
	}
	if value, ok := _c.mutation.BasePort(); ok {
		_spec.SetField(proxysubscription.FieldBasePort, field.TypeInt, value)
		_node.BasePort = value
	}
	if value, ok := _c.mutation.MaxPorts(); ok {
		_spec.SetField(proxysubscription.FieldMaxPorts, field.TypeInt, value)
		_node.MaxPorts = value
	}
	if value, ok := _c.mutation.SyncIntervalSec(); ok {
		_spec.SetField(proxysubscription.FieldSyncIntervalSec, field.TypeInt, value)
		_node.SyncIntervalSec = value
	}
	if value, ok := _c.mutation.NodeAllowContains(); ok {
		_spec.SetField(proxysubscription.FieldNodeAllowContains, field.TypeJSON, value)
		_node.NodeAllowContains = value
	}
	if value, ok := _c.mutation.LastSyncAt(); ok {
		_spec.SetField(proxysubscription.FieldLastSyncAt, field.TypeTime, value)
		_node.LastSyncAt = &value
	}
	if value, ok := _c.mutation.LastSyncStatus(); ok {
		_spec.SetField(proxysubscription.FieldLastSyncStatus, field.TypeString, value)
		_node.LastSyncStatus = value
	}
	if value, ok := _c.mutation.LastSyncError(); ok {
		_spec.SetField(proxysubscription.FieldLastSyncError, field.TypeString, value)
		_node.LastSyncError = value
	}
	if value, ok := _c.mutation.LastConfigHash(); ok {
		_spec.SetField(proxysubscription.FieldLastConfigHash, field.TypeString, value)
		_node.LastConfigHash = value
	}
	if value, ok := _c.mutation.DesiredCount(); ok {
		_spec.SetField(proxysubscription.FieldDesiredCount, field.TypeInt, value)
		_node.DesiredCount = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(proxysubscription.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.NextDueAt(); ok {
		_spec.SetField(proxysubscription.FieldNextDueAt, field.TypeTime, value)
		_node.NextDueAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxySubscription.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxySubscriptionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxySubscriptionCreate) OnConflict(opts ...sql.ConflictOption) *ProxySubscriptionUpsertOne {
	_c.conflict = opts
	return &ProxySubscriptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxySubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxySubscriptionCreate) OnConflictColumns(columns ...string) *ProxySubscriptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxySubscriptionUpsertOne{
		create: _c,
	}
}

type (
	// ProxySubscriptionUpsertOne is the builder for "upsert"-ing
	//  one ProxySubscription node.
	ProxySubscriptionUpsertOne struct {
		create *ProxySubscriptionCreate
	}

	// ProxySubscriptionUpsert is the "OnConflict" setter.
	ProxySubscriptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxySubscriptionUpsert) SetUpdatedAt(v time.Time) *ProxySubscriptionUpsert {
	u.Set(proxysubscription.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxySubscriptionUpsert) UpdateUpdatedAt() *ProxySubscriptionUpsert {
	u.SetExcluded(proxysubscription.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *ProxySubscriptionUpsert) SetName(v string) *ProxySubscriptionUpsert {
	u.Set(proxysubscription.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProxySubscriptionUpsert) UpdateName() *ProxySubscriptionUpsert {
	u.SetExcluded(proxysubscription.FieldName)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *ProxySubscriptionUpsert) SetEnabled(v bool) *ProxySubscriptionUpsert {
	u.Set(proxysubscription.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ProxySubscriptionUpsert) UpdateEnabled() *ProxySubscriptionUpsert {
	u.SetExcluded(proxysubscription.FieldEnabled)
	return u
}

// SetSourceType sets the "source_type" field.
func (u *ProxySubscriptionUpsert) SetSourceType(v string) *ProxySubscriptionUpsert {
	u.Set(proxysubscription.FieldSourceType, v)
	return u
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *ProxySubscriptionUpsert) UpdateSourceType() *ProxySubscriptionUpsert {
	u.SetExcluded(proxysubscription.FieldSourceType)
	return u
}

// SetSubscriptionURL sets the "subscription_url" field.
func (u *ProxySubscriptionUpsert) SetSubscriptionURL(v string) *ProxySubscriptionUpsert {
	u.Set(proxysubscription.FieldSubscriptionURL, v)
	return u
}

// UpdateSubscriptionURL sets the "subscription_url" field to the value that was provided on create.
func (u *ProxySubscriptionUpsert) UpdateSubscriptionURL() *ProxySubscriptionUpsert {
	u.SetExcluded(proxysubscription.FieldSubscriptionURL)
	return u
}

// ClearSubscriptionURL clears the value of the "subscription_url" field.
func (u *ProxySubscriptionUpsert) ClearSubscriptionURL() *ProxySubscriptionUpsert {
	u.SetNull(proxysubscription.FieldSubscriptionURL)
	return u
}

// SetInlineBody sets the "inline_body" field.
func (u *ProxySubscriptionUpsert) SetInlineBody(v string) *ProxySubscriptionUpsert {
	u.Set(proxysubscription.FieldInlineBody, v)
	return u
}

// UpdateInlineBody sets the "inline_body" field to the value that was provided on create.
func (u *ProxySubscriptionUpsert) UpdateInlineBody() *ProxySubscriptionUpsert {
	u.SetExcluded(proxysubscription.FieldInlineBody)
	return u
}

// ClearInlineBody clears the value of the "inline_body" field.
func (u *ProxySubscriptionUpsert) ClearInlineBody() *ProxySubscriptionUpsert {
	u.SetNull(proxysubscription.FieldInlineBody)
	return u
}

// SetNamePrefix sets the "name_prefix" field.
func (u *ProxySubscriptionUpsert) SetNamePrefix(v string) *ProxySubscriptionUpsert {
	u.Set(proxysubscription.FieldNamePrefix, v)
	return u
}

// UpdateNamePrefix sets the "name_prefix" field to the value that was provided on create.
func (u *ProxySubscriptionUpsert) UpdateNamePrefix() *ProxySubscriptionUpsert {
	u.SetExcluded(proxysubscription.FieldNamePrefix)
	return u
}

// SetProtocol sets the "protocol" field.
func (u *ProxySubscriptionUpsert) SetProtocol(v string) *ProxySubscriptionUpsert {
	u.Set(proxysubscription.FieldProtocol, v)
	return u
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *ProxySubscriptionUpsert) UpdateProtocol() *ProxySubscriptionUpsert {
	u.SetExcluded(proxysubscription.FieldProtocol)
	return u
}

// SetBindAddress sets the "bind_address" field.
func (u *ProxySubscriptionUpsert) SetBindAddress(v string) *ProxySubscriptionUpsert {
	u.Set(proxysubscription.FieldBindAddress, v)
	return u
}

// UpdateBindAddress sets the "bind_address" field to the value that was provided on create.
func (u *ProxySubscriptionUpsert) UpdateBindAddress() *ProxySubscriptionUpsert {
	u.SetExcluded(proxysubscription.FieldBindAddress)
	return u
}

// SetBasePort sets the "base_port" field.
func (u *ProxySubscriptionUpsert) SetBasePort(v int) *ProxySubscriptionUpsert {
	u.Set(proxysubscription.FieldBasePort, v)
	return u
}

// UpdateBasePort sets the "base_port" field to the value that was provided on create.
func (u *ProxySubscriptionUpsert) UpdateBasePort() *ProxySubscriptionUpsert {
	u.SetExcluded(proxysubscription.FieldBasePort)
	return u
}

// AddBasePort adds v to the "base_port" field.
func (u *ProxySubscriptionUpsert) AddBasePort(v int) *ProxySubscriptionUpsert {
	u.Add(proxysubscription.FieldBasePort, v)
	return u
}

// SetMaxPorts sets the "max_ports" field.
func (u *ProxySubscriptionUpsert) SetMaxPorts(v int) *ProxySubscriptionUpsert {
	u.Set(proxysubscription.FieldMaxPorts, v)
	return u
}

// UpdateMaxPorts sets the "max_ports" field to the value that was provided on create.
func (u *ProxySubscriptionUpsert) UpdateMaxPorts() *ProxySubscriptionUpsert {
	u.SetExcluded(proxysubscription.FieldMaxPorts)
	return u
}

// AddMaxPorts adds v to the "max_ports" field.
func (u *ProxySubscriptionUpsert) AddMaxPorts(v int) *ProxySubscriptionUpsert {
	u.Add(proxysubscription.FieldMaxPorts, v)
	return u
}

// SetSyncIntervalSec sets the "sync_interval_sec" field.
func (u *ProxySubscriptionUpsert) SetSyncIntervalSec(v int) *ProxySubscriptionUpsert {
	u.Set(proxysubscription.FieldSyncIntervalSec, v)
	return u
}

// UpdateSyncIntervalSec sets the "sync_interval_sec" field to the value that was provided on create.
func (u *ProxySubscriptionUpsert) UpdateSyncIntervalSec() *ProxySubscriptionUpsert {
	u.SetExcluded(proxysubscription.FieldSyncIntervalSec)
	return u
}

// AddSyncIntervalSec adds v to the "sync_interval_sec" field.
func (u *ProxySubscriptionUpsert) AddSyncIntervalSec(v int) *ProxySubscriptionUpsert {
	u.Add(proxysubscription.FieldSyncIntervalSec, v)
	return u
}

// SetNodeAllowContains sets the "node_allow_contains" field.
func (u *ProxySubscriptionUpsert) SetNodeAllowContains(v []string) *ProxySubscriptionUpsert {
	u.Set(proxysubscription.FieldNodeAllowContains, v)
	return u
}

// UpdateNodeAllowContains sets the "node_allow_contains" field to the value that was provided on create.
func (u *ProxySubscriptionUpsert) UpdateNodeAllowContains() *ProxySubscriptionUpsert {
	u.SetExcluded(proxysubscription.FieldNodeAllowContains)
	return u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (u *ProxySubscriptionUpsert) SetLastSyncAt(v time.Time) *ProxySubscriptionUpsert {
	u.Set(proxysubscription.FieldLastSyncAt, v)
	return u
}

// UpdateLastSyncAt sets the "last_sync_at" field to the value that was provided on create.
func (u *ProxySubscriptionUpsert) UpdateLastSyncAt() *ProxySubscriptionUpsert {
	u.SetExcluded(proxysubscription.FieldLastSyncAt)
	return u
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (u *ProxySubscriptionUpsert) ClearLastSyncAt() *ProxySubscriptionUpsert {
	u.SetNull(proxysubscription.FieldLastSyncAt)
	return u
}

// SetLastSyncStatus sets the "last_sync_status" field.
func (u *ProxySubscriptionUpsert) SetLastSyncStatus(v string) *ProxySubscriptionUpsert {
	u.Set(proxysubscription.FieldLastSyncStatus, v)
	return u
}

// UpdateLastSyncStatus sets the "last_sync_status" field to the value that was provided on create.
func (u *ProxySubscriptionUpsert) UpdateLastSyncStatus() *ProxySubscriptionUpsert {
	u.SetExcluded(proxysubscription.FieldLastSyncStatus)
	return u
}

// ClearLastSyncStatus clears the value of the "last_sync_status" field.
func (u *ProxySubscriptionUpsert) ClearLastSyncStatus() *ProxySubscriptionUpsert {
	u.SetNull(proxysubscription.FieldLastSyncStatus)
	return u
}

// SetLastSyncError sets the "last_sync_error" field.
func (u *ProxySubscriptionUpsert) SetLastSyncError(v string) *ProxySubscriptionUpsert {
	u.Set(proxysubscription.FieldLastSyncError, v)
	return u
}

// UpdateLastSyncError sets the "last_sync_error" field to the value that was provided on create.
func (u *ProxySubscriptionUpsert) UpdateLastSyncError() *ProxySubscriptionUpsert {
	u.SetExcluded(proxysubscription.FieldLastSyncError)
	return u
}

// ClearLastSyncError clears the value of the "last_sync_error" field.
func (u *ProxySubscriptionUpsert) ClearLastSyncError() *ProxySubscriptionUpsert {
	u.SetNull(proxysubscription.FieldLastSyncError)
	return u
}

// SetLastConfigHash sets the "last_config_hash" field.
func (u *ProxySubscriptionUpsert) SetLastConfigHash(v string) *ProxySubscriptionUpsert {
	u.Set(proxysubscription.FieldLastConfigHash, v)
	return u
}

// UpdateLastConfigHash sets the "last_config_hash" field to the value that was provided on create.
func (u *ProxySubscriptionUpsert) UpdateLastConfigHash() *ProxySubscriptionUpsert {
	u.SetExcluded(proxysubscription.FieldLastConfigHash)
	return u
}

// ClearLastConfigHash clears the value of the "last_config_hash" field.
func (u *ProxySubscriptionUpsert) ClearLastConfigHash() *ProxySubscriptionUpsert {
	u.SetNull(proxysubscription.FieldLastConfigHash)
	return u
}

// SetDesiredCount sets the "desired_count" field.
func (u *ProxySubscriptionUpsert) SetDesiredCount(v int) *ProxySubscriptionUpsert {
	u.Set(proxysubscription.FieldDesiredCount, v)
	return u
}

// UpdateDesiredCount sets the "desired_count" field to the value that was provided on create.
func (u *ProxySubscriptionUpsert) UpdateDesiredCount() *ProxySubscriptionUpsert {
	u.SetExcluded(proxysubscription.FieldDesiredCount)
	return u
}

// AddDesiredCount adds v to the "desired_count" field.
func (u *ProxySubscriptionUpsert) AddDesiredCount(v int) *ProxySubscriptionUpsert {
	u.Add(proxysubscription.FieldDesiredCount, v)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *ProxySubscriptionUpsert) SetCreatedBy(v int64) *ProxySubscriptionUpsert {
	u.Set(proxysubscription.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ProxySubscriptionUpsert) UpdateCreatedBy() *ProxySubscriptionUpsert {
	u.SetExcluded(proxysubscription.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ProxySubscriptionUpsert) AddCreatedBy(v int64) *ProxySubscriptionUpsert {
	u.Add(proxysubscription.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ProxySubscriptionUpsert) ClearCreatedBy() *ProxySubscriptionUpsert {
	u.SetNull(proxysubscription.FieldCreatedBy)
	return u
}

// SetNextDueAt sets the "next_due_at" field.
func (u *ProxySubscriptionUpsert) SetNextDueAt(v time.Time) *ProxySubscriptionUpsert {
	u.Set(proxysubscription.FieldNextDueAt, v)
	return u
}

// UpdateNextDueAt sets the "next_due_at" field to the value that was provided on create.
func (u *ProxySubscriptionUpsert) UpdateNextDueAt() *ProxySubscriptionUpsert {
	u.SetExcluded(proxysubscription.FieldNextDueAt)
	return u
}

// ClearNextDueAt clears the value of the "next_due_at" field.
func (u *ProxySubscriptionUpsert) ClearNextDueAt() *ProxySubscriptionUpsert {
	u.SetNull(proxysubscription.FieldNextDueAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ProxySubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxySubscriptionUpsertOne) UpdateNewValues() *ProxySubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(proxysubscription.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxySubscription.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProxySubscriptionUpsertOne) Ignore() *ProxySubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxySubscriptionUpsertOne) DoNothing() *ProxySubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxySubscriptionCreate.OnConflict
// documentation for more info.
func (u *ProxySubscriptionUpsertOne) Update(set func(*ProxySubscriptionUpsert)) *ProxySubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxySubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxySubscriptionUpsertOne) SetUpdatedAt(v time.Time) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertOne) UpdateUpdatedAt() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *ProxySubscriptionUpsertOne) SetName(v string) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertOne) UpdateName() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateName()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ProxySubscriptionUpsertOne) SetEnabled(v bool) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertOne) UpdateEnabled() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateEnabled()
	})
}

// SetSourceType sets the "source_type" field.
func (u *ProxySubscriptionUpsertOne) SetSourceType(v string) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertOne) UpdateSourceType() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateSourceType()
	})
}

// SetSubscriptionURL sets the "subscription_url" field.
func (u *ProxySubscriptionUpsertOne) SetSubscriptionURL(v string) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetSubscriptionURL(v)
	})
}

// UpdateSubscriptionURL sets the "subscription_url" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertOne) UpdateSubscriptionURL() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateSubscriptionURL()
	})
}

// ClearSubscriptionURL clears the value of the "subscription_url" field.
func (u *ProxySubscriptionUpsertOne) ClearSubscriptionURL() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.ClearSubscriptionURL()
	})
}

// SetInlineBody sets the "inline_body" field.
func (u *ProxySubscriptionUpsertOne) SetInlineBody(v string) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetInlineBody(v)
	})
}

// UpdateInlineBody sets the "inline_body" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertOne) UpdateInlineBody() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateInlineBody()
	})
}

// ClearInlineBody clears the value of the "inline_body" field.
func (u *ProxySubscriptionUpsertOne) ClearInlineBody() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.ClearInlineBody()
	})
}

// SetNamePrefix sets the "name_prefix" field.
func (u *ProxySubscriptionUpsertOne) SetNamePrefix(v string) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetNamePrefix(v)
	})
}

// UpdateNamePrefix sets the "name_prefix" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertOne) UpdateNamePrefix() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateNamePrefix()
	})
}

// SetProtocol sets the "protocol" field.
func (u *ProxySubscriptionUpsertOne) SetProtocol(v string) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetProtocol(v)
	})
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertOne) UpdateProtocol() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateProtocol()
	})
}

// SetBindAddress sets the "bind_address" field.
func (u *ProxySubscriptionUpsertOne) SetBindAddress(v string) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetBindAddress(v)
	})
}

// UpdateBindAddress sets the "bind_address" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertOne) UpdateBindAddress() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateBindAddress()
	})
}

// SetBasePort sets the "base_port" field.
func (u *ProxySubscriptionUpsertOne) SetBasePort(v int) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetBasePort(v)
	})
}

// AddBasePort adds v to the "base_port" field.
func (u *ProxySubscriptionUpsertOne) AddBasePort(v int) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.AddBasePort(v)
	})
}

// UpdateBasePort sets the "base_port" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertOne) UpdateBasePort() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateBasePort()
	})
}

// SetMaxPorts sets the "max_ports" field.
func (u *ProxySubscriptionUpsertOne) SetMaxPorts(v int) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetMaxPorts(v)
	})
}

// AddMaxPorts adds v to the "max_ports" field.
func (u *ProxySubscriptionUpsertOne) AddMaxPorts(v int) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.AddMaxPorts(v)
	})
}

// UpdateMaxPorts sets the "max_ports" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertOne) UpdateMaxPorts() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateMaxPorts()
	})
}

// SetSyncIntervalSec sets the "sync_interval_sec" field.
func (u *ProxySubscriptionUpsertOne) SetSyncIntervalSec(v int) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetSyncIntervalSec(v)
	})
}

// AddSyncIntervalSec adds v to the "sync_interval_sec" field.
func (u *ProxySubscriptionUpsertOne) AddSyncIntervalSec(v int) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.AddSyncIntervalSec(v)
	})
}

// UpdateSyncIntervalSec sets the "sync_interval_sec" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertOne) UpdateSyncIntervalSec() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateSyncIntervalSec()
	})
}

// SetNodeAllowContains sets the "node_allow_contains" field.
func (u *ProxySubscriptionUpsertOne) SetNodeAllowContains(v []string) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetNodeAllowContains(v)
	})
}

// UpdateNodeAllowContains sets the "node_allow_contains" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertOne) UpdateNodeAllowContains() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateNodeAllowContains()
	})
}

// SetLastSyncAt sets the "last_sync_at" field.
func (u *ProxySubscriptionUpsertOne) SetLastSyncAt(v time.Time) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetLastSyncAt(v)
	})
}

// UpdateLastSyncAt sets the "last_sync_at" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertOne) UpdateLastSyncAt() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateLastSyncAt()
	})
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (u *ProxySubscriptionUpsertOne) ClearLastSyncAt() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.ClearLastSyncAt()
	})
}

// SetLastSyncStatus sets the "last_sync_status" field.
func (u *ProxySubscriptionUpsertOne) SetLastSyncStatus(v string) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetLastSyncStatus(v)
	})
}

// UpdateLastSyncStatus sets the "last_sync_status" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertOne) UpdateLastSyncStatus() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateLastSyncStatus()
	})
}

// ClearLastSyncStatus clears the value of the "last_sync_status" field.
func (u *ProxySubscriptionUpsertOne) ClearLastSyncStatus() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.ClearLastSyncStatus()
	})
}

// SetLastSyncError sets the "last_sync_error" field.
func (u *ProxySubscriptionUpsertOne) SetLastSyncError(v string) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetLastSyncError(v)
	})
}

// UpdateLastSyncError sets the "last_sync_error" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertOne) UpdateLastSyncError() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateLastSyncError()
	})
}

// ClearLastSyncError clears the value of the "last_sync_error" field.
func (u *ProxySubscriptionUpsertOne) ClearLastSyncError() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.ClearLastSyncError()
	})
}

// SetLastConfigHash sets the "last_config_hash" field.
func (u *ProxySubscriptionUpsertOne) SetLastConfigHash(v string) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetLastConfigHash(v)
	})
}

// UpdateLastConfigHash sets the "last_config_hash" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertOne) UpdateLastConfigHash() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateLastConfigHash()
	})
}

// ClearLastConfigHash clears the value of the "last_config_hash" field.
func (u *ProxySubscriptionUpsertOne) ClearLastConfigHash() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.ClearLastConfigHash()
	})
}

// SetDesiredCount sets the "desired_count" field.
func (u *ProxySubscriptionUpsertOne) SetDesiredCount(v int) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetDesiredCount(v)
	})
}

// AddDesiredCount adds v to the "desired_count" field.
func (u *ProxySubscriptionUpsertOne) AddDesiredCount(v int) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.AddDesiredCount(v)
	})
}

// UpdateDesiredCount sets the "desired_count" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertOne) UpdateDesiredCount() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateDesiredCount()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ProxySubscriptionUpsertOne) SetCreatedBy(v int64) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ProxySubscriptionUpsertOne) AddCreatedBy(v int64) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertOne) UpdateCreatedBy() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ProxySubscriptionUpsertOne) ClearCreatedBy() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.ClearCreatedBy()
	})
}

// SetNextDueAt sets the "next_due_at" field.
func (u *ProxySubscriptionUpsertOne) SetNextDueAt(v time.Time) *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetNextDueAt(v)
	})
}

// UpdateNextDueAt sets the "next_due_at" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertOne) UpdateNextDueAt() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateNextDueAt()
	})
}

// ClearNextDueAt clears the value of the "next_due_at" field.
func (u *ProxySubscriptionUpsertOne) ClearNextDueAt() *ProxySubscriptionUpsertOne {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.ClearNextDueAt()
	})
}

// Exec executes the query.
func (u *ProxySubscriptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxySubscriptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxySubscriptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProxySubscriptionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProxySubscriptionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProxySubscriptionCreateBulk is the builder for creating many ProxySubscription entities in bulk.
type ProxySubscriptionCreateBulk struct {
	config
	err      error
	builders []*ProxySubscriptionCreate
	conflict []sql.ConflictOption
}

// Save creates the ProxySubscription entities in the database.
func (_c *ProxySubscriptionCreateBulk) Save(ctx context.Context) ([]*ProxySubscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProxySubscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProxySubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProxySubscriptionCreateBulk) SaveX(ctx context.Context) []*ProxySubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxySubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxySubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxySubscription.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxySubscriptionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxySubscriptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProxySubscriptionUpsertBulk {
	_c.conflict = opts
	return &ProxySubscriptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxySubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxySubscriptionCreateBulk) OnConflictColumns(columns ...string) *ProxySubscriptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxySubscriptionUpsertBulk{
		create: _c,
	}
}

// ProxySubscriptionUpsertBulk is the builder for "upsert"-ing
// a bulk of ProxySubscription nodes.
type ProxySubscriptionUpsertBulk struct {
	create *ProxySubscriptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProxySubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxySubscriptionUpsertBulk) UpdateNewValues() *ProxySubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(proxysubscription.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxySubscription.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProxySubscriptionUpsertBulk) Ignore() *ProxySubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxySubscriptionUpsertBulk) DoNothing() *ProxySubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxySubscriptionCreateBulk.OnConflict
// documentation for more info.
func (u *ProxySubscriptionUpsertBulk) Update(set func(*ProxySubscriptionUpsert)) *ProxySubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxySubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxySubscriptionUpsertBulk) SetUpdatedAt(v time.Time) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertBulk) UpdateUpdatedAt() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *ProxySubscriptionUpsertBulk) SetName(v string) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertBulk) UpdateName() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateName()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ProxySubscriptionUpsertBulk) SetEnabled(v bool) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertBulk) UpdateEnabled() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateEnabled()
	})
}

// SetSourceType sets the "source_type" field.
func (u *ProxySubscriptionUpsertBulk) SetSourceType(v string) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertBulk) UpdateSourceType() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateSourceType()
	})
}

// SetSubscriptionURL sets the "subscription_url" field.
func (u *ProxySubscriptionUpsertBulk) SetSubscriptionURL(v string) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetSubscriptionURL(v)
	})
}

// UpdateSubscriptionURL sets the "subscription_url" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertBulk) UpdateSubscriptionURL() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateSubscriptionURL()
	})
}

// ClearSubscriptionURL clears the value of the "subscription_url" field.
func (u *ProxySubscriptionUpsertBulk) ClearSubscriptionURL() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.ClearSubscriptionURL()
	})
}

// SetInlineBody sets the "inline_body" field.
func (u *ProxySubscriptionUpsertBulk) SetInlineBody(v string) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetInlineBody(v)
	})
}

// UpdateInlineBody sets the "inline_body" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertBulk) UpdateInlineBody() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateInlineBody()
	})
}

// ClearInlineBody clears the value of the "inline_body" field.
func (u *ProxySubscriptionUpsertBulk) ClearInlineBody() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.ClearInlineBody()
	})
}

// SetNamePrefix sets the "name_prefix" field.
func (u *ProxySubscriptionUpsertBulk) SetNamePrefix(v string) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetNamePrefix(v)
	})
}

// UpdateNamePrefix sets the "name_prefix" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertBulk) UpdateNamePrefix() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateNamePrefix()
	})
}

// SetProtocol sets the "protocol" field.
func (u *ProxySubscriptionUpsertBulk) SetProtocol(v string) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetProtocol(v)
	})
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertBulk) UpdateProtocol() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateProtocol()
	})
}

// SetBindAddress sets the "bind_address" field.
func (u *ProxySubscriptionUpsertBulk) SetBindAddress(v string) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetBindAddress(v)
	})
}

// UpdateBindAddress sets the "bind_address" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertBulk) UpdateBindAddress() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateBindAddress()
	})
}

// SetBasePort sets the "base_port" field.
func (u *ProxySubscriptionUpsertBulk) SetBasePort(v int) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetBasePort(v)
	})
}

// AddBasePort adds v to the "base_port" field.
func (u *ProxySubscriptionUpsertBulk) AddBasePort(v int) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.AddBasePort(v)
	})
}

// UpdateBasePort sets the "base_port" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertBulk) UpdateBasePort() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateBasePort()
	})
}

// SetMaxPorts sets the "max_ports" field.
func (u *ProxySubscriptionUpsertBulk) SetMaxPorts(v int) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetMaxPorts(v)
	})
}

// AddMaxPorts adds v to the "max_ports" field.
func (u *ProxySubscriptionUpsertBulk) AddMaxPorts(v int) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.AddMaxPorts(v)
	})
}

// UpdateMaxPorts sets the "max_ports" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertBulk) UpdateMaxPorts() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateMaxPorts()
	})
}

// SetSyncIntervalSec sets the "sync_interval_sec" field.
func (u *ProxySubscriptionUpsertBulk) SetSyncIntervalSec(v int) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetSyncIntervalSec(v)
	})
}

// AddSyncIntervalSec adds v to the "sync_interval_sec" field.
func (u *ProxySubscriptionUpsertBulk) AddSyncIntervalSec(v int) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.AddSyncIntervalSec(v)
	})
}

// UpdateSyncIntervalSec sets the "sync_interval_sec" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertBulk) UpdateSyncIntervalSec() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateSyncIntervalSec()
	})
}

// SetNodeAllowContains sets the "node_allow_contains" field.
func (u *ProxySubscriptionUpsertBulk) SetNodeAllowContains(v []string) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetNodeAllowContains(v)
	})
}

// UpdateNodeAllowContains sets the "node_allow_contains" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertBulk) UpdateNodeAllowContains() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateNodeAllowContains()
	})
}

// SetLastSyncAt sets the "last_sync_at" field.
func (u *ProxySubscriptionUpsertBulk) SetLastSyncAt(v time.Time) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetLastSyncAt(v)
	})
}

// UpdateLastSyncAt sets the "last_sync_at" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertBulk) UpdateLastSyncAt() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateLastSyncAt()
	})
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (u *ProxySubscriptionUpsertBulk) ClearLastSyncAt() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.ClearLastSyncAt()
	})
}

// SetLastSyncStatus sets the "last_sync_status" field.
func (u *ProxySubscriptionUpsertBulk) SetLastSyncStatus(v string) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetLastSyncStatus(v)
	})
}

// UpdateLastSyncStatus sets the "last_sync_status" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertBulk) UpdateLastSyncStatus() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateLastSyncStatus()
	})
}

// ClearLastSyncStatus clears the value of the "last_sync_status" field.
func (u *ProxySubscriptionUpsertBulk) ClearLastSyncStatus() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.ClearLastSyncStatus()
	})
}

// SetLastSyncError sets the "last_sync_error" field.
func (u *ProxySubscriptionUpsertBulk) SetLastSyncError(v string) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetLastSyncError(v)
	})
}

// UpdateLastSyncError sets the "last_sync_error" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertBulk) UpdateLastSyncError() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateLastSyncError()
	})
}

// ClearLastSyncError clears the value of the "last_sync_error" field.
func (u *ProxySubscriptionUpsertBulk) ClearLastSyncError() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.ClearLastSyncError()
	})
}

// SetLastConfigHash sets the "last_config_hash" field.
func (u *ProxySubscriptionUpsertBulk) SetLastConfigHash(v string) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetLastConfigHash(v)
	})
}

// UpdateLastConfigHash sets the "last_config_hash" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertBulk) UpdateLastConfigHash() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateLastConfigHash()
	})
}

// ClearLastConfigHash clears the value of the "last_config_hash" field.
func (u *ProxySubscriptionUpsertBulk) ClearLastConfigHash() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.ClearLastConfigHash()
	})
}

// SetDesiredCount sets the "desired_count" field.
func (u *ProxySubscriptionUpsertBulk) SetDesiredCount(v int) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetDesiredCount(v)
	})
}

// AddDesiredCount adds v to the "desired_count" field.
func (u *ProxySubscriptionUpsertBulk) AddDesiredCount(v int) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.AddDesiredCount(v)
	})
}

// UpdateDesiredCount sets the "desired_count" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertBulk) UpdateDesiredCount() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateDesiredCount()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ProxySubscriptionUpsertBulk) SetCreatedBy(v int64) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ProxySubscriptionUpsertBulk) AddCreatedBy(v int64) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertBulk) UpdateCreatedBy() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ProxySubscriptionUpsertBulk) ClearCreatedBy() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.ClearCreatedBy()
	})
}

// SetNextDueAt sets the "next_due_at" field.
func (u *ProxySubscriptionUpsertBulk) SetNextDueAt(v time.Time) *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.SetNextDueAt(v)
	})
}

// UpdateNextDueAt sets the "next_due_at" field to the value that was provided on create.
func (u *ProxySubscriptionUpsertBulk) UpdateNextDueAt() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.UpdateNextDueAt()
	})
}

// ClearNextDueAt clears the value of the "next_due_at" field.
func (u *ProxySubscriptionUpsertBulk) ClearNextDueAt() *ProxySubscriptionUpsertBulk {
	return u.Update(func(s *ProxySubscriptionUpsert) {
		s.ClearNextDueAt()
	})
}

// Exec executes the query.
func (u *ProxySubscriptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProxySubscriptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxySubscriptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxySubscriptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
