// Code generated by ent, DO NOT EDIT.

package imbotchat

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldUpdatedAt, v))
}

// BotID applies equality check predicate on the "bot_id" field. It's identical to BotIDEQ.
func BotID(v int64) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldBotID, v))
}

// ChatID applies equality check predicate on the "chat_id" field. It's identical to ChatIDEQ.
func ChatID(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldChatID, v))
}

// PlatformUserID applies equality check predicate on the "platform_user_id" field. It's identical to PlatformUserIDEQ.
func PlatformUserID(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldPlatformUserID, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldDisplayName, v))
}

// SessionUUID applies equality check predicate on the "session_uuid" field. It's identical to SessionUUIDEQ.
func SessionUUID(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldSessionUUID, v))
}

// ModelOverride applies equality check predicate on the "model_override" field. It's identical to ModelOverrideEQ.
func ModelOverride(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldModelOverride, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldStatus, v))
}

// PairedAt applies equality check predicate on the "paired_at" field. It's identical to PairedAtEQ.
func PairedAt(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldPairedAt, v))
}

// LastMessageAt applies equality check predicate on the "last_message_at" field. It's identical to LastMessageAtEQ.
func LastMessageAt(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldLastMessageAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLTE(FieldUpdatedAt, v))
}

// BotIDEQ applies the EQ predicate on the "bot_id" field.
func BotIDEQ(v int64) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldBotID, v))
}

// BotIDNEQ applies the NEQ predicate on the "bot_id" field.
func BotIDNEQ(v int64) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNEQ(FieldBotID, v))
}

// BotIDIn applies the In predicate on the "bot_id" field.
func BotIDIn(vs ...int64) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldIn(FieldBotID, vs...))
}

// BotIDNotIn applies the NotIn predicate on the "bot_id" field.
func BotIDNotIn(vs ...int64) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNotIn(FieldBotID, vs...))
}

// ChatIDEQ applies the EQ predicate on the "chat_id" field.
func ChatIDEQ(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldChatID, v))
}

// ChatIDNEQ applies the NEQ predicate on the "chat_id" field.
func ChatIDNEQ(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNEQ(FieldChatID, v))
}

// ChatIDIn applies the In predicate on the "chat_id" field.
func ChatIDIn(vs ...string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldIn(FieldChatID, vs...))
}

// ChatIDNotIn applies the NotIn predicate on the "chat_id" field.
func ChatIDNotIn(vs ...string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNotIn(FieldChatID, vs...))
}

// ChatIDGT applies the GT predicate on the "chat_id" field.
func ChatIDGT(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGT(FieldChatID, v))
}

// ChatIDGTE applies the GTE predicate on the "chat_id" field.
func ChatIDGTE(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGTE(FieldChatID, v))
}

// ChatIDLT applies the LT predicate on the "chat_id" field.
func ChatIDLT(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLT(FieldChatID, v))
}

// ChatIDLTE applies the LTE predicate on the "chat_id" field.
func ChatIDLTE(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLTE(FieldChatID, v))
}

// ChatIDContains applies the Contains predicate on the "chat_id" field.
func ChatIDContains(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldContains(FieldChatID, v))
}

// ChatIDHasPrefix applies the HasPrefix predicate on the "chat_id" field.
func ChatIDHasPrefix(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldHasPrefix(FieldChatID, v))
}

// ChatIDHasSuffix applies the HasSuffix predicate on the "chat_id" field.
func ChatIDHasSuffix(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldHasSuffix(FieldChatID, v))
}

// ChatIDEqualFold applies the EqualFold predicate on the "chat_id" field.
func ChatIDEqualFold(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEqualFold(FieldChatID, v))
}

// ChatIDContainsFold applies the ContainsFold predicate on the "chat_id" field.
func ChatIDContainsFold(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldContainsFold(FieldChatID, v))
}

// PlatformUserIDEQ applies the EQ predicate on the "platform_user_id" field.
func PlatformUserIDEQ(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldPlatformUserID, v))
}

// PlatformUserIDNEQ applies the NEQ predicate on the "platform_user_id" field.
func PlatformUserIDNEQ(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNEQ(FieldPlatformUserID, v))
}

// PlatformUserIDIn applies the In predicate on the "platform_user_id" field.
func PlatformUserIDIn(vs ...string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldIn(FieldPlatformUserID, vs...))
}

// PlatformUserIDNotIn applies the NotIn predicate on the "platform_user_id" field.
func PlatformUserIDNotIn(vs ...string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNotIn(FieldPlatformUserID, vs...))
}

// PlatformUserIDGT applies the GT predicate on the "platform_user_id" field.
func PlatformUserIDGT(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGT(FieldPlatformUserID, v))
}

// PlatformUserIDGTE applies the GTE predicate on the "platform_user_id" field.
func PlatformUserIDGTE(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGTE(FieldPlatformUserID, v))
}

// PlatformUserIDLT applies the LT predicate on the "platform_user_id" field.
func PlatformUserIDLT(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLT(FieldPlatformUserID, v))
}

// PlatformUserIDLTE applies the LTE predicate on the "platform_user_id" field.
func PlatformUserIDLTE(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLTE(FieldPlatformUserID, v))
}

// PlatformUserIDContains applies the Contains predicate on the "platform_user_id" field.
func PlatformUserIDContains(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldContains(FieldPlatformUserID, v))
}

// PlatformUserIDHasPrefix applies the HasPrefix predicate on the "platform_user_id" field.
func PlatformUserIDHasPrefix(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldHasPrefix(FieldPlatformUserID, v))
}

// PlatformUserIDHasSuffix applies the HasSuffix predicate on the "platform_user_id" field.
func PlatformUserIDHasSuffix(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldHasSuffix(FieldPlatformUserID, v))
}

// PlatformUserIDEqualFold applies the EqualFold predicate on the "platform_user_id" field.
func PlatformUserIDEqualFold(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEqualFold(FieldPlatformUserID, v))
}

// PlatformUserIDContainsFold applies the ContainsFold predicate on the "platform_user_id" field.
func PlatformUserIDContainsFold(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldContainsFold(FieldPlatformUserID, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldContainsFold(FieldDisplayName, v))
}

// SessionUUIDEQ applies the EQ predicate on the "session_uuid" field.
func SessionUUIDEQ(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldSessionUUID, v))
}

// SessionUUIDNEQ applies the NEQ predicate on the "session_uuid" field.
func SessionUUIDNEQ(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNEQ(FieldSessionUUID, v))
}

// SessionUUIDIn applies the In predicate on the "session_uuid" field.
func SessionUUIDIn(vs ...string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldIn(FieldSessionUUID, vs...))
}

// SessionUUIDNotIn applies the NotIn predicate on the "session_uuid" field.
func SessionUUIDNotIn(vs ...string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNotIn(FieldSessionUUID, vs...))
}

// SessionUUIDGT applies the GT predicate on the "session_uuid" field.
func SessionUUIDGT(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGT(FieldSessionUUID, v))
}

// SessionUUIDGTE applies the GTE predicate on the "session_uuid" field.
func SessionUUIDGTE(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGTE(FieldSessionUUID, v))
}

// SessionUUIDLT applies the LT predicate on the "session_uuid" field.
func SessionUUIDLT(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLT(FieldSessionUUID, v))
}

// SessionUUIDLTE applies the LTE predicate on the "session_uuid" field.
func SessionUUIDLTE(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLTE(FieldSessionUUID, v))
}

// SessionUUIDContains applies the Contains predicate on the "session_uuid" field.
func SessionUUIDContains(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldContains(FieldSessionUUID, v))
}

// SessionUUIDHasPrefix applies the HasPrefix predicate on the "session_uuid" field.
func SessionUUIDHasPrefix(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldHasPrefix(FieldSessionUUID, v))
}

// SessionUUIDHasSuffix applies the HasSuffix predicate on the "session_uuid" field.
func SessionUUIDHasSuffix(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldHasSuffix(FieldSessionUUID, v))
}

// SessionUUIDEqualFold applies the EqualFold predicate on the "session_uuid" field.
func SessionUUIDEqualFold(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEqualFold(FieldSessionUUID, v))
}

// SessionUUIDContainsFold applies the ContainsFold predicate on the "session_uuid" field.
func SessionUUIDContainsFold(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldContainsFold(FieldSessionUUID, v))
}

// ModelOverrideEQ applies the EQ predicate on the "model_override" field.
func ModelOverrideEQ(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldModelOverride, v))
}

// ModelOverrideNEQ applies the NEQ predicate on the "model_override" field.
func ModelOverrideNEQ(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNEQ(FieldModelOverride, v))
}

// ModelOverrideIn applies the In predicate on the "model_override" field.
func ModelOverrideIn(vs ...string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldIn(FieldModelOverride, vs...))
}

// ModelOverrideNotIn applies the NotIn predicate on the "model_override" field.
func ModelOverrideNotIn(vs ...string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNotIn(FieldModelOverride, vs...))
}

// ModelOverrideGT applies the GT predicate on the "model_override" field.
func ModelOverrideGT(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGT(FieldModelOverride, v))
}

// ModelOverrideGTE applies the GTE predicate on the "model_override" field.
func ModelOverrideGTE(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGTE(FieldModelOverride, v))
}

// ModelOverrideLT applies the LT predicate on the "model_override" field.
func ModelOverrideLT(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLT(FieldModelOverride, v))
}

// ModelOverrideLTE applies the LTE predicate on the "model_override" field.
func ModelOverrideLTE(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLTE(FieldModelOverride, v))
}

// ModelOverrideContains applies the Contains predicate on the "model_override" field.
func ModelOverrideContains(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldContains(FieldModelOverride, v))
}

// ModelOverrideHasPrefix applies the HasPrefix predicate on the "model_override" field.
func ModelOverrideHasPrefix(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldHasPrefix(FieldModelOverride, v))
}

// ModelOverrideHasSuffix applies the HasSuffix predicate on the "model_override" field.
func ModelOverrideHasSuffix(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldHasSuffix(FieldModelOverride, v))
}

// ModelOverrideEqualFold applies the EqualFold predicate on the "model_override" field.
func ModelOverrideEqualFold(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEqualFold(FieldModelOverride, v))
}

// ModelOverrideContainsFold applies the ContainsFold predicate on the "model_override" field.
func ModelOverrideContainsFold(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldContainsFold(FieldModelOverride, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldContainsFold(FieldStatus, v))
}

// PairedAtEQ applies the EQ predicate on the "paired_at" field.
func PairedAtEQ(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldPairedAt, v))
}

// PairedAtNEQ applies the NEQ predicate on the "paired_at" field.
func PairedAtNEQ(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNEQ(FieldPairedAt, v))
}

// PairedAtIn applies the In predicate on the "paired_at" field.
func PairedAtIn(vs ...time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldIn(FieldPairedAt, vs...))
}

// PairedAtNotIn applies the NotIn predicate on the "paired_at" field.
func PairedAtNotIn(vs ...time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNotIn(FieldPairedAt, vs...))
}

// PairedAtGT applies the GT predicate on the "paired_at" field.
func PairedAtGT(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGT(FieldPairedAt, v))
}

// PairedAtGTE applies the GTE predicate on the "paired_at" field.
func PairedAtGTE(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGTE(FieldPairedAt, v))
}

// PairedAtLT applies the LT predicate on the "paired_at" field.
func PairedAtLT(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLT(FieldPairedAt, v))
}

// PairedAtLTE applies the LTE predicate on the "paired_at" field.
func PairedAtLTE(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLTE(FieldPairedAt, v))
}

// LastMessageAtEQ applies the EQ predicate on the "last_message_at" field.
func LastMessageAtEQ(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldEQ(FieldLastMessageAt, v))
}

// LastMessageAtNEQ applies the NEQ predicate on the "last_message_at" field.
func LastMessageAtNEQ(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNEQ(FieldLastMessageAt, v))
}

// LastMessageAtIn applies the In predicate on the "last_message_at" field.
func LastMessageAtIn(vs ...time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldIn(FieldLastMessageAt, vs...))
}

// LastMessageAtNotIn applies the NotIn predicate on the "last_message_at" field.
func LastMessageAtNotIn(vs ...time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNotIn(FieldLastMessageAt, vs...))
}

// LastMessageAtGT applies the GT predicate on the "last_message_at" field.
func LastMessageAtGT(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGT(FieldLastMessageAt, v))
}

// LastMessageAtGTE applies the GTE predicate on the "last_message_at" field.
func LastMessageAtGTE(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldGTE(FieldLastMessageAt, v))
}

// LastMessageAtLT applies the LT predicate on the "last_message_at" field.
func LastMessageAtLT(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLT(FieldLastMessageAt, v))
}

// LastMessageAtLTE applies the LTE predicate on the "last_message_at" field.
func LastMessageAtLTE(v time.Time) predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldLTE(FieldLastMessageAt, v))
}

// LastMessageAtIsNil applies the IsNil predicate on the "last_message_at" field.
func LastMessageAtIsNil() predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldIsNull(FieldLastMessageAt))
}

// LastMessageAtNotNil applies the NotNil predicate on the "last_message_at" field.
func LastMessageAtNotNil() predicate.IMBotChat {
	return predicate.IMBotChat(sql.FieldNotNull(FieldLastMessageAt))
}

// HasBot applies the HasEdge predicate on the "bot" edge.
func HasBot() predicate.IMBotChat {
	return predicate.IMBotChat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BotTable, BotColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBotWith applies the HasEdge predicate on the "bot" edge with a given conditions (other predicates).
func HasBotWith(preds ...predicate.IMBot) predicate.IMBotChat {
	return predicate.IMBotChat(func(s *sql.Selector) {
		step := newBotStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMessages applies the HasEdge predicate on the "messages" edge.
func HasMessages() predicate.IMBotChat {
	return predicate.IMBotChat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessagesWith applies the HasEdge predicate on the "messages" edge with a given conditions (other predicates).
func HasMessagesWith(preds ...predicate.IMBotMessage) predicate.IMBotChat {
	return predicate.IMBotChat(func(s *sql.Selector) {
		step := newMessagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IMBotChat) predicate.IMBotChat {
	return predicate.IMBotChat(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IMBotChat) predicate.IMBotChat {
	return predicate.IMBotChat(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IMBotChat) predicate.IMBotChat {
	return predicate.IMBotChat(sql.NotPredicates(p))
}
