// Code generated by ent, DO NOT EDIT.

package proxysubscription

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the proxysubscription type in the database.
	Label = "proxy_subscription"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldSourceType holds the string denoting the source_type field in the database.
	FieldSourceType = "source_type"
	// FieldSubscriptionURL holds the string denoting the subscription_url field in the database.
	FieldSubscriptionURL = "subscription_url"
	// FieldInlineBody holds the string denoting the inline_body field in the database.
	FieldInlineBody = "inline_body"
	// FieldNamePrefix holds the string denoting the name_prefix field in the database.
	FieldNamePrefix = "name_prefix"
	// FieldProtocol holds the string denoting the protocol field in the database.
	FieldProtocol = "protocol"
	// FieldBindAddress holds the string denoting the bind_address field in the database.
	FieldBindAddress = "bind_address"
	// FieldBasePort holds the string denoting the base_port field in the database.
	FieldBasePort = "base_port"
	// FieldMaxPorts holds the string denoting the max_ports field in the database.
	FieldMaxPorts = "max_ports"
	// FieldSyncIntervalSec holds the string denoting the sync_interval_sec field in the database.
	FieldSyncIntervalSec = "sync_interval_sec"
	// FieldNodeAllowContains holds the string denoting the node_allow_contains field in the database.
	FieldNodeAllowContains = "node_allow_contains"
	// FieldNodeIdentityAllowlist holds the string denoting the node_identity_allowlist field in the database.
	FieldNodeIdentityAllowlist = "node_identity_allowlist"
	// FieldLastSyncAt holds the string denoting the last_sync_at field in the database.
	FieldLastSyncAt = "last_sync_at"
	// FieldLastSyncStatus holds the string denoting the last_sync_status field in the database.
	FieldLastSyncStatus = "last_sync_status"
	// FieldLastSyncError holds the string denoting the last_sync_error field in the database.
	FieldLastSyncError = "last_sync_error"
	// FieldLastConfigHash holds the string denoting the last_config_hash field in the database.
	FieldLastConfigHash = "last_config_hash"
	// FieldDesiredCount holds the string denoting the desired_count field in the database.
	FieldDesiredCount = "desired_count"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldNextDueAt holds the string denoting the next_due_at field in the database.
	FieldNextDueAt = "next_due_at"
	// Table holds the table name of the proxysubscription in the database.
	Table = "proxy_subscriptions"
)

// Columns holds all SQL columns for proxysubscription fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldEnabled,
	FieldSourceType,
	FieldSubscriptionURL,
	FieldInlineBody,
	FieldNamePrefix,
	FieldProtocol,
	FieldBindAddress,
	FieldBasePort,
	FieldMaxPorts,
	FieldSyncIntervalSec,
	FieldNodeAllowContains,
	FieldNodeIdentityAllowlist,
	FieldLastSyncAt,
	FieldLastSyncStatus,
	FieldLastSyncError,
	FieldLastConfigHash,
	FieldDesiredCount,
	FieldCreatedBy,
	FieldNextDueAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultSourceType holds the default value on creation for the "source_type" field.
	DefaultSourceType string
	// SourceTypeValidator is a validator for the "source_type" field. It is called by the builders before save.
	SourceTypeValidator func(string) error
	// DefaultSubscriptionURL holds the default value on creation for the "subscription_url" field.
	DefaultSubscriptionURL string
	// SubscriptionURLValidator is a validator for the "subscription_url" field. It is called by the builders before save.
	SubscriptionURLValidator func(string) error
	// DefaultInlineBody holds the default value on creation for the "inline_body" field.
	DefaultInlineBody string
	// DefaultNamePrefix holds the default value on creation for the "name_prefix" field.
	DefaultNamePrefix string
	// NamePrefixValidator is a validator for the "name_prefix" field. It is called by the builders before save.
	NamePrefixValidator func(string) error
	// DefaultProtocol holds the default value on creation for the "protocol" field.
	DefaultProtocol string
	// ProtocolValidator is a validator for the "protocol" field. It is called by the builders before save.
	ProtocolValidator func(string) error
	// DefaultBindAddress holds the default value on creation for the "bind_address" field.
	DefaultBindAddress string
	// BindAddressValidator is a validator for the "bind_address" field. It is called by the builders before save.
	BindAddressValidator func(string) error
	// DefaultBasePort holds the default value on creation for the "base_port" field.
	DefaultBasePort int
	// DefaultMaxPorts holds the default value on creation for the "max_ports" field.
	DefaultMaxPorts int
	// DefaultSyncIntervalSec holds the default value on creation for the "sync_interval_sec" field.
	DefaultSyncIntervalSec int
	// DefaultNodeAllowContains holds the default value on creation for the "node_allow_contains" field.
	DefaultNodeAllowContains []string
	// DefaultNodeIdentityAllowlist holds the default value on creation for the "node_identity_allowlist" field.
	DefaultNodeIdentityAllowlist []string
	// DefaultLastSyncStatus holds the default value on creation for the "last_sync_status" field.
	DefaultLastSyncStatus string
	// LastSyncStatusValidator is a validator for the "last_sync_status" field. It is called by the builders before save.
	LastSyncStatusValidator func(string) error
	// DefaultLastSyncError holds the default value on creation for the "last_sync_error" field.
	DefaultLastSyncError string
	// DefaultLastConfigHash holds the default value on creation for the "last_config_hash" field.
	DefaultLastConfigHash string
	// LastConfigHashValidator is a validator for the "last_config_hash" field. It is called by the builders before save.
	LastConfigHashValidator func(string) error
	// DefaultDesiredCount holds the default value on creation for the "desired_count" field.
	DefaultDesiredCount int
	// DefaultCreatedBy holds the default value on creation for the "created_by" field.
	DefaultCreatedBy int64
)

// OrderOption defines the ordering options for the ProxySubscription queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// BySourceType orders the results by the source_type field.
func BySourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceType, opts...).ToFunc()
}

// BySubscriptionURL orders the results by the subscription_url field.
func BySubscriptionURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionURL, opts...).ToFunc()
}

// ByInlineBody orders the results by the inline_body field.
func ByInlineBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInlineBody, opts...).ToFunc()
}

// ByNamePrefix orders the results by the name_prefix field.
func ByNamePrefix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNamePrefix, opts...).ToFunc()
}

// ByProtocol orders the results by the protocol field.
func ByProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtocol, opts...).ToFunc()
}

// ByBindAddress orders the results by the bind_address field.
func ByBindAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBindAddress, opts...).ToFunc()
}

// ByBasePort orders the results by the base_port field.
func ByBasePort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBasePort, opts...).ToFunc()
}

// ByMaxPorts orders the results by the max_ports field.
func ByMaxPorts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxPorts, opts...).ToFunc()
}

// BySyncIntervalSec orders the results by the sync_interval_sec field.
func BySyncIntervalSec(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncIntervalSec, opts...).ToFunc()
}

// ByLastSyncAt orders the results by the last_sync_at field.
func ByLastSyncAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncAt, opts...).ToFunc()
}

// ByLastSyncStatus orders the results by the last_sync_status field.
func ByLastSyncStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncStatus, opts...).ToFunc()
}

// ByLastSyncError orders the results by the last_sync_error field.
func ByLastSyncError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncError, opts...).ToFunc()
}

// ByLastConfigHash orders the results by the last_config_hash field.
func ByLastConfigHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastConfigHash, opts...).ToFunc()
}

// ByDesiredCount orders the results by the desired_count field.
func ByDesiredCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDesiredCount, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByNextDueAt orders the results by the next_due_at field.
func ByNextDueAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextDueAt, opts...).ToFunc()
}
