// Code generated by ent, DO NOT EDIT.

package proxysubscription

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldName, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldEnabled, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldSourceType, v))
}

// SubscriptionURL applies equality check predicate on the "subscription_url" field. It's identical to SubscriptionURLEQ.
func SubscriptionURL(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldSubscriptionURL, v))
}

// InlineBody applies equality check predicate on the "inline_body" field. It's identical to InlineBodyEQ.
func InlineBody(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldInlineBody, v))
}

// NamePrefix applies equality check predicate on the "name_prefix" field. It's identical to NamePrefixEQ.
func NamePrefix(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldNamePrefix, v))
}

// Protocol applies equality check predicate on the "protocol" field. It's identical to ProtocolEQ.
func Protocol(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldProtocol, v))
}

// BindAddress applies equality check predicate on the "bind_address" field. It's identical to BindAddressEQ.
func BindAddress(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldBindAddress, v))
}

// BasePort applies equality check predicate on the "base_port" field. It's identical to BasePortEQ.
func BasePort(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldBasePort, v))
}

// MaxPorts applies equality check predicate on the "max_ports" field. It's identical to MaxPortsEQ.
func MaxPorts(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldMaxPorts, v))
}

// SyncIntervalSec applies equality check predicate on the "sync_interval_sec" field. It's identical to SyncIntervalSecEQ.
func SyncIntervalSec(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldSyncIntervalSec, v))
}

// LastSyncAt applies equality check predicate on the "last_sync_at" field. It's identical to LastSyncAtEQ.
func LastSyncAt(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldLastSyncAt, v))
}

// LastSyncStatus applies equality check predicate on the "last_sync_status" field. It's identical to LastSyncStatusEQ.
func LastSyncStatus(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldLastSyncStatus, v))
}

// LastSyncError applies equality check predicate on the "last_sync_error" field. It's identical to LastSyncErrorEQ.
func LastSyncError(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldLastSyncError, v))
}

// LastConfigHash applies equality check predicate on the "last_config_hash" field. It's identical to LastConfigHashEQ.
func LastConfigHash(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldLastConfigHash, v))
}

// DesiredCount applies equality check predicate on the "desired_count" field. It's identical to DesiredCountEQ.
func DesiredCount(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldDesiredCount, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldCreatedBy, v))
}

// NextDueAt applies equality check predicate on the "next_due_at" field. It's identical to NextDueAtEQ.
func NextDueAt(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldNextDueAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldContainsFold(FieldName, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNEQ(FieldEnabled, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldContainsFold(FieldSourceType, v))
}

// SubscriptionURLEQ applies the EQ predicate on the "subscription_url" field.
func SubscriptionURLEQ(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldSubscriptionURL, v))
}

// SubscriptionURLNEQ applies the NEQ predicate on the "subscription_url" field.
func SubscriptionURLNEQ(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNEQ(FieldSubscriptionURL, v))
}

// SubscriptionURLIn applies the In predicate on the "subscription_url" field.
func SubscriptionURLIn(vs ...string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIn(FieldSubscriptionURL, vs...))
}

// SubscriptionURLNotIn applies the NotIn predicate on the "subscription_url" field.
func SubscriptionURLNotIn(vs ...string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotIn(FieldSubscriptionURL, vs...))
}

// SubscriptionURLGT applies the GT predicate on the "subscription_url" field.
func SubscriptionURLGT(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGT(FieldSubscriptionURL, v))
}

// SubscriptionURLGTE applies the GTE predicate on the "subscription_url" field.
func SubscriptionURLGTE(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGTE(FieldSubscriptionURL, v))
}

// SubscriptionURLLT applies the LT predicate on the "subscription_url" field.
func SubscriptionURLLT(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLT(FieldSubscriptionURL, v))
}

// SubscriptionURLLTE applies the LTE predicate on the "subscription_url" field.
func SubscriptionURLLTE(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLTE(FieldSubscriptionURL, v))
}

// SubscriptionURLContains applies the Contains predicate on the "subscription_url" field.
func SubscriptionURLContains(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldContains(FieldSubscriptionURL, v))
}

// SubscriptionURLHasPrefix applies the HasPrefix predicate on the "subscription_url" field.
func SubscriptionURLHasPrefix(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldHasPrefix(FieldSubscriptionURL, v))
}

// SubscriptionURLHasSuffix applies the HasSuffix predicate on the "subscription_url" field.
func SubscriptionURLHasSuffix(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldHasSuffix(FieldSubscriptionURL, v))
}

// SubscriptionURLIsNil applies the IsNil predicate on the "subscription_url" field.
func SubscriptionURLIsNil() predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIsNull(FieldSubscriptionURL))
}

// SubscriptionURLNotNil applies the NotNil predicate on the "subscription_url" field.
func SubscriptionURLNotNil() predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotNull(FieldSubscriptionURL))
}

// SubscriptionURLEqualFold applies the EqualFold predicate on the "subscription_url" field.
func SubscriptionURLEqualFold(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEqualFold(FieldSubscriptionURL, v))
}

// SubscriptionURLContainsFold applies the ContainsFold predicate on the "subscription_url" field.
func SubscriptionURLContainsFold(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldContainsFold(FieldSubscriptionURL, v))
}

// InlineBodyEQ applies the EQ predicate on the "inline_body" field.
func InlineBodyEQ(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldInlineBody, v))
}

// InlineBodyNEQ applies the NEQ predicate on the "inline_body" field.
func InlineBodyNEQ(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNEQ(FieldInlineBody, v))
}

// InlineBodyIn applies the In predicate on the "inline_body" field.
func InlineBodyIn(vs ...string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIn(FieldInlineBody, vs...))
}

// InlineBodyNotIn applies the NotIn predicate on the "inline_body" field.
func InlineBodyNotIn(vs ...string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotIn(FieldInlineBody, vs...))
}

// InlineBodyGT applies the GT predicate on the "inline_body" field.
func InlineBodyGT(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGT(FieldInlineBody, v))
}

// InlineBodyGTE applies the GTE predicate on the "inline_body" field.
func InlineBodyGTE(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGTE(FieldInlineBody, v))
}

// InlineBodyLT applies the LT predicate on the "inline_body" field.
func InlineBodyLT(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLT(FieldInlineBody, v))
}

// InlineBodyLTE applies the LTE predicate on the "inline_body" field.
func InlineBodyLTE(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLTE(FieldInlineBody, v))
}

// InlineBodyContains applies the Contains predicate on the "inline_body" field.
func InlineBodyContains(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldContains(FieldInlineBody, v))
}

// InlineBodyHasPrefix applies the HasPrefix predicate on the "inline_body" field.
func InlineBodyHasPrefix(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldHasPrefix(FieldInlineBody, v))
}

// InlineBodyHasSuffix applies the HasSuffix predicate on the "inline_body" field.
func InlineBodyHasSuffix(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldHasSuffix(FieldInlineBody, v))
}

// InlineBodyIsNil applies the IsNil predicate on the "inline_body" field.
func InlineBodyIsNil() predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIsNull(FieldInlineBody))
}

// InlineBodyNotNil applies the NotNil predicate on the "inline_body" field.
func InlineBodyNotNil() predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotNull(FieldInlineBody))
}

// InlineBodyEqualFold applies the EqualFold predicate on the "inline_body" field.
func InlineBodyEqualFold(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEqualFold(FieldInlineBody, v))
}

// InlineBodyContainsFold applies the ContainsFold predicate on the "inline_body" field.
func InlineBodyContainsFold(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldContainsFold(FieldInlineBody, v))
}

// NamePrefixEQ applies the EQ predicate on the "name_prefix" field.
func NamePrefixEQ(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldNamePrefix, v))
}

// NamePrefixNEQ applies the NEQ predicate on the "name_prefix" field.
func NamePrefixNEQ(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNEQ(FieldNamePrefix, v))
}

// NamePrefixIn applies the In predicate on the "name_prefix" field.
func NamePrefixIn(vs ...string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIn(FieldNamePrefix, vs...))
}

// NamePrefixNotIn applies the NotIn predicate on the "name_prefix" field.
func NamePrefixNotIn(vs ...string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotIn(FieldNamePrefix, vs...))
}

// NamePrefixGT applies the GT predicate on the "name_prefix" field.
func NamePrefixGT(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGT(FieldNamePrefix, v))
}

// NamePrefixGTE applies the GTE predicate on the "name_prefix" field.
func NamePrefixGTE(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGTE(FieldNamePrefix, v))
}

// NamePrefixLT applies the LT predicate on the "name_prefix" field.
func NamePrefixLT(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLT(FieldNamePrefix, v))
}

// NamePrefixLTE applies the LTE predicate on the "name_prefix" field.
func NamePrefixLTE(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLTE(FieldNamePrefix, v))
}

// NamePrefixContains applies the Contains predicate on the "name_prefix" field.
func NamePrefixContains(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldContains(FieldNamePrefix, v))
}

// NamePrefixHasPrefix applies the HasPrefix predicate on the "name_prefix" field.
func NamePrefixHasPrefix(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldHasPrefix(FieldNamePrefix, v))
}

// NamePrefixHasSuffix applies the HasSuffix predicate on the "name_prefix" field.
func NamePrefixHasSuffix(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldHasSuffix(FieldNamePrefix, v))
}

// NamePrefixEqualFold applies the EqualFold predicate on the "name_prefix" field.
func NamePrefixEqualFold(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEqualFold(FieldNamePrefix, v))
}

// NamePrefixContainsFold applies the ContainsFold predicate on the "name_prefix" field.
func NamePrefixContainsFold(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldContainsFold(FieldNamePrefix, v))
}

// ProtocolEQ applies the EQ predicate on the "protocol" field.
func ProtocolEQ(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldProtocol, v))
}

// ProtocolNEQ applies the NEQ predicate on the "protocol" field.
func ProtocolNEQ(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNEQ(FieldProtocol, v))
}

// ProtocolIn applies the In predicate on the "protocol" field.
func ProtocolIn(vs ...string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIn(FieldProtocol, vs...))
}

// ProtocolNotIn applies the NotIn predicate on the "protocol" field.
func ProtocolNotIn(vs ...string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotIn(FieldProtocol, vs...))
}

// ProtocolGT applies the GT predicate on the "protocol" field.
func ProtocolGT(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGT(FieldProtocol, v))
}

// ProtocolGTE applies the GTE predicate on the "protocol" field.
func ProtocolGTE(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGTE(FieldProtocol, v))
}

// ProtocolLT applies the LT predicate on the "protocol" field.
func ProtocolLT(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLT(FieldProtocol, v))
}

// ProtocolLTE applies the LTE predicate on the "protocol" field.
func ProtocolLTE(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLTE(FieldProtocol, v))
}

// ProtocolContains applies the Contains predicate on the "protocol" field.
func ProtocolContains(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldContains(FieldProtocol, v))
}

// ProtocolHasPrefix applies the HasPrefix predicate on the "protocol" field.
func ProtocolHasPrefix(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldHasPrefix(FieldProtocol, v))
}

// ProtocolHasSuffix applies the HasSuffix predicate on the "protocol" field.
func ProtocolHasSuffix(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldHasSuffix(FieldProtocol, v))
}

// ProtocolEqualFold applies the EqualFold predicate on the "protocol" field.
func ProtocolEqualFold(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEqualFold(FieldProtocol, v))
}

// ProtocolContainsFold applies the ContainsFold predicate on the "protocol" field.
func ProtocolContainsFold(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldContainsFold(FieldProtocol, v))
}

// BindAddressEQ applies the EQ predicate on the "bind_address" field.
func BindAddressEQ(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldBindAddress, v))
}

// BindAddressNEQ applies the NEQ predicate on the "bind_address" field.
func BindAddressNEQ(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNEQ(FieldBindAddress, v))
}

// BindAddressIn applies the In predicate on the "bind_address" field.
func BindAddressIn(vs ...string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIn(FieldBindAddress, vs...))
}

// BindAddressNotIn applies the NotIn predicate on the "bind_address" field.
func BindAddressNotIn(vs ...string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotIn(FieldBindAddress, vs...))
}

// BindAddressGT applies the GT predicate on the "bind_address" field.
func BindAddressGT(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGT(FieldBindAddress, v))
}

// BindAddressGTE applies the GTE predicate on the "bind_address" field.
func BindAddressGTE(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGTE(FieldBindAddress, v))
}

// BindAddressLT applies the LT predicate on the "bind_address" field.
func BindAddressLT(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLT(FieldBindAddress, v))
}

// BindAddressLTE applies the LTE predicate on the "bind_address" field.
func BindAddressLTE(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLTE(FieldBindAddress, v))
}

// BindAddressContains applies the Contains predicate on the "bind_address" field.
func BindAddressContains(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldContains(FieldBindAddress, v))
}

// BindAddressHasPrefix applies the HasPrefix predicate on the "bind_address" field.
func BindAddressHasPrefix(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldHasPrefix(FieldBindAddress, v))
}

// BindAddressHasSuffix applies the HasSuffix predicate on the "bind_address" field.
func BindAddressHasSuffix(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldHasSuffix(FieldBindAddress, v))
}

// BindAddressEqualFold applies the EqualFold predicate on the "bind_address" field.
func BindAddressEqualFold(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEqualFold(FieldBindAddress, v))
}

// BindAddressContainsFold applies the ContainsFold predicate on the "bind_address" field.
func BindAddressContainsFold(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldContainsFold(FieldBindAddress, v))
}

// BasePortEQ applies the EQ predicate on the "base_port" field.
func BasePortEQ(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldBasePort, v))
}

// BasePortNEQ applies the NEQ predicate on the "base_port" field.
func BasePortNEQ(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNEQ(FieldBasePort, v))
}

// BasePortIn applies the In predicate on the "base_port" field.
func BasePortIn(vs ...int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIn(FieldBasePort, vs...))
}

// BasePortNotIn applies the NotIn predicate on the "base_port" field.
func BasePortNotIn(vs ...int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotIn(FieldBasePort, vs...))
}

// BasePortGT applies the GT predicate on the "base_port" field.
func BasePortGT(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGT(FieldBasePort, v))
}

// BasePortGTE applies the GTE predicate on the "base_port" field.
func BasePortGTE(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGTE(FieldBasePort, v))
}

// BasePortLT applies the LT predicate on the "base_port" field.
func BasePortLT(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLT(FieldBasePort, v))
}

// BasePortLTE applies the LTE predicate on the "base_port" field.
func BasePortLTE(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLTE(FieldBasePort, v))
}

// MaxPortsEQ applies the EQ predicate on the "max_ports" field.
func MaxPortsEQ(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldMaxPorts, v))
}

// MaxPortsNEQ applies the NEQ predicate on the "max_ports" field.
func MaxPortsNEQ(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNEQ(FieldMaxPorts, v))
}

// MaxPortsIn applies the In predicate on the "max_ports" field.
func MaxPortsIn(vs ...int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIn(FieldMaxPorts, vs...))
}

// MaxPortsNotIn applies the NotIn predicate on the "max_ports" field.
func MaxPortsNotIn(vs ...int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotIn(FieldMaxPorts, vs...))
}

// MaxPortsGT applies the GT predicate on the "max_ports" field.
func MaxPortsGT(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGT(FieldMaxPorts, v))
}

// MaxPortsGTE applies the GTE predicate on the "max_ports" field.
func MaxPortsGTE(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGTE(FieldMaxPorts, v))
}

// MaxPortsLT applies the LT predicate on the "max_ports" field.
func MaxPortsLT(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLT(FieldMaxPorts, v))
}

// MaxPortsLTE applies the LTE predicate on the "max_ports" field.
func MaxPortsLTE(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLTE(FieldMaxPorts, v))
}

// SyncIntervalSecEQ applies the EQ predicate on the "sync_interval_sec" field.
func SyncIntervalSecEQ(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldSyncIntervalSec, v))
}

// SyncIntervalSecNEQ applies the NEQ predicate on the "sync_interval_sec" field.
func SyncIntervalSecNEQ(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNEQ(FieldSyncIntervalSec, v))
}

// SyncIntervalSecIn applies the In predicate on the "sync_interval_sec" field.
func SyncIntervalSecIn(vs ...int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIn(FieldSyncIntervalSec, vs...))
}

// SyncIntervalSecNotIn applies the NotIn predicate on the "sync_interval_sec" field.
func SyncIntervalSecNotIn(vs ...int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotIn(FieldSyncIntervalSec, vs...))
}

// SyncIntervalSecGT applies the GT predicate on the "sync_interval_sec" field.
func SyncIntervalSecGT(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGT(FieldSyncIntervalSec, v))
}

// SyncIntervalSecGTE applies the GTE predicate on the "sync_interval_sec" field.
func SyncIntervalSecGTE(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGTE(FieldSyncIntervalSec, v))
}

// SyncIntervalSecLT applies the LT predicate on the "sync_interval_sec" field.
func SyncIntervalSecLT(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLT(FieldSyncIntervalSec, v))
}

// SyncIntervalSecLTE applies the LTE predicate on the "sync_interval_sec" field.
func SyncIntervalSecLTE(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLTE(FieldSyncIntervalSec, v))
}

// LastSyncAtEQ applies the EQ predicate on the "last_sync_at" field.
func LastSyncAtEQ(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldLastSyncAt, v))
}

// LastSyncAtNEQ applies the NEQ predicate on the "last_sync_at" field.
func LastSyncAtNEQ(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNEQ(FieldLastSyncAt, v))
}

// LastSyncAtIn applies the In predicate on the "last_sync_at" field.
func LastSyncAtIn(vs ...time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIn(FieldLastSyncAt, vs...))
}

// LastSyncAtNotIn applies the NotIn predicate on the "last_sync_at" field.
func LastSyncAtNotIn(vs ...time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotIn(FieldLastSyncAt, vs...))
}

// LastSyncAtGT applies the GT predicate on the "last_sync_at" field.
func LastSyncAtGT(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGT(FieldLastSyncAt, v))
}

// LastSyncAtGTE applies the GTE predicate on the "last_sync_at" field.
func LastSyncAtGTE(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGTE(FieldLastSyncAt, v))
}

// LastSyncAtLT applies the LT predicate on the "last_sync_at" field.
func LastSyncAtLT(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLT(FieldLastSyncAt, v))
}

// LastSyncAtLTE applies the LTE predicate on the "last_sync_at" field.
func LastSyncAtLTE(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLTE(FieldLastSyncAt, v))
}

// LastSyncAtIsNil applies the IsNil predicate on the "last_sync_at" field.
func LastSyncAtIsNil() predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIsNull(FieldLastSyncAt))
}

// LastSyncAtNotNil applies the NotNil predicate on the "last_sync_at" field.
func LastSyncAtNotNil() predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotNull(FieldLastSyncAt))
}

// LastSyncStatusEQ applies the EQ predicate on the "last_sync_status" field.
func LastSyncStatusEQ(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldLastSyncStatus, v))
}

// LastSyncStatusNEQ applies the NEQ predicate on the "last_sync_status" field.
func LastSyncStatusNEQ(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNEQ(FieldLastSyncStatus, v))
}

// LastSyncStatusIn applies the In predicate on the "last_sync_status" field.
func LastSyncStatusIn(vs ...string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIn(FieldLastSyncStatus, vs...))
}

// LastSyncStatusNotIn applies the NotIn predicate on the "last_sync_status" field.
func LastSyncStatusNotIn(vs ...string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotIn(FieldLastSyncStatus, vs...))
}

// LastSyncStatusGT applies the GT predicate on the "last_sync_status" field.
func LastSyncStatusGT(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGT(FieldLastSyncStatus, v))
}

// LastSyncStatusGTE applies the GTE predicate on the "last_sync_status" field.
func LastSyncStatusGTE(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGTE(FieldLastSyncStatus, v))
}

// LastSyncStatusLT applies the LT predicate on the "last_sync_status" field.
func LastSyncStatusLT(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLT(FieldLastSyncStatus, v))
}

// LastSyncStatusLTE applies the LTE predicate on the "last_sync_status" field.
func LastSyncStatusLTE(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLTE(FieldLastSyncStatus, v))
}

// LastSyncStatusContains applies the Contains predicate on the "last_sync_status" field.
func LastSyncStatusContains(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldContains(FieldLastSyncStatus, v))
}

// LastSyncStatusHasPrefix applies the HasPrefix predicate on the "last_sync_status" field.
func LastSyncStatusHasPrefix(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldHasPrefix(FieldLastSyncStatus, v))
}

// LastSyncStatusHasSuffix applies the HasSuffix predicate on the "last_sync_status" field.
func LastSyncStatusHasSuffix(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldHasSuffix(FieldLastSyncStatus, v))
}

// LastSyncStatusIsNil applies the IsNil predicate on the "last_sync_status" field.
func LastSyncStatusIsNil() predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIsNull(FieldLastSyncStatus))
}

// LastSyncStatusNotNil applies the NotNil predicate on the "last_sync_status" field.
func LastSyncStatusNotNil() predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotNull(FieldLastSyncStatus))
}

// LastSyncStatusEqualFold applies the EqualFold predicate on the "last_sync_status" field.
func LastSyncStatusEqualFold(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEqualFold(FieldLastSyncStatus, v))
}

// LastSyncStatusContainsFold applies the ContainsFold predicate on the "last_sync_status" field.
func LastSyncStatusContainsFold(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldContainsFold(FieldLastSyncStatus, v))
}

// LastSyncErrorEQ applies the EQ predicate on the "last_sync_error" field.
func LastSyncErrorEQ(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldLastSyncError, v))
}

// LastSyncErrorNEQ applies the NEQ predicate on the "last_sync_error" field.
func LastSyncErrorNEQ(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNEQ(FieldLastSyncError, v))
}

// LastSyncErrorIn applies the In predicate on the "last_sync_error" field.
func LastSyncErrorIn(vs ...string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIn(FieldLastSyncError, vs...))
}

// LastSyncErrorNotIn applies the NotIn predicate on the "last_sync_error" field.
func LastSyncErrorNotIn(vs ...string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotIn(FieldLastSyncError, vs...))
}

// LastSyncErrorGT applies the GT predicate on the "last_sync_error" field.
func LastSyncErrorGT(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGT(FieldLastSyncError, v))
}

// LastSyncErrorGTE applies the GTE predicate on the "last_sync_error" field.
func LastSyncErrorGTE(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGTE(FieldLastSyncError, v))
}

// LastSyncErrorLT applies the LT predicate on the "last_sync_error" field.
func LastSyncErrorLT(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLT(FieldLastSyncError, v))
}

// LastSyncErrorLTE applies the LTE predicate on the "last_sync_error" field.
func LastSyncErrorLTE(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLTE(FieldLastSyncError, v))
}

// LastSyncErrorContains applies the Contains predicate on the "last_sync_error" field.
func LastSyncErrorContains(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldContains(FieldLastSyncError, v))
}

// LastSyncErrorHasPrefix applies the HasPrefix predicate on the "last_sync_error" field.
func LastSyncErrorHasPrefix(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldHasPrefix(FieldLastSyncError, v))
}

// LastSyncErrorHasSuffix applies the HasSuffix predicate on the "last_sync_error" field.
func LastSyncErrorHasSuffix(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldHasSuffix(FieldLastSyncError, v))
}

// LastSyncErrorIsNil applies the IsNil predicate on the "last_sync_error" field.
func LastSyncErrorIsNil() predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIsNull(FieldLastSyncError))
}

// LastSyncErrorNotNil applies the NotNil predicate on the "last_sync_error" field.
func LastSyncErrorNotNil() predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotNull(FieldLastSyncError))
}

// LastSyncErrorEqualFold applies the EqualFold predicate on the "last_sync_error" field.
func LastSyncErrorEqualFold(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEqualFold(FieldLastSyncError, v))
}

// LastSyncErrorContainsFold applies the ContainsFold predicate on the "last_sync_error" field.
func LastSyncErrorContainsFold(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldContainsFold(FieldLastSyncError, v))
}

// LastConfigHashEQ applies the EQ predicate on the "last_config_hash" field.
func LastConfigHashEQ(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldLastConfigHash, v))
}

// LastConfigHashNEQ applies the NEQ predicate on the "last_config_hash" field.
func LastConfigHashNEQ(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNEQ(FieldLastConfigHash, v))
}

// LastConfigHashIn applies the In predicate on the "last_config_hash" field.
func LastConfigHashIn(vs ...string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIn(FieldLastConfigHash, vs...))
}

// LastConfigHashNotIn applies the NotIn predicate on the "last_config_hash" field.
func LastConfigHashNotIn(vs ...string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotIn(FieldLastConfigHash, vs...))
}

// LastConfigHashGT applies the GT predicate on the "last_config_hash" field.
func LastConfigHashGT(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGT(FieldLastConfigHash, v))
}

// LastConfigHashGTE applies the GTE predicate on the "last_config_hash" field.
func LastConfigHashGTE(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGTE(FieldLastConfigHash, v))
}

// LastConfigHashLT applies the LT predicate on the "last_config_hash" field.
func LastConfigHashLT(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLT(FieldLastConfigHash, v))
}

// LastConfigHashLTE applies the LTE predicate on the "last_config_hash" field.
func LastConfigHashLTE(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLTE(FieldLastConfigHash, v))
}

// LastConfigHashContains applies the Contains predicate on the "last_config_hash" field.
func LastConfigHashContains(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldContains(FieldLastConfigHash, v))
}

// LastConfigHashHasPrefix applies the HasPrefix predicate on the "last_config_hash" field.
func LastConfigHashHasPrefix(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldHasPrefix(FieldLastConfigHash, v))
}

// LastConfigHashHasSuffix applies the HasSuffix predicate on the "last_config_hash" field.
func LastConfigHashHasSuffix(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldHasSuffix(FieldLastConfigHash, v))
}

// LastConfigHashIsNil applies the IsNil predicate on the "last_config_hash" field.
func LastConfigHashIsNil() predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIsNull(FieldLastConfigHash))
}

// LastConfigHashNotNil applies the NotNil predicate on the "last_config_hash" field.
func LastConfigHashNotNil() predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotNull(FieldLastConfigHash))
}

// LastConfigHashEqualFold applies the EqualFold predicate on the "last_config_hash" field.
func LastConfigHashEqualFold(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEqualFold(FieldLastConfigHash, v))
}

// LastConfigHashContainsFold applies the ContainsFold predicate on the "last_config_hash" field.
func LastConfigHashContainsFold(v string) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldContainsFold(FieldLastConfigHash, v))
}

// DesiredCountEQ applies the EQ predicate on the "desired_count" field.
func DesiredCountEQ(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldDesiredCount, v))
}

// DesiredCountNEQ applies the NEQ predicate on the "desired_count" field.
func DesiredCountNEQ(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNEQ(FieldDesiredCount, v))
}

// DesiredCountIn applies the In predicate on the "desired_count" field.
func DesiredCountIn(vs ...int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIn(FieldDesiredCount, vs...))
}

// DesiredCountNotIn applies the NotIn predicate on the "desired_count" field.
func DesiredCountNotIn(vs ...int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotIn(FieldDesiredCount, vs...))
}

// DesiredCountGT applies the GT predicate on the "desired_count" field.
func DesiredCountGT(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGT(FieldDesiredCount, v))
}

// DesiredCountGTE applies the GTE predicate on the "desired_count" field.
func DesiredCountGTE(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGTE(FieldDesiredCount, v))
}

// DesiredCountLT applies the LT predicate on the "desired_count" field.
func DesiredCountLT(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLT(FieldDesiredCount, v))
}

// DesiredCountLTE applies the LTE predicate on the "desired_count" field.
func DesiredCountLTE(v int) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLTE(FieldDesiredCount, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotNull(FieldCreatedBy))
}

// NextDueAtEQ applies the EQ predicate on the "next_due_at" field.
func NextDueAtEQ(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldEQ(FieldNextDueAt, v))
}

// NextDueAtNEQ applies the NEQ predicate on the "next_due_at" field.
func NextDueAtNEQ(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNEQ(FieldNextDueAt, v))
}

// NextDueAtIn applies the In predicate on the "next_due_at" field.
func NextDueAtIn(vs ...time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIn(FieldNextDueAt, vs...))
}

// NextDueAtNotIn applies the NotIn predicate on the "next_due_at" field.
func NextDueAtNotIn(vs ...time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotIn(FieldNextDueAt, vs...))
}

// NextDueAtGT applies the GT predicate on the "next_due_at" field.
func NextDueAtGT(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGT(FieldNextDueAt, v))
}

// NextDueAtGTE applies the GTE predicate on the "next_due_at" field.
func NextDueAtGTE(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldGTE(FieldNextDueAt, v))
}

// NextDueAtLT applies the LT predicate on the "next_due_at" field.
func NextDueAtLT(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLT(FieldNextDueAt, v))
}

// NextDueAtLTE applies the LTE predicate on the "next_due_at" field.
func NextDueAtLTE(v time.Time) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldLTE(FieldNextDueAt, v))
}

// NextDueAtIsNil applies the IsNil predicate on the "next_due_at" field.
func NextDueAtIsNil() predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldIsNull(FieldNextDueAt))
}

// NextDueAtNotNil applies the NotNil predicate on the "next_due_at" field.
func NextDueAtNotNil() predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.FieldNotNull(FieldNextDueAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProxySubscription) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProxySubscription) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProxySubscription) predicate.ProxySubscription {
	return predicate.ProxySubscription(sql.NotPredicates(p))
}
